Repository GEOS-DEV/GEOS, pull requests merged in 2020-10, with the labels that each got.

#1152 Time History objectPath parsing and buffer size override
  src/coreComponents/fileIO/schema/docs/PackCollection.rst
  src/coreComponents/fileIO/schema/schema.xsd
  src/coreComponents/managers/TimeHistory/PackCollection.cpp
  src/coreComponents/managers/TimeHistory/PackCollection.hpp
  src/coreComponents/managers/TimeHistory/TimeHistoryCollection.hpp
Labels: effort: 1 day, flag: ready for review, flag: requires rebaseline, priority: medium, type: feature

#1073 Handling of empty regions in some ranks for MPI run using external meshed
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.hpp
  src/coreComponents/meshUtilities/PAMELAMeshGenerator.cpp
Labels: flag: ready to be merged

#1184 Sphinx documentation -- September Doc Day
  src/conf.py
  src/coreComponents/linearAlgebra/docs/LinearSolvers.rst
  src/coreComponents/physicsSolvers/SolverBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/benchmarks/Egg/dead_oil_egg.xml
  src/coreComponents/physicsSolvers/fluidFlow/benchmarks/SPE10/dead_oil_spe10_layers_83_84_85.xml
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/3D_10x10x10_compressible.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/FieldCaseCo2InjTutorial.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/FieldCaseTutorial1.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/PoroElastic_Terzaghi_FIM.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/tables_FieldCaseTuto/permx.geos
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/tables_FieldCaseTuto/permy.geos
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/tables_FieldCaseTuto/permz.geos
  src/coreComponents/physicsSolvers/simplePDE/LaplaceFEM.cpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceFEM.hpp
  src/docs/sphinx/QuickStart.rst
  src/docs/sphinx/developerGuide/KeyComponents/AddingNewSolver.rst
  src/docs/sphinx/tutorials/step01/Tutorial.rst
  src/docs/sphinx/tutorials/step02/Tutorial.rst
  src/docs/sphinx/tutorials/step03/Tutorial.rst
  src/docs/sphinx/tutorials/step03/mapping_perm.png
  src/docs/sphinx/tutorials/step03/pressureField_2e8.png
  src/docs/sphinx/tutorials/step03/pressureField_5e8.png
  src/docs/sphinx/tutorials/step03/pressureField_initial.png
  src/docs/sphinx/tutorials/step04/Tutorial.rst
  src/docs/sphinx/tutorials/step04/wellRateHistory1.hdf5
  src/docs/sphinx/tutorials/step04/wellRateHistory2.hdf5
  src/docs/sphinx/tutorials/step04/wellRateHistory3.hdf5
  src/docs/sphinx/tutorials/step04/wellRateHistory4.hdf5
  src/docs/sphinx/tutorials/step05/Tutorial.rst
  src/docs/sphinx/tutorials/step05/wellRateHistory1.hdf5
  src/docs/sphinx/tutorials/step05/wellRateHistory2.hdf5
  src/docs/sphinx/tutorials/step05/wellRateHistory3.hdf5
  src/docs/sphinx/tutorials/step05/wellRateHistory4.hdf5
  src/docs/sphinx/tutorials/step06/Tutorial.rst
  src/docs/sphinx/tutorials/step08/Tutorial.rst
  src/docs/sphinx/tutorials/step08/case_setup.png
  src/docs/sphinx/tutorials/step08/cell_centers.hdf5
  src/docs/sphinx/tutorials/step08/displacement.png
  src/docs/sphinx/tutorials/step08/pressure.png
  src/docs/sphinx/tutorials/step08/pressure_history.hdf5
  src/docs/sphinx/tutorials/step08/terzaghi_sketch.svg
Labels: flag: ready to be merged

#1218 Fix MGR DoF labeling for 3 fields or more
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGRStrategies.hpp
Labels: flag: ready for review, type: bug
