Repository GEOS-DEV/GEOS, pull requests merged in 2020-12, with the labels that each got.

#1239 Unit testing on Lassen - Laplace2D with serial direct solver
  .travis.yml
  src/coreComponents/linearAlgebra/unitTests/testLAOperations.cpp
Labels: flag: ready to be merged, type: bug

#1246 Compile mathpresso targets iff mathpresso option is requested.
  src/coreComponents/managers/CMakeLists.txt
  src/coreComponents/managers/Functions/CompositeFunction.cpp
  src/coreComponents/managers/Functions/CompositeFunction.hpp
  src/coreComponents/managers/Functions/SymbolicFunction.cpp
  src/coreComponents/managers/Functions/SymbolicFunction.hpp
  src/coreComponents/managers/unitTests/testFunctions.cpp
Labels: flag: ready for review, priority: low, type: build

#1247 Provide docker solution to docker restriction
  .travis.yml
Labels: type: build

#1224 Adding an mesh tools python package for GEOSX
  src/coreComponents/python/modules/geosx_mesh_tools_package/geosx_mesh_tools/__init__.py
  src/coreComponents/python/modules/geosx_mesh_tools_package/geosx_mesh_tools/abaqus_converter.py
  src/coreComponents/python/modules/geosx_mesh_tools_package/setup.py
Labels: flag: ready to be merged, type: feature
