Repository GEOS-DEV/GEOS, pull requests merged in 2020-09, with the labels that each got.

#1120 Fixing a bug in FunctionBase for functions applied to sets
  src/coreComponents/managers/Functions/FunctionBase.hpp
Labels: flag: ready for review, priority: high, type: bug

#1139 Using accessors when they are available.
  src/coreComponents/fileIO/coupling/ChomboCoupler.cpp
  src/coreComponents/linearAlgebra/unitTests/testDofManagerUtils.hpp
  src/coreComponents/managers/DomainPartition.cpp
  src/coreComponents/mpiCommunications/CommunicationTools.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFlow.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVMKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/unitTests/testCompMultiphaseFlow.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp
Labels: flag: ready for review, type: cleanup / refactor

#1110 Fixing issues with the new HF tutorial
  examples/hydraulicFracturing/heterogeneousInSituProperties/heterogeneousInSitu_base.xml
  src/docs/sphinx/tutorials/step09/Tutorial.rst
  src/docs/sphinx/tutorials/step09/aperture.png
  src/docs/sphinx/tutorials/step09/extents.png
  src/docs/sphinx/tutorials/step09/pressure.png
Labels: flag: ready to be merged

#836 Implement EDFM Single Phase Flow Solver
  src/coreComponents/fileIO/schema/docs/EmbeddedSurfaceGenerator_other.rst
  src/coreComponents/fileIO/schema/docs/Level0_other.rst
  src/coreComponents/fileIO/schema/docs/default_other.rst
  src/coreComponents/fileIO/schema/docs/edgeManager_other.rst
  src/coreComponents/fileIO/schema/docs/embeddedSurfacesEdgeManager_other.rst
  src/coreComponents/fileIO/schema/docs/nodeManager_other.rst
  src/coreComponents/fileIO/schema/schema.xsd.other
  src/coreComponents/fileIO/silo/SiloFile.cpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.hpp
  src/coreComponents/finiteVolume/FluxApproximationBase.hpp
  src/coreComponents/finiteVolume/TwoPointFluxApproximation.cpp
  src/coreComponents/finiteVolume/TwoPointFluxApproximation.hpp
  src/coreComponents/linearAlgebra/unitTests/testDofManagerUtils.hpp
  src/coreComponents/mesh/CellElementSubRegion.cpp
  src/coreComponents/mesh/CellElementSubRegion.hpp
  src/coreComponents/mesh/EdgeManager.cpp
  src/coreComponents/mesh/EdgeManager.hpp
  src/coreComponents/mesh/EmbeddedSurfaceRegion.cpp
  src/coreComponents/mesh/EmbeddedSurfaceRegion.hpp
  src/coreComponents/mesh/EmbeddedSurfaceSubRegion.cpp
  src/coreComponents/mesh/EmbeddedSurfaceSubRegion.hpp
  src/coreComponents/mesh/MeshLevel.cpp
  src/coreComponents/mesh/MeshLevel.hpp
  src/coreComponents/mesh/NodeManager.cpp
  src/coreComponents/mesh/NodeManager.hpp
  src/coreComponents/meshUtilities/ComputationalGeometry.cpp
  src/coreComponents/meshUtilities/ComputationalGeometry.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/fractureMatrixFlow_Embedded2d.xml
  src/coreComponents/physicsSolvers/surfaceGeneration/EmbeddedSurfaceGenerator.cpp
  src/coreComponents/physicsSolvers/surfaceGeneration/EmbeddedSurfaceGenerator.hpp
  src/docs/sphinx/CompleteXMLSchema.rst
Labels: flag: ready to be merged, flag: requires rebaseline

#1157 Fix parallel VTK output for wells
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
Labels: flag: ready to be merged, type: bug

#1158 Remove legacy .gitignore entries
  .gitignore
Labels: flag: ready for review, type: cleanup / refactor

#1165 Fixing a typo in the default executable group timestep request
  src/coreComponents/dataRepository/ExecutableGroup.hpp
Labels: flag: ready to be merged, type: bug

#1177 Applying the formatter to all xml files in the repository
  examples/hydraulicFracturing/KGD/KGD_ZeroToughness.xml
  src/coreComponents/physicsSolvers/fluidFlow/benchmarks/Egg/dead_oil_egg.xml
  src/coreComponents/physicsSolvers/fluidFlow/benchmarks/SPE10/dead_oil_spe10_layers_83_84_85.xml
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/fractureMatrixFlow_Embedded2d.xml
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/staircase_3d.xml
  src/coreComponents/physicsSolvers/fluidFlow/wells/integratedTests/compositionalMultiphaseWell/staircase_co2_wells_3d.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/FieldCaseTutorial1.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/FlowProppantTransport_2d.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/Hydrofracture_KGD_EdgeBased_C3D6.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/Hydrofracture_SinglePhase_2d.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/KGDBase.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/KGDTest_GEOSX.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/KGD_ZeroToughness.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/KGD_ZeroViscosity.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/PhaseFieldFracture_DamageAndLoad.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/PhaseFieldFracture_DamageOnly.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/Sneddon_conforming.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/poroElastic_Mandel.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/poroElastic_Terzaghi_monolithic.xml
  src/coreComponents/physicsSolvers/solidMechanics/benchmarks/SSLE-QS-small.xml
  src/coreComponents/physicsSolvers/solidMechanics/integratedTests/sedov_base.xml
  src/coreComponents/physicsSolvers/solidMechanics/integratedTests/sedov_with_bias.xml
  src/coreComponents/physicsSolvers/solidMechanics/integratedTests/solidMechBlock.xml
  src/coreComponents/unitTests/xmlTests/basic_input.xml
Labels: flag: ready for review, flag: ready to be merged

#1182 Update brew
  .travis.yml
Labels: type: build
