Repository GEOS-DEV/GEOS, pull requests merged in 2020-11, with the labels that each got.

#1178 Adding a script to check xml attribute names
  scripts/checkParameterCase.py
Labels: flag: ready to be merged, type: cleanup / refactor

#1236 Add integratedTests workaround to QuickStart guide
  src/docs/sphinx/QuickStart.rst
Labels: flag: ready for review, type: documentation

#1126 release/0.2.x candidate
  NOTICE
  README.md
  RELEASE
  RELEASE_NOTES.md
  src/docs/sphinx/developerGuide/Contributing/GitWorkflow.rst
  src/docs/sphinx/developerGuide/Contributing/index_contributing.rst
Labels: flag: ready for review
