Repository GEOS-DEV/GEOS, pull requests merged in 2021-07, with the labels that each got.

#1419 Refactor VEM classes to allow computations on GPU
  src/coreComponents/mesh/utilities/ComputationalGeometry.hpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceBaseH1.cpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceBaseH1.hpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceFEM.cpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceFEM.hpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceVEM.cpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceVEM.hpp
  src/coreComponents/unitTests/virtualElementTests/testVirtualElementBase.cpp
  src/coreComponents/virtualElement/ConformingVirtualElementOrder1.hpp
  src/coreComponents/virtualElement/ConformingVirtualElementOrder1_impl.hpp
  src/coreComponents/virtualElement/VirtualElementBase.hpp
  src/docs/sphinx/developerGuide/KeyComponents/AddingNewSolver.rst
Labels: flag: ready to be merged

#1484 VTK output improvements
  src/coreComponents/codingUtilities/StringUtilities.hpp
  src/coreComponents/codingUtilities/traits.hpp
  src/coreComponents/common/CMakeLists.txt
  src/coreComponents/common/DataTypes.hpp
  src/coreComponents/common/Span.hpp
  src/coreComponents/constitutive/ConstitutiveBase.cpp
  src/coreComponents/constitutive/capillaryPressure/CapillaryPressureBase.cpp
  src/coreComponents/constitutive/capillaryPressure/CapillaryPressureBase.hpp
  src/coreComponents/constitutive/fluid/MultiFluidBase.cpp
  src/coreComponents/constitutive/fluid/MultiFluidBase.hpp
  src/coreComponents/constitutive/relativePermeability/RelativePermeabilityBase.cpp
  src/coreComponents/constitutive/relativePermeability/RelativePermeabilityBase.hpp
  src/coreComponents/constitutive/relativePermeability/TableRelativePermeability.cpp
  src/coreComponents/constitutive/solid/SolidBase.cpp
  src/coreComponents/dataRepository/Group.hpp
  src/coreComponents/dataRepository/Wrapper.hpp
  src/coreComponents/dataRepository/WrapperBase.cpp
  src/coreComponents/dataRepository/WrapperBase.hpp
  src/coreComponents/dataRepository/wrapperHelpers.hpp
  src/coreComponents/fileIO/CMakeLists.txt
  src/coreComponents/fileIO/silo/SiloFile.cpp
  src/coreComponents/fileIO/vtk/VTKGEOSXData.cpp
  src/coreComponents/fileIO/vtk/VTKGEOSXData.hpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
Labels: flag: ready for review, type: feature

#1487 Proposal for type dispatch
  src/coreComponents/common/CMakeLists.txt
  src/coreComponents/common/DataTypes.hpp
  src/coreComponents/common/TypeDispatch.hpp
  src/coreComponents/common/unitTests/CMakeLists.txt
  src/coreComponents/common/unitTests/testTypeDispatch.cpp
  src/coreComponents/dataRepository/Wrapper.hpp
  src/coreComponents/fieldSpecification/FieldSpecificationBase.hpp
  src/coreComponents/fileIO/silo/SiloFile.cpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
  src/coreComponents/linearAlgebra/DofManager.cpp
  src/coreComponents/mesh/CellElementSubRegion.cpp
Labels: type: cleanup / refactor

#1433 CMake build cleanup
  scripts/circular_dependencies.sh
  scripts/find_cycles.py
  src/cmake/thirdparty/SetupGeosxThirdParty.cmake
  src/coreComponents/CMakeLists.txt
  src/coreComponents/codingUtilities/tests/CMakeLists.txt
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/unitTests/CMakeLists.txt
  src/coreComponents/dataRepository/CMakeLists.txt
  src/coreComponents/dataRepository/unitTests/CMakeLists.txt
  src/coreComponents/discretizationMethods/CMakeLists.txt
  src/coreComponents/events/CMakeLists.txt
  src/coreComponents/fieldSpecification/CMakeLists.txt
  src/coreComponents/fieldSpecification/FieldSpecificationManager.hpp
  src/coreComponents/fileIO/CMakeLists.txt
  src/coreComponents/finiteElement/CMakeLists.txt
  src/coreComponents/finiteElement/unitTests/CMakeLists.txt
  src/coreComponents/finiteVolume/CMakeLists.txt
  src/coreComponents/functions/CMakeLists.txt
  src/coreComponents/linearAlgebra/CMakeLists.txt
  src/coreComponents/linearAlgebra/unitTests/CMakeLists.txt
  src/coreComponents/mainInterface/CMakeLists.txt
  src/coreComponents/mesh/CMakeLists.txt
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/schema/CMakeLists.txt
  src/coreComponents/unitTests/constitutiveTests/CMakeLists.txt
  src/coreComponents/unitTests/constitutiveTests/testDamage.cpp
  src/coreComponents/unitTests/dataRepositoryTests/CMakeLists.txt
  src/coreComponents/unitTests/fieldSpecificationTests/CMakeLists.txt
  src/coreComponents/unitTests/fileIOTests/CMakeLists.txt
  src/coreComponents/unitTests/finiteVolumeTests/CMakeLists.txt
  src/coreComponents/unitTests/fluidFlowTests/CMakeLists.txt
  src/coreComponents/unitTests/functionsTests/CMakeLists.txt
  src/coreComponents/unitTests/linearAlgebraTests/CMakeLists.txt
  src/coreComponents/unitTests/meshTests/CMakeLists.txt
  src/coreComponents/unitTests/virtualElementTests/CMakeLists.txt
  src/coreComponents/unitTests/wellsTests/CMakeLists.txt
  src/coreComponents/unitTests/xmlTests/CMakeLists.txt
Labels: flag: ready for review

#1465 Specificy multiple input xml files from command line
  src/coreComponents/common/initializeEnvironment.cpp
  src/coreComponents/common/initializeEnvironment.hpp
  src/coreComponents/dataRepository/xmlWrapper.cpp
  src/coreComponents/dataRepository/xmlWrapper.hpp
  src/coreComponents/mainInterface/ProblemManager.cpp
  src/coreComponents/mainInterface/initialization.cpp
  src/coreComponents/schema/docs/SurfaceGenerator_other.rst
Labels: flag: ready for review

#1493 Remove static_if
  src/coreComponents/codingUtilities/CMakeLists.txt
  src/coreComponents/codingUtilities/static_if.hpp
  src/coreComponents/dataRepository/BufferOps.hpp
  src/coreComponents/dataRepository/BufferOpsDevice.hpp
  src/coreComponents/dataRepository/BufferOps_inline.hpp
  src/coreComponents/schema/docs/SurfaceGenerator_other.rst
Labels: Issue Day, flag: ready for review, flag: ready to be merged, type: cleanup / refactor

#1511 Updating tutorial step08
  src/docs/sphinx/tutorials/step08/Tutorial.rst
Labels: flag: ready for review, type: documentation

#1512 Moved resizeFields to registerDataOnMesh in compositional solvers
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.hpp
Labels: flag: ready to be merged

#1474 Docs for Analytical Verification of Drucker-Prager Model
  examples/plasticity/DruckerPrager_Verification.xml
  src/docs/sphinx/tutorials/step11/Tutorial.rst
  src/docs/sphinx/tutorials/step11/Verification.png
  src/docs/sphinx/tutorials/step11/WellMesh.png
  src/docs/sphinx/tutorials/step11/Wellbore.png
Labels: flag: ready for review, type: documentation

#1490 Add missing & Remove duplicated files in CMakeLists.txt
  src/CMakeLists.txt
  src/cmake/CMakeBasics.cmake
  src/cmake/GeosxConfig.cmake
  src/cmake/GeosxMacros.cmake
  src/cmake/GeosxOptions.cmake
  src/coreComponents/CMakeLists.txt
  src/coreComponents/codingUtilities/CMakeLists.txt
  src/coreComponents/common/CMakeLists.txt
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/dataRepository/CMakeLists.txt
  src/coreComponents/discretizationMethods/CMakeLists.txt
  src/coreComponents/events/CMakeLists.txt
  src/coreComponents/fieldSpecification/CMakeLists.txt
  src/coreComponents/fileIO/CMakeLists.txt
  src/coreComponents/finiteElement/CMakeLists.txt
  src/coreComponents/finiteVolume/CMakeLists.txt
  src/coreComponents/functions/CMakeLists.txt
  src/coreComponents/linearAlgebra/CMakeLists.txt
  src/coreComponents/mainInterface/CMakeLists.txt
  src/coreComponents/math/CMakeLists.txt
  src/coreComponents/mesh/CMakeLists.txt
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/python/CMakeLists.txt
  src/coreComponents/schema/CMakeLists.txt
  src/coreComponents/virtualElement/CMakeLists.txt
  src/externalComponents/CMakeLists.txt
  src/pygeosx/CMakeLists.txt
  src/thirdparty/CMakeLists.txt
Labels: flag: ready to be merged, type: cleanup / refactor

#1519 Fix schema generation crash + minor bugfixes
  scripts/SchemaToRSTDocumentation.py
  scripts/updateRstTables.bash
  scripts/validateXMLFiles.bash
  src/CMakeLists.txt
  src/cmake/GeosxConfig.cmake
  src/coreComponents/common/GeosxConfig.hpp.in
  src/coreComponents/constitutive/fluid/multiFluidSelector.hpp
  src/coreComponents/fileIO/schema/docs/InternalWellbore.rst
  src/coreComponents/fileIO/schema/docs/InternalWellbore_other.rst
  src/coreComponents/fileIO/schema/docs/Traction.rst
  src/coreComponents/fileIO/schema/docs/Traction_other.rst
  src/coreComponents/fileIO/schema/docs/TriaxialDriver.rst
  src/coreComponents/fileIO/schema/docs/TriaxialDriver_other.rst
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/schema/docs/BiotPorosity_other.rst
  src/coreComponents/schema/docs/PressurePorosity_other.rst
  src/coreComponents/schema/schema.xsd.other
  src/docs/doxygen/GeosxConfig.hpp
Labels: flag: ready for review, flag: ready to be merged

#1467 Add new cluster target and clean CI
  .travis.yml
  host-configs/TOTAL/pecan.cmake
  host-configs/environment.cmake
  scripts/travis_build_and_test.sh
  src/coreComponents/unitTests/virtualElementTests/testVirtualElementBase.cpp
Labels: flag: ready to be merged, flag: requires updated TPL(s)

#1527 Remove unused TPLs
  .travis.yml
  src/docs/sphinx/buildGuide/Dependencies.rst
Labels: flag: ready for review, flag: ready to be merged, type: cleanup / refactor
