Repository GEOS-DEV/GEOS, pull requests merged in 2021-01, with the labels that each got.

#1206 Fixed bug related to matching perforations to reservoir elements
  src/coreComponents/mesh/WellElementRegion.cpp
  src/coreComponents/mesh/WellElementSubRegion.cpp
  src/coreComponents/meshUtilities/PerforationData.cpp
  src/coreComponents/meshUtilities/PerforationData.hpp
Labels: flag: ready to be merged, type: bug

#1276 Fix missing blob on GCP
  .travis.yml
Labels: priority: critical

#1220 Virtual Element Method
  src/coreComponents/CMakeLists.txt
  src/coreComponents/virtualElement/CMakeLists.txt
  src/coreComponents/virtualElement/ConformingVirtualElementOrder1.cpp
  src/coreComponents/virtualElement/ConformingVirtualElementOrder1.hpp
  src/coreComponents/virtualElement/VirtualElementBase.hpp
  src/coreComponents/virtualElement/unitTests/CMakeLists.txt
  src/coreComponents/virtualElement/unitTests/testVirtualElementBase.cpp
Labels: flag: ready to be merged

#1270 Travis Cuda Clang Debug Build
  .travis.yml
  scripts/travis_build_and_test.sh
Labels: flag: ready for review

#1268 Fix to default destructor missing
  src/coreComponents/constitutive/solid/Damage.cpp
  src/coreComponents/constitutive/solid/Damage.hpp
Labels: flag: ready to be merged

#1293 Removed Doxygen warnings on Quartz
  src/coreComponents/dataRepository/Group.hpp
  src/coreComponents/dataRepository/Wrapper.hpp
  src/coreComponents/managers/DomainPartition.hpp
  src/coreComponents/managers/Events/EventBase.hpp
  src/coreComponents/managers/Events/HaltEvent.hpp
  src/coreComponents/managers/Events/PeriodicEvent.hpp
  src/coreComponents/managers/Events/SoloEvent.hpp
  src/coreComponents/managers/Outputs/BlueprintOutput.hpp
  src/coreComponents/managers/Outputs/ChomboIO.hpp
  src/coreComponents/managers/Outputs/OutputManager.hpp
  src/coreComponents/managers/Outputs/RestartOutput.hpp
  src/coreComponents/managers/Outputs/SiloOutput.hpp
  src/coreComponents/managers/Outputs/TimeHistoryOutput.hpp
  src/coreComponents/managers/Outputs/VTKOutput.hpp
  src/coreComponents/managers/Tasks/TasksManager.hpp
  src/coreComponents/managers/TimeHistory/PackCollection.hpp
  src/coreComponents/mesh/ElementRegionBase.hpp
  src/coreComponents/mesh/ElementRegionManager.hpp
  src/coreComponents/mesh/WellElementSubRegion.hpp
  src/coreComponents/mesh/deprecated/FaceElementRegion.hpp
Labels: flag: ready to be merged, type: documentation

#1294 Minor cameBack correction
  src/coreComponents/physicsSolvers/surfaceGeneration/SurfaceGenerator.cpp
Labels: effort: 1 hour

#1304 Fix to boundedPlane to avoid missing some embedded elements.
  src/coreComponents/meshUtilities/SimpleGeometricObjects/BoundedPlane.cpp
  src/coreComponents/meshUtilities/SimpleGeometricObjects/BoundedPlane.hpp
Labels: flag: ready to be merged

#1287 Updating publications.rst
  src/docs/sphinx/Publications.rst
Labels: flag: ready for review, type: documentation

#1306 Fixed crash in SinglePhaseFVM with wells and fractures
  src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoir.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoir.hpp
Labels: flag: ready to be merged
