Repository GEOS-DEV/GEOS, pull requests merged in 2021-09, with the labels that each got.

#1557 Fix for reference porosity import
  src/coreComponents/mesh/generators/PAMELAMeshGenerator.cpp
  src/coreComponents/physicsSolvers/fluidFlow/benchmarks/Egg/dead_oil_egg.xml
Labels: type: bug, flag: ready to be merged, flag: ready for review

#1556 Bugfix for #1550
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVMKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVMKernels.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsFluxKernels.cpp
Labels: type: bug, flag: ready to be merged, flag: ready for review

#1542 Doc for cased wellbore problem
  src/coreComponents/physicsSolvers/solidMechanics/benchmarks/CasedElasticWellbore.xml
  src/docs/sphinx/advancedExamples/elasticCasedWellbore/Index.rst
  src/docs/sphinx/advancedExamples/elasticCasedWellbore/mesh.png
  src/docs/sphinx/advancedExamples/elasticCasedWellbore/stress_11.curve
  src/docs/sphinx/advancedExamples/elasticCasedWellbore/stress_22.curve
  src/docs/sphinx/advancedExamples/elasticCasedWellbore/validation.png
Labels: flag: ready to be merged, flag: ready for review

#1558 Fix #1524
  scripts/checkDoxygenWarnings.bash
  src/coreComponents/codingUtilities/StringUtilities.cpp
  src/coreComponents/common/Logger.hpp
  src/coreComponents/common/Tensor.hpp
  src/coreComponents/dataRepository/Wrapper.hpp
  src/coreComponents/dataRepository/unitTests/testXmlWrapper.cpp
  src/coreComponents/dataRepository/xmlWrapper.cpp
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/PhaseFieldFracture_SpectralSplit.xml
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/tests/generate_test_xml.py
  src/coreComponents/unitTests/fluidFlowTests/testCompMultiphaseFlow.cpp
  src/coreComponents/unitTests/fluidFlowTests/testCompMultiphaseFlowHybrid.cpp
  src/coreComponents/unitTests/wellsTests/testReservoirCompositionalMultiphaseMSWells.cpp
  src/coreComponents/unitTests/wellsTests/testReservoirSinglePhaseMSWells.cpp
  src/docs/doxygen/CMakeLists.txt
  src/docs/sphinx/developerGuide/KeyComponents/XML.rst
Labels: flag: ready to be merged, flag: ready for review

#1572 Added calls to reserve in transmissibilities precomputation
  src/coreComponents/finiteVolume/CellElementStencilTPFA.cpp
  src/coreComponents/finiteVolume/CellElementStencilTPFA.hpp
  src/coreComponents/finiteVolume/FaceElementToCellStencil.cpp
  src/coreComponents/finiteVolume/FaceElementToCellStencil.hpp
  src/coreComponents/finiteVolume/TwoPointFluxApproximation.cpp
Labels: flag: ready to be merged

#1574 Move xml files of wellbore problems to benchmark folders
  src/coreComponents/physicsSolvers/multiphysics/benchmarks/WellboreProblem_Base.xml
  src/coreComponents/physicsSolvers/multiphysics/benchmarks/WellboreProblem_PoroDruckerPrager.xml
  src/coreComponents/physicsSolvers/multiphysics/benchmarks/WellboreProblem_PoroElastic.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/ExtendedDruckerPrager_Wellbore.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/PoroExtendedDruckerPrager_Wellbore.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/WellboreProblem_Base.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/WellboreProblem_PoroDruckerPrager.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/WellboreProblem_PoroElastic.xml
  src/coreComponents/physicsSolvers/solidMechanics/benchmarks/DruckerPrager_Verification.xml
  src/coreComponents/physicsSolvers/solidMechanics/integratedTests/ExtendedDruckerPrager_Wellbore.xml
  src/coreComponents/physicsSolvers/solidMechanics/integratedTests/PlasticWell_Base.xml
  src/docs/sphinx/advancedExamples/validationStudies/edpWellbore/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/poromechanicsWellbore/Example.rst
Labels: type: documentation, flag: ready to be merged, flag: ready for review

#1567 Documentation for docker development.
  src/docs/sphinx/buildGuide/UsingDocker.rst
  src/docs/sphinx/developerGuide/Contributing/UsingDocker.rst
  src/docs/sphinx/developerGuide/Contributing/developingOnDocker.rst
  src/docs/sphinx/developerGuide/Contributing/index_contributing.rst
Labels: type: documentation, flag: ready for review

#1571 Doc for deviated elastic wellbore
  src/coreComponents/physicsSolvers/solidMechanics/benchmarks/DeviatedElasticWellbore.xml
  src/docs/sphinx/advancedExamples/validationStudies/Index.rst
  src/docs/sphinx/advancedExamples/validationStudies/casedElasticWellbore/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/casedElasticWellbore/mesh.png
  src/docs/sphinx/advancedExamples/validationStudies/casedElasticWellbore/stress_11.curve
  src/docs/sphinx/advancedExamples/validationStudies/casedElasticWellbore/stress_22.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedElasticWellbore/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/deviatedElasticWellbore/mesh.png
  src/docs/sphinx/advancedExamples/validationStudies/deviatedElasticWellbore/stress_11.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedElasticWellbore/stress_12.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedElasticWellbore/stress_13.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedElasticWellbore/stress_22.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedElasticWellbore/stress_23.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedElasticWellbore/stress_33.curve
  src/docs/sphinx/advancedExamples/validationStudies/elasticCasedWellbore/validation.png
Labels: flag: ready to be merged, flag: ready for review

#1577 Correct wrong markdown formatting
  src/docs/sphinx/developerGuide/Contributing/UsingDocker.rst
Labels: type: documentation, flag: ready for review

#1581 Add version output
  src/VERSION
  src/cmake/GeosxConfig.cmake
  src/coreComponents/common/GeosxConfig.hpp.in
  src/coreComponents/common/initializeEnvironment.cpp
  src/coreComponents/mainInterface/GeosxState.hpp
  src/coreComponents/mainInterface/initialization.cpp
  src/coreComponents/mainInterface/initialization.hpp
  src/docs/doxygen/GeosxConfig.hpp
  src/main/main.cpp
Labels: type: feature, flag: ready to be merged, flag: ready for review

#1583 Improve version header generation
  src/CMakeLists.txt
  src/cmake/GeosxConfig.cmake
  src/cmake/GeosxVersion.cmake
  src/coreComponents/common/GeosxConfig.hpp.in
  src/coreComponents/mainInterface/CMakeLists.txt
  src/coreComponents/mainInterface/GeosxVersion.hpp.in
  src/coreComponents/mainInterface/initialization.cpp
  src/docs/doxygen/GeosxConfig.hpp
Labels: flag: ready for review

#1590 Add Ninja job pool limit options
  src/cmake/GeosxOptions.cmake
  src/docs/sphinx/buildGuide/BuildProcess.rst
Labels: type: build, flag: ready to be merged, flag: ready for review

#1589 Fixed negative cell volume with reverseZ on CPG
  src/coreComponents/mesh/CellBlock.hpp
  src/coreComponents/mesh/generators/PAMELAMeshGenerator.cpp
  src/coreComponents/mesh/utilities/ComputationalGeometry.hpp
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_pyramid_gravity.xml
  src/coreComponents/unitTests/finiteVolumeTests/testMimeticInnerProducts.cpp
Labels: type: bug, flag: ready to be merged

#1596 Poromechanics kernels refactoring
  src/coreComponents/constitutive/solid/PorousSolid.hpp
  src/coreComponents/constitutive/solid/porosity/BiotPorosity.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanicsKernel.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsKernel.hpp
Labels: type: cleanup / refactor, flag: ready for review

#1602 update TPL in Pangea host config
  host-configs/TOTAL/pangea2-base.cmake
Labels: flag: ready to be merged

#1582 Xcode build fix
  src/coreComponents/python/CMakeLists.txt
Labels: flag: ready for review

#1605 Add TPL note to QuickStart
  src/docs/sphinx/QuickStart.rst
Labels: flag: ready for review

#1573 [Doc] advanced example for simulating proppant slot test
  src/coreComponents/physicsSolvers/multiphysics/benchmarks/Proppant-transport-validation-case.xml
  src/docs/sphinx/advancedExamples/validationStudies/Index.rst
  src/docs/sphinx/advancedExamples/validationStudies/proppantSlotTest/Comparison.png
  src/docs/sphinx/advancedExamples/validationStudies/proppantSlotTest/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/proppantSlotTest/Validation.png
  src/docs/sphinx/advancedExamples/validationStudies/proppantSlotTest/config.png
  src/docs/sphinx/advancedExamples/validationStudies/proppantSlotTest/experiment-data.txt
  src/docs/sphinx/advancedExamples/validationStudies/proppantSlotTest/experiment-data2.txt
  src/docs/sphinx/advancedExamples/validationStudies/proppantSlotTest/mesh.png
  src/docs/sphinx/advancedExamples/validationStudies/proppantSlotTest/model-results.txt
  src/docs/sphinx/advancedExamples/validationStudies/proppantSlotTest/model-results2.txt
Labels: type: documentation, flag: ready to be merged, flag: ready for review

#1608 Correct some XMLs
  examples/hydraulicFracturing/heterogeneousInSituProperties/heterogeneousInSitu_base.xml
  src/coreComponents/physicsSolvers/solidMechanics/integratedTests/mechanicsWithHeterogeneousMaterials.xml
Labels: flag: ready to be merged
