Repository GEOS-DEV/GEOS, pull requests merged in 2021-02, with the labels that each got.

#1332 Updated Build Guide
  src/coreComponents/constitutive/docs/LinearElasticAnisotropic.rst
  src/coreComponents/constitutive/docs/LinearElasticIsotropic.rst
  src/coreComponents/constitutive/docs/PoroLinearElasticAnisotropic.rst
  src/coreComponents/constitutive/docs/PoroLinearElasticIsotropic.rst
  src/coreComponents/constitutive/docs/SolidMechanicsModels.rst
  src/coreComponents/constitutive/docs/TwoInvariantPlasticity.rst
  src/coreComponents/constitutive/relativePermeability/BrooksCoreyRelativePermeability.hpp
  src/coreComponents/finiteElement/docs/FiniteElement.rst
  src/coreComponents/finiteVolume/docs/FiniteVolume.rst
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/docs/CompositionalMultiphaseFlow.rst
  src/coreComponents/physicsSolvers/fluidFlow/docs/ProppantTransport.rst
  src/coreComponents/physicsSolvers/fluidFlow/docs/SinglePhaseFlow.rst
  src/coreComponents/physicsSolvers/fluidFlow/unitTests/testCompMultiphaseFlow.cpp
  src/docs/sphinx/QuickStart.rst
  src/docs/sphinx/buildGuide/BuildProcess.rst
  src/docs/sphinx/buildGuide/Dependencies.rst
  src/docs/sphinx/buildGuide/Index.rst
  src/docs/sphinx/buildGuide/Prerequisites.rst
  src/docs/sphinx/buildGuide/SpackUberenv.rst
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/Instructions.rst
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/Ubuntu_installation_01.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/Ubuntu_installation_02.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/Ubuntu_installation_03.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/Ubuntu_installation_04.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/Ubuntu_installation_05.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VM_install_01.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VM_install_02.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VM_install_03.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VM_install_04.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VM_install_05.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VM_install_06.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VM_install_07.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VM_install_09.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VM_settings_01.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VM_settings_02.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VM_settings_03.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VM_settings_04c.png
  src/docs/sphinx/buildGuide/ubuntuVirtualMachineOnOSX/VirtualBox_error.png
  src/docs/sphinx/developerGuide/Contributing/Caliper.rst
  src/docs/sphinx/developerGuide/Contributing/GitWorkflow.rst
  src/docs/sphinx/developerGuide/Contributing/IntegratedTests.rst
  src/docs/sphinx/developerGuide/Contributing/UnitTests.rst
  src/docs/sphinx/developerGuide/KeyComponents/LvArray.rst
  src/docs/sphinx/developerGuide/KeyComponents/XML.rst
  src/docs/sphinx/tutorials/step08/Tutorial.rst
Labels: type: documentation

#1337 Fix Debug-build compile fail on Lassen
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVMKernels.hpp
Labels: flag: ready for review, priority: high, type: bug

#1330 Update CO2-brine model documentation
  src/coreComponents/constitutive/docs/BlackOilFluid.rst
  src/coreComponents/constitutive/docs/BrooksCoreyCapillaryPressure.rst
  src/coreComponents/constitutive/docs/BrooksCoreyRelativePermeability.rst
  src/coreComponents/constitutive/docs/CO2Brine.rst
  src/coreComponents/constitutive/docs/CompositionalMultiphaseFluid.rst
  src/coreComponents/constitutive/docs/CompressibleSinglePhaseFluid.rst
  src/coreComponents/constitutive/docs/ThreePhaseRelativePermeability.rst
  src/coreComponents/constitutive/docs/VanGenuchtenCapillaryPressure.rst
Labels: flag: ready to be merged, type: documentation
