Repository GEOS-DEV/GEOS, pull requests merged in 2021-10, with the labels that each got.

#1585 Doc for deviated PoroElastic wellbore
  inputFiles/multiphysics/DeviatedPoroElasticWellbore_Drilling_Base.xml
  inputFiles/multiphysics/DeviatedPoroElasticWellbore_Drilling_Example.xml
  inputFiles/multiphysics/DeviatedPoroElasticWellbore_Drilling_Smoke.xml
  inputFiles/multiphysics/DeviatedPoroElasticWellbore_Injection_Base.xml
  inputFiles/multiphysics/DeviatedPoroElasticWellbore_Injection_Example.xml
  inputFiles/multiphysics/DeviatedPoroElasticWellbore_Injection_Smoke.xml
  scripts/postProcessing/wellboreAnalyticalResultsForBenchmarking/elasticVerticalWellbore.py
  scripts/postProcessing/wellboreAnalyticalResultsForBenchmarking/poroelasticVerticalWellbore.py
  src/docs/sphinx/advancedExamples/validationStudies/Index.rst
  src/docs/sphinx/advancedExamples/validationStudies/casedElasticWellbore/mesh.png
  src/docs/sphinx/advancedExamples/validationStudies/deviatedElasticWellbore/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/deviatedElasticWellbore/mesh.png
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/Example2.rst
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/pressure.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/pressure.png
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/pressure_drilling.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/pressure_drilling.png
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/stress_11.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/stress_11_drilling.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/stress_12.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/stress_12_drilling.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/stress_13.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/stress_13_drilling.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/stress_22.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/stress_22_drilling.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/stress_23.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/stress_23_drilling.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/stress_33.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/stress_33_drilling.curve
  src/docs/sphinx/advancedExamples/validationStudies/deviatedPoroElasticWellbore/wellboreAnalyticalSolutions.py
  src/docs/sphinx/advancedExamples/validationStudies/verticalPoroElastoPlasticWellbore/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/verticalPoroElastoPlasticWellbore/PoroDP_Stress.png
  src/docs/sphinx/advancedExamples/validationStudies/verticalPoroElastoPlasticWellbore/PoroDP_WellMesh.png
  src/docs/sphinx/advancedExamples/validationStudies/verticalPoroElastoPlasticWellbore/PoroDP_X.png
  src/docs/sphinx/advancedExamples/validationStudies/verticalPoroElastoPlasticWellbore/PoroDP_wellSketch.png
  src/docs/sphinx/advancedExamples/validationStudies/verticalPoroElastoPlasticWellbore/PoroElastic_PP.png
  src/docs/sphinx/advancedExamples/validationStudies/verticalPoroElastoPlasticWellbore/PoroElastic_X.png
Labels: type: documentation, flag: ready to be merged

#1614 Fix broken links in tutorial examples
  examples/proppantTransport/Proppant-transport-validation-case.xml
  src/coreComponents/physicsSolvers/multiphysics/benchmarks/Proppant-transport-validation-case.xml
  src/docs/sphinx/advancedExamples/validationStudies/mccWellbore/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/proppantSlotTest/Example.rst
Labels: flag: ready to be merged, flag: ready for review

#1609 Add pygeosx tutorials and update advanced xml features
  examples/pygeosxExamples/hydraulicFractureWithMonitor/heterogeneousInSitu_base.xml
  examples/pygeosxExamples/hydraulicFractureWithMonitor/heterogeneousInSitu_singleFracture.xml
  examples/pygeosxExamples/hydraulicFractureWithMonitor/hydraulicFracture.xml
  examples/pygeosxExamples/hydraulicFractureWithMonitor/hydraulicFractureWithMonitor.py
  examples/pygeosxExamples/sedovWithStressFunction/modified_sedov.xml
  examples/pygeosxExamples/sedovWithStressFunction/run_sedov_problem.py
  examples/pygeosxExamples/sedovWithStressFunction/sedov.xml
  scripts/automatic_xml_preprocess.sh
  src/coreComponents/fileIO/doc/InputXMLFiles.rst
  src/coreComponents/python/CMakeLists.txt
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/__main__.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/attribute_coverage.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/geosx_xml_tools_documentation.rst
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/regex_tools.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/table_generator.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/tests/generate_test_xml.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/tests/test_manager.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/unit_manager.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/xml_formatter.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/xml_processor.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/xml_redundancy_check.py
  src/coreComponents/python/modules/geosx_xml_tools_package/setup.py
  src/docs/sphinx/advancedExamples/Index.rst
  src/docs/sphinx/advancedExamples/pygeosxExamples/Index.rst
  src/docs/sphinx/advancedExamples/pygeosxExamples/inSituDataMonitor/AdvancedExample.rst
  src/docs/sphinx/advancedExamples/pygeosxExamples/initialConditionModification/AdvancedExample.rst
  src/docs/sphinx/basicExamples/hydraulicFracturing/Example.rst
  src/docs/sphinx/userGuide/Index.rst
  src/pygeosx/pygeosx_documentation.rst
Labels: type: feature, type: documentation, type: pygeosx

#1612 Bugfixes for time history functionality.
  src/coreComponents/dataRepository/HistoryDataSpec.hpp
  src/coreComponents/fileIO/timeHistory/PackCollection.cpp
Labels: type: bug, priority: low, flag: ready for review, new

#1617 Allow nested XML includes
  src/coreComponents/dataRepository/CMakeLists.txt
  src/coreComponents/dataRepository/Group.cpp
  src/coreComponents/dataRepository/Wrapper.cpp
  src/coreComponents/dataRepository/Wrapper.hpp
  src/coreComponents/dataRepository/WrapperBase.cpp
  src/coreComponents/dataRepository/xmlWrapper.cpp
  src/coreComponents/dataRepository/xmlWrapper.hpp
  src/coreComponents/mainInterface/ProblemManager.cpp
  src/coreComponents/mainInterface/ProblemManager.hpp
  src/coreComponents/mesh/utilities/MeshUtilities.cpp
  src/coreComponents/mesh/utilities/MeshUtilities.hpp
  src/coreComponents/schema/docs/SurfaceGenerator_other.rst
  src/coreComponents/unitTests/fluidFlowTests/testCompFlowUtils.hpp
  src/coreComponents/unitTests/linearAlgebraTests/testDofManagerUtils.hpp
  src/coreComponents/unitTests/meshTests/testMeshGeneration.cpp
  src/coreComponents/unitTests/virtualElementTests/testVirtualElementBase.cpp
  src/coreComponents/unitTests/xmlTests/CMakeLists.txt
  src/coreComponents/unitTests/xmlTests/multifile_input.xml
  src/coreComponents/unitTests/xmlTests/multifile_input/boundary_conditions/constraints.xml
  src/coreComponents/unitTests/xmlTests/multifile_input/boundary_conditions/velocity.xml
  src/coreComponents/unitTests/xmlTests/multifile_input/fieldspec.xml
  src/coreComponents/unitTests/xmlTests/multifile_input/mesh.xml
  src/coreComponents/unitTests/xmlTests/multifile_input/outputs.xml
  src/coreComponents/unitTests/xmlTests/testXML.cpp
  src/coreComponents/unitTests/xmlTests/testXMLFile.cpp
Labels: type: feature, type: cleanup / refactor, flag: ready for review

#1625 Adding a Pecan CPU target alongside the GPU one.
  .travis.yml
  host-configs/TOTAL/pecan-CPU.cmake
  host-configs/TOTAL/pecan-GPU.cmake
Labels: type: build

#1670 Fixed VEM unit test on Lassen
  src/coreComponents/unitTests/virtualElementTests/testConformingVirtualElementOrder1.cpp
Labels: type: bug, type: testing
