Repository GEOS-DEV/GEOS, pull requests merged in 2021-12, with the labels that each got.

#1703 Change github REST call addresses
  .travis.yml
Labels: type: bug, flag: ready for review, type: dev environment

#1705 Reduce logs for packaging targets
  .travis.yml
Labels: flag: ready for review

#1707 Correct Dockerfile indentation.
  src/docs/sphinx/developerGuide/Contributing/Dockerfile-remote-dev.example
Labels: flag: ready for review

#1689 Refactor enthalpy and internal energy for CO2 brine
  .travis.yml
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/PVTFunctions/BrineEnthalpy.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/BrineEnthalpy.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/BrineInternalEnergy.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/BrineInternalEnergy.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/CO2Enthalpy.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/CO2Enthalpy.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/CO2InternalEnergy.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/CO2InternalEnergy.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/PVTFunctionBase.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/PVTFunctionHelpers.hpp
  src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp
Labels: type: cleanup / refactor, flag: ready for review

#1702 Extrinsic mesh data for flow solvers
  src/coreComponents/fieldSpecification/docs/FieldSpecification.rst
  src/coreComponents/mesh/ObjectManagerBase.hpp
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBaseExtrinsicData.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVMKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBaseExtrinsicData.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBaseExtrinsicData.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseProppantBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseProppantBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/proppantTransport/ProppantTransport.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellSolverBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanicsKernel.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEFEMKernel.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsKernel.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsSolverEmbeddedFractures.cpp
  src/coreComponents/schema/docs/CompositionalMultiphaseFVM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseHybridFVM_other.rst
  src/coreComponents/schema/docs/FaceManager_other.rst
  src/coreComponents/schema/docs/ProppantTransport_other.rst
  src/coreComponents/schema/docs/SinglePhaseFVM_other.rst
  src/coreComponents/schema/docs/SinglePhaseHybridFVM_other.rst
  src/coreComponents/schema/docs/SinglePhaseProppantFVM_other.rst
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/fluidFlowTests/testCompMultiphaseFlow.cpp
  src/coreComponents/unitTests/fluidFlowTests/testCompMultiphaseFlowHybrid.cpp
  src/coreComponents/unitTests/wellsTests/testReservoirCompositionalMultiphaseMSWells.cpp
  src/coreComponents/unitTests/wellsTests/testReservoirSinglePhaseMSWells.cpp
  src/docs/sphinx/basicExamples/multiphaseFlow/Example.rst
Labels: type: cleanup / refactor, flag: ready for review

#1700 Move to ubuntu 20.04 and gcc 9 & 10
  .travis.yml
  scripts/travis_build_and_test.sh
Labels: flag: ready for review

#1709 Implemented extrinsic data for multiphase constitutive models
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/ConstitutiveBase.hpp
  src/coreComponents/constitutive/capillaryPressure/CapillaryPressureBase.cpp
  src/coreComponents/constitutive/capillaryPressure/CapillaryPressureBase.hpp
  src/coreComponents/constitutive/capillaryPressure/CapillaryPressureExtrinsicData.hpp
  src/coreComponents/constitutive/fluid/MultiFluidBase.cpp
  src/coreComponents/constitutive/fluid/MultiFluidBase.hpp
  src/coreComponents/constitutive/fluid/MultiFluidExtrinsicData.hpp
  src/coreComponents/constitutive/relativePermeability/RelativePermeabilityBase.cpp
  src/coreComponents/constitutive/relativePermeability/RelativePermeabilityBase.hpp
  src/coreComponents/constitutive/relativePermeability/RelativePermeabilityExtrinsicData.hpp
  src/coreComponents/mesh/ElementRegionManager.hpp
  src/coreComponents/mesh/ExtrinsicMeshData.hpp
  src/coreComponents/mesh/ObjectManagerBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/schema/docs/BlackOilFluid_other.rst
  src/coreComponents/schema/docs/BrooksCoreyBakerRelativePermeability_other.rst
  src/coreComponents/schema/docs/BrooksCoreyCapillaryPressure_other.rst
  src/coreComponents/schema/docs/BrooksCoreyRelativePermeability_other.rst
  src/coreComponents/schema/docs/CO2BrineEzrokhiFluid_other.rst
  src/coreComponents/schema/docs/CO2BrinePhillipsFluid_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseFluid_other.rst
  src/coreComponents/schema/docs/DeadOilFluid_other.rst
  src/coreComponents/schema/docs/TableCapillaryPressure_other.rst
  src/coreComponents/schema/docs/TableRelativePermeability_other.rst
  src/coreComponents/schema/docs/VanGenuchtenBakerRelativePermeability_other.rst
  src/coreComponents/schema/docs/VanGenuchtenCapillaryPressure_other.rst
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/constitutiveTests/testMultiFluid.cpp
Labels: type: cleanup / refactor, flag: ready to be merged

#1711 PVTDriver
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/docs/FluidModels.rst
  src/coreComponents/constitutive/docs/PVTDriver.rst
  src/coreComponents/constitutive/docs/TriaxialDriver.rst
  src/coreComponents/constitutive/docs/TriaxialDriver.svg
  src/coreComponents/constitutive/docs/solid/TriaxialDriver.rst
  src/coreComponents/constitutive/fluid/MultiFluidBase.hpp
  src/coreComponents/constitutive/fluid/PVTDriver.cpp
  src/coreComponents/constitutive/fluid/PVTDriver.hpp
  src/coreComponents/schema/docs/PVTDriver.rst
  src/coreComponents/schema/docs/PVTDriver_other.rst
  src/coreComponents/schema/docs/Tasks.rst
  src/coreComponents/schema/docs/Tasks_other.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/constitutiveTests/CMakeLists.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT.cpp
  src/coreComponents/unitTests/constitutiveTests/testPVT.xml
  src/coreComponents/unitTests/constitutiveTests/testPVT_CO2.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_brine.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/brinePVT.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/carbonDioxideFlash.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/carbonDioxidePVT.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/gasPVT.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/oilPVT.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/referencePVT_CO2.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/referencePVT_H2_CH4.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/referencePVT_brine.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_docExample.xml
  src/coreComponents/unitTests/constitutiveTests/testPVT_hydrogenMixtureA.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_hydrogenMixtureB.txt
  src/docs/sphinx/CompleteXMLSchema.rst
Labels: type: feature, flag: ready for review

#1713 Fixed Pamela parallel properties import (inside GEOSX)
  src/coreComponents/mesh/generators/PAMELAMeshGenerator.cpp
Labels: type: bug, flag: ready to be merged

#1698 Implemented new kernel interface for compositional properties
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBaseKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVMKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVMKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBaseKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWellKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWellKernels.hpp
Labels: type: cleanup / refactor, flag: ready to be merged

#1696 Implemented new kernel interface for flux
  src/coreComponents/codingUtilities/Utilities.hpp
  src/coreComponents/codingUtilities/traits.hpp
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/ConstitutiveBase.hpp
  src/coreComponents/constitutive/permeability/ParallelPlatesPermeability.cpp
  src/coreComponents/constitutive/permeability/PermeabilityBase.cpp
  src/coreComponents/constitutive/permeability/PermeabilityBase.hpp
  src/coreComponents/constitutive/permeability/PermeabilityExtrinsicData.hpp
  src/coreComponents/constitutive/permeability/ProppantPermeability.cpp
  src/coreComponents/constitutive/permeability/ProppantPermeability.hpp
  src/coreComponents/mesh/ElementRegionManager.hpp
  src/coreComponents/mesh/ExtrinsicMeshData.hpp
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVMKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVMKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseProppantBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/StencilAccessors.hpp
  src/coreComponents/physicsSolvers/fluidFlow/proppantTransport/ProppantTransport.cpp
  src/coreComponents/physicsSolvers/multiphysics/ReservoirSolverBase.cpp
  src/coreComponents/schema/docs/CarmanKozenyPermeability_other.rst
  src/coreComponents/schema/docs/ConstantPermeability_other.rst
  src/coreComponents/schema/docs/ParallelPlatesPermeability_other.rst
  src/coreComponents/schema/docs/PermeabilityBase_other.rst
  src/coreComponents/schema/docs/ProppantPermeability_other.rst
  src/coreComponents/schema/docs/StrainDependentPermeability_other.rst
  src/coreComponents/schema/schema.xsd.other
Labels: type: cleanup / refactor, flag: ready to be merged
