Repository GEOS-DEV/GEOS, pull requests merged in 2021-08, with the labels that each got.

#1500 Changed default m_component value to -1 in FieldSpecificationBase to …
  src/coreComponents/fieldSpecification/FieldSpecificationBase.cpp
  src/coreComponents/fieldSpecification/FieldSpecificationBase.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
Labels: flag: requires rebaseline

#1526 Correct some XMLs
  src/coreComponents/physicsSolvers/multiphysics/benchmarks/PoroElastic_wellbore_FIM.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/PoroElastic_wellbore_FIM.xml
Labels: flag: ready to be merged

#1329 Update solid model documentation
  src/coreComponents/constitutive/docs/Constitutive.rst
  src/coreComponents/constitutive/docs/LinearElasticAnisotropic.rst
  src/coreComponents/constitutive/docs/LinearElasticIsotropic.rst
  src/coreComponents/constitutive/docs/PoroLinearElasticAnisotropic.rst
  src/coreComponents/constitutive/docs/PoroLinearElasticIsotropic.rst
  src/coreComponents/constitutive/docs/SolidMechanicsModels.rst
  src/coreComponents/constitutive/docs/TwoInvariantPlasticity.rst
  src/coreComponents/constitutive/docs/solid/DPyield.png
  src/coreComponents/constitutive/docs/solid/Damage.rst
  src/coreComponents/constitutive/docs/solid/DelftEgg.rst
  src/coreComponents/constitutive/docs/solid/DevView.png
  src/coreComponents/constitutive/docs/solid/DruckerPrager.rst
  src/coreComponents/constitutive/docs/solid/DruckerPragerExtended.rst
  src/coreComponents/constitutive/docs/solid/ElasticIsotropic.rst
  src/coreComponents/constitutive/docs/solid/ElasticIsotropicPressureDependent.rst
  src/coreComponents/constitutive/docs/solid/ElasticTransverseIsotropic.rst
  src/coreComponents/constitutive/docs/solid/ModifiedCamClay.rst
  src/coreComponents/constitutive/docs/solid/ModifiedCamClayHardening.png
  src/coreComponents/constitutive/docs/solid/ModifiedCamClayPQ.png
  src/coreComponents/constitutive/docs/solid/MohrCoulomb.png
  src/coreComponents/constitutive/docs/solid/Plasticity.rst
  src/coreComponents/constitutive/docs/solid/Porous.rst
  src/coreComponents/constitutive/docs/solid/SolidModels.rst
  src/coreComponents/constitutive/docs/solid/Theory.rst
  src/coreComponents/constitutive/docs/solid/TriaxialDriver.rst
  src/coreComponents/constitutive/docs/solid/TriaxialDriver.svg
  src/coreComponents/constitutive/docs/solid/Voight.rst
  src/coreComponents/physicsSolvers/PhysicsSolvers.rst
  src/coreComponents/unitTests/constitutiveTests/testTriaxial_sphinxExample.xml
  src/docs/sphinx/buildGuide/ContinuousIntegration.rst
  src/docs/sphinx/buildGuide/UsingDocker.rst
  src/docs/sphinx/developerGuide/Contributing/GitWorkflow.rst
  src/docs/sphinx/tutorials/Index.rst
Labels: flag: ready for review

#1535 Minor doc fixes
  src/docs/sphinx/tutorials/Index.rst
  src/docs/sphinx/tutorials/step01/Tutorial.rst
  src/docs/sphinx/tutorials/step06/Tutorial.rst
  src/docs/sphinx/tutorials/step07/Tutorial.rst
  src/docs/sphinx/tutorials/step08/Tutorial.rst
  src/docs/sphinx/tutorials/step09/Tutorial.rst
  src/docs/sphinx/tutorials/step10/Tutorial.rst
  src/docs/sphinx/tutorials/step10/Verification.png
  src/docs/sphinx/tutorials/step11/Tutorial.rst
  src/docs/sphinx/tutorials/step12/Tutorial.rst
Labels: type: documentation, flag: ready to be merged

#1539 [Docs] coupled solid documentation
  src/coreComponents/constitutive/docs/BiotPorosity.rst
  src/coreComponents/constitutive/docs/ConstantPermeability.rst
  src/coreComponents/constitutive/docs/Constitutive.rst
  src/coreComponents/constitutive/docs/KozenyCarmanPermeability.rst
  src/coreComponents/constitutive/docs/ParallelPlatesPermeability.rst
  src/coreComponents/constitutive/docs/PermeabilityModels.rst
  src/coreComponents/constitutive/docs/PorosityModels.rst
  src/coreComponents/constitutive/docs/PorousSolids.rst
  src/coreComponents/constitutive/docs/PressurePorosity.rst
  src/coreComponents/constitutive/docs/solid/Porous.rst
  src/coreComponents/constitutive/docs/solid/SolidModels.rst
Labels: type: documentation, flag: ready to be merged
