Repository GEOS-DEV/GEOS, pull requests merged in 2021-04, with the labels that each got.

#1380 Fixed compilation warning with clang+hypreGPU on Lassen
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.cpp
Labels: type: build

#1397 Bugfixes for CUDA build (multiphase model kernel wrappers, HypreVector::extract)
  .travis.yml
  src/CMakeLists.txt
  src/cmake/GeosxConfig.cmake
  src/cmake/GeosxOptions.cmake
  src/coreComponents/constitutive/fluid/PVTFunctions/BrineCO2Density.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/BrineCO2Density.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/BrineViscosity.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/BrineViscosity.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/CO2Solubility.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/CO2Solubility.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/FenghourCO2Viscosity.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/FenghourCO2Viscosity.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/FlashModelBase.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/PVTFunctionBase.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/SpanWagnerCO2Density.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/SpanWagnerCO2Density.hpp
  src/coreComponents/functions/TableFunction.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMatrix.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMatrix.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HyprePreconditioner.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreUtils.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreVector.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreVector.hpp
  src/coreComponents/linearAlgebra/interfaces/trilinos/TrilinosPreconditioner.cpp
  src/uncrustify.cfg
Labels: effort: 1 day, flag: ready to be merged, type: bug

#1382 Device Packing Optimization
  src/coreComponents/dataRepository/BufferOpsDevice.cpp
  src/coreComponents/dataRepository/BufferOpsDevice.hpp
  src/coreComponents/unitTests/dataRepositoryTests/testPacking.cpp
Labels: flag: ready to be merged, new, type: optimization

#1395 Update host config to resolve Pangea build issue
  host-configs/TOTAL/pangea2-base.cmake
  host-configs/TOTAL/pangea2-gcc@8.3.0.cmake
Labels: flag: ready to be merged

#1400 Fix silo output issue #1186
  src/coreComponents/fileIO/silo/SiloFile.cpp
Labels: flag: ready to be merged

#1102 Adding a script to test for xml attribute coverage
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/attribute_coverage.py
  src/coreComponents/python/modules/geosx_xml_tools_package/setup.py
Labels: flag: ready to be merged

#1407 Adding timestamp information required by visit to vtk files
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.hpp
Labels: flag: ready for review, type: cleanup / refactor

#1385 Add LaplaceBase class
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/simplePDE/LaplaceBaseH1.cpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceBaseH1.hpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceFEM.cpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceFEM.hpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceVEM.cpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceVEM.hpp
  src/coreComponents/schema/docs/LaplaceFEM.rst
  src/coreComponents/schema/docs/LaplaceVEM.rst
  src/coreComponents/schema/schema.xsd
  src/docs/sphinx/developerGuide/KeyComponents/AddingNewSolver.rst
Labels: flag: ready for review, flag: ready to be merged

#1362 Add pygeosx_tools python package
  examples/pygeosxExamples/hydraulicFractureWithMonitor/heterogeneousInSitu_base.xml
  examples/pygeosxExamples/hydraulicFractureWithMonitor/heterogeneousInSitu_singleFracture.xml
  examples/pygeosxExamples/hydraulicFractureWithMonitor/hydraulicFractureWithMonitor.py
  examples/pygeosxExamples/modifyBoundaryCondition/pkn_example.xml
  examples/pygeosxExamples/modifyBoundaryCondition/run_fracture_problem.py
  examples/pygeosxExamples/parametricSurfaceMapping/parametricMesh.xml
  examples/pygeosxExamples/parametricSurfaceMapping/run_parametric_mesh_problem.py
  examples/pygeosxExamples/sedovWithStressFunction/run_sedov_problem.py
  examples/pygeosxExamples/sedovWithStressFunction/sedov.xml
  src/coreComponents/python/modules/pygeosx_tools_package/pygeosx_tools/__init__.py
  src/coreComponents/python/modules/pygeosx_tools_package/pygeosx_tools/file_io.py
  src/coreComponents/python/modules/pygeosx_tools_package/pygeosx_tools/mesh_interpolation.py
  src/coreComponents/python/modules/pygeosx_tools_package/pygeosx_tools/well_log.py
  src/coreComponents/python/modules/pygeosx_tools_package/pygeosx_tools/wrapper.py
  src/coreComponents/python/modules/pygeosx_tools_package/pygeosx_tools/xml.py
  src/coreComponents/python/modules/pygeosx_tools_package/setup.py
Labels: flag: ready to be merged
