Repository GEOS-DEV/GEOS, pull requests merged in 2021-11, with the labels that each got.

#1674 Fixed division by zero in getHistoryMetadata
  src/coreComponents/dataRepository/HistoryDataSpec.hpp
  src/coreComponents/dataRepository/Wrapper.hpp
  src/coreComponents/unitTests/fileIOTests/testHDFFile.cpp
Labels: type: bug, flag: ready for review

#1659 [Doc] extend sneddon problem to different solvers
  inputFiles/efemFractureMechanics/Sneddon_benchmark.xml
  inputFiles/efemFractureMechanics/Sneddon_benchmark2.xml
  inputFiles/efemFractureMechanics/Sneddon_benchmark3.xml
  inputFiles/efemFractureMechanics/Sneddon_embeddedFrac_base.xml
  inputFiles/efemFractureMechanics/Sneddon_embeddedFrac_benchmark.xml
  inputFiles/efemFractureMechanics/Sneddon_embeddedFrac_smoke.xml
  inputFiles/efemFractureMechanics/Sneddon_smoke.xml
  inputFiles/hydraulicFracturing/Sneddon_hydroFrac_base.xml
  inputFiles/hydraulicFracturing/Sneddon_hydroFrac_benchmark.xml
  inputFiles/hydraulicFracturing/Sneddon_hydroFrac_smoke.xml
  inputFiles/hydraulicFracturing/sneddonConformingMesh_base.xml
  inputFiles/hydraulicFracturing/sneddonConformingMesh_smoke.xml
  inputFiles/lagrangianContactMechanics/Sneddon_contactMechanics_base.xml
  inputFiles/lagrangianContactMechanics/Sneddon_contactMechanics_benchmark.xml
  inputFiles/lagrangianContactMechanics/Sneddon_contactMechanics_smoke.xml
  src/docs/sphinx/advancedExamples/validationStudies/sneddon/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/sneddon/Verification.png
  src/docs/sphinx/advancedExamples/validationStudies/sneddon/cell_centers.hdf5
  src/docs/sphinx/advancedExamples/validationStudies/sneddon/cell_centers2.hdf5
  src/docs/sphinx/advancedExamples/validationStudies/sneddon/displacementJump_contactMechanics.hdf5
  src/docs/sphinx/advancedExamples/validationStudies/sneddon/displacementJump_embeddedFrac.hdf5
  src/docs/sphinx/advancedExamples/validationStudies/sneddon/displacementJump_history.hdf5
  src/docs/sphinx/advancedExamples/validationStudies/sneddon/displacementJump_hydroFrac.hdf5
  src/docs/sphinx/advancedExamples/validationStudies/sneddon/pressure_history.hdf5
Labels: type: documentation, flag: ready to be merged, flag: requires rebaseline

#1668 Linear algebra changes
  src/coreComponents/codingUtilities/StringUtilities.cpp
  src/coreComponents/codingUtilities/StringUtilities.hpp
  src/coreComponents/codingUtilities/UnitTestUtilities.hpp
  src/coreComponents/common/GEOS_RAJA_Interface.hpp
  src/coreComponents/linearAlgebra/CMakeLists.txt
  src/coreComponents/linearAlgebra/interfaces/MatrixBase.hpp
  src/coreComponents/linearAlgebra/interfaces/VectorBase.hpp
  src/coreComponents/linearAlgebra/interfaces/direct/SuperLUDist.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreExport.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreKernels.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreKernels.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMatrix.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMatrix.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HyprePreconditioner.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreSolver.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreUtils.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreUtils.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreVector.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreVector.hpp
  src/coreComponents/linearAlgebra/interfaces/petsc/PetscMatrix.cpp
  src/coreComponents/linearAlgebra/interfaces/petsc/PetscMatrix.hpp
  src/coreComponents/linearAlgebra/interfaces/petsc/PetscPreconditioner.cpp
  src/coreComponents/linearAlgebra/interfaces/petsc/PetscVector.hpp
  src/coreComponents/linearAlgebra/interfaces/trilinos/EpetraMatrix.cpp
  src/coreComponents/linearAlgebra/interfaces/trilinos/EpetraMatrix.hpp
  src/coreComponents/linearAlgebra/interfaces/trilinos/EpetraVector.hpp
  src/coreComponents/linearAlgebra/interfaces/trilinos/TrilinosPreconditioner.cpp
  src/coreComponents/linearAlgebra/solvers/BicgstabSolver.cpp
  src/coreComponents/linearAlgebra/solvers/BicgstabSolver.hpp
  src/coreComponents/linearAlgebra/solvers/BlockPreconditioner.cpp
  src/coreComponents/linearAlgebra/solvers/CgSolver.cpp
  src/coreComponents/linearAlgebra/solvers/CgSolver.hpp
  src/coreComponents/linearAlgebra/solvers/GmresSolver.cpp
  src/coreComponents/linearAlgebra/solvers/GmresSolver.hpp
  src/coreComponents/linearAlgebra/solvers/KrylovSolver.cpp
  src/coreComponents/linearAlgebra/solvers/KrylovSolver.hpp
  src/coreComponents/linearAlgebra/solvers/PreconditionerBlockJacobi.hpp
  src/coreComponents/linearAlgebra/solvers/SeparateComponentPreconditioner.cpp
  src/coreComponents/linearAlgebra/unitTests/testExternalSolvers.cpp
  src/coreComponents/linearAlgebra/unitTests/testKrylovSolvers.cpp
  src/coreComponents/linearAlgebra/unitTests/testLinearAlgebraUtils.hpp
  src/coreComponents/linearAlgebra/unitTests/testVectors.cpp
  src/coreComponents/linearAlgebra/utilities/BlockVectorView.hpp
  src/coreComponents/linearAlgebra/utilities/LAIHelperFunctions.hpp
  src/coreComponents/linearAlgebra/utilities/LinearSolverParameters.hpp
  src/coreComponents/linearAlgebra/utilities/TransposeOperator.hpp
  src/coreComponents/mainInterface/initialization.cpp
  src/coreComponents/physicsSolvers/SolverBase.cpp
  src/coreComponents/physicsSolvers/multiphysics/LagrangianContactSolver.cpp
  src/coreComponents/schema/docs/LinearSolverParameters.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/unitTests/linearAlgebraTests/testDofManager.cpp
  src/uncrustify.cfg
Labels: type: cleanup / refactor, flag: ready for review

#1640 Added hydrostatic equilibrium documentation
  src/coreComponents/constitutive/docs/VanGenuchtenCapillaryPressure.rst
  src/coreComponents/fieldSpecification/docs/AquiferBoundaryCondition.rst
  src/coreComponents/fieldSpecification/docs/EquilibriumInitialCondition.rst
  src/coreComponents/fieldSpecification/docs/FieldSpecification.rst
Labels: flag: ready to be merged

#1672 Implemented new interface for accumulation and volume balance kernels
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBaseKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBaseKernels.hpp
  src/coreComponents/unitTests/fluidFlowTests/testCompMultiphaseFlow.cpp
Labels: type: cleanup / refactor, flag: ready for review

#1691 Check that PR is assigned
  .travis.yml
Labels: type: build, flag: ready to be merged

#1695 Fix #1694
  src/coreComponents/linearAlgebra/interfaces/petsc/PetscVector.cpp
Labels: type: bug, flag: ready to be merged, flag: ready for review
