Repository GEOS-DEV/GEOS, pull requests merged in 2021-06, with the labels that each got.

#1459 Consistify temperature units for CO2-brine input
  src/coreComponents/constitutive/docs/CO2Brine.rst
  src/coreComponents/constitutive/fluid/PVTFunctions/PVTFunctionHelpers.hpp
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/compositionalMultiphaseFlow/co2flash.txt
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/compositionalMultiphaseFlow/pvtgas.txt
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/compositionalMultiphaseFlow/pvtliquid.txt
  src/coreComponents/physicsSolvers/fluidFlow/wells/integratedTests/compositionalMultiphaseWell/co2flash.txt
  src/coreComponents/physicsSolvers/fluidFlow/wells/integratedTests/compositionalMultiphaseWell/pvtgas.txt
  src/coreComponents/physicsSolvers/fluidFlow/wells/integratedTests/compositionalMultiphaseWell/pvtliquid.txt
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/pvt_tables/co2flash.txt
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/pvt_tables/pvtgas.txt
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/pvt_tables/pvtliquid.txt
  src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp
  src/coreComponents/unitTests/constitutiveTests/testMultiFluid.cpp
Labels: flag: ready for review, type: cleanup / refactor

#1460 Fixed the bug related to underscores in PAMELA region/surface names
  src/coreComponents/mesh/generators/PAMELAMeshGenerator.hpp
Labels: flag: ready to be merged, type: cleanup / refactor

#1401 Mgr cleanup + Poromechanics solvers cleanup
  src/conf.py
  src/coreComponents/linearAlgebra/CMakeLists.txt
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGR.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGR.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGRStrategies.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HyprePreconditioner.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreVector.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoir.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/HybridSinglePhasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/LagrangianContactMechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/MultiphasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhasePoromechanics.hpp
  src/coreComponents/linearAlgebra/utilities/LinearSolverParameters.hpp
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanicsKernel.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanicsSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanicsSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/PoroelasticSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsKernel.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsSolverEmbeddedFractures.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsSolverEmbeddedFractures.hpp
  src/coreComponents/physicsSolvers/multiphysics/benchmarks/PoroElastic_wellbore_FIM.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/FlowProppantBedTransport_2d.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/PoroElastic_Mandel_FIM.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/PoroElastic_Terzaghi_FIM.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/PoroElastic_deadoil_3ph_baker_2d.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/PoroElastic_embFractures.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/PoroElastic_wellbore_FIM.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/poroElastic_Mandel.xml
  src/coreComponents/physicsSolvers/multiphysics/integratedTests/poroElastic_Terzaghi.xml
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsPoroElasticKernel.hpp
  src/coreComponents/schema/docs/MultiphasePoroelastic.rst
  src/coreComponents/schema/docs/MultiphasePoromechanics.rst
  src/coreComponents/schema/docs/MultiphasePoromechanics_other.rst
  src/coreComponents/schema/docs/Poroelastic.rst
  src/coreComponents/schema/docs/PoroelasticEmbeddedFractures.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanics.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanicsEmbeddedFractures.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanicsEmbeddedFractures_other.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanics_other.rst
  src/coreComponents/schema/docs/SolidMechanicsLagrangianSSLE.rst
  src/coreComponents/schema/docs/SolidMechanics_LagrangianFEM.rst
  src/coreComponents/schema/docs/Solvers.rst
  src/coreComponents/schema/docs/Solvers_other.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/docs/doxygen/Doxyfile.in
  src/docs/sphinx/CompleteXMLSchema.rst
  src/docs/sphinx/tutorials/step08/Tutorial.rst
  src/docs/sphinx/tutorials/step08/cell_centers.hdf5
  src/docs/sphinx/tutorials/step08/pressure_history.hdf5
Labels: flag: ready to be merged, flag: requires rebaseline, type: cleanup / refactor

#1454 Fix Wedge node ordering
  src/coreComponents/fileIO/silo/SiloFile.cpp
  src/coreComponents/mesh/ElementSubRegionBase.cpp
  src/coreComponents/mesh/ElementSubRegionBase.hpp
  src/coreComponents/mesh/generators/PAMELAMeshGenerator.cpp
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_hex_gravity.xml
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_pyramid_gravity.xml
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_tetra_2_regions.xml
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_tetra_2_regions_half_flow.xml
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_tetra_gravity.xml
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/3D_10x10x10_compressible_pamela_wedge_gravity.xml
  src/coreComponents/physicsSolvers/fluidFlow/integratedTests/singlePhaseFlow/pamela_test/cube_10x10x10_wedge.msh
Labels: flag: ready to be merged

#1473 Fix bugs and add unit tests for ComponentMask
  src/coreComponents/linearAlgebra/unitTests/CMakeLists.txt
  src/coreComponents/linearAlgebra/unitTests/testBlasLapack.cpp
  src/coreComponents/linearAlgebra/unitTests/testComponentMask.cpp
  src/coreComponents/linearAlgebra/utilities/ComponentMask.hpp
  src/coreComponents/schema/docs/InternalWell.rst
  src/coreComponents/schema/schema.xsd
Labels: effort: 1 day, flag: ready for review, type: bug
