Repository GEOS-DEV/GEOS, pull requests merged in 2022-12, with the labels that each got.

#2166 Fix vtk labels for stress.
  src/coreComponents/constitutive/solid/SolidBase.cpp
Labels: flag: ready to be merged

#2183 Update the style of single phase face BC
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVMKernels.hpp
Labels: type: cleanup / refactor, flag: ready to be merged

#2155 Build travis-ci using ninja
  .travis.yml
  scripts/config-build.py
  scripts/travis_build_and_test.sh
Labels: flag: requires updated TPL(s)

#2206 Fix non conformal mesh drawing in doc
  src/coreComponents/fieldSpecification/docs/AquiferBoundaryCondition.rst
  src/coreComponents/mesh/docs/Mesh.rst
  src/coreComponents/mesh/docs/mesh.svg
Labels: type: documentation

#2211 Separate denseLinearAlgebra in its own component.
  src/coreComponents/CMakeLists.txt
  src/coreComponents/denseLinearAlgebra/CMakeLists.txt
  src/coreComponents/denseLinearAlgebra/common/layouts.hpp
  src/coreComponents/denseLinearAlgebra/interfaces/blaslapack/BlasLapackFunctions.h
  src/coreComponents/denseLinearAlgebra/interfaces/blaslapack/BlasLapackLA.cpp
  src/coreComponents/denseLinearAlgebra/interfaces/blaslapack/BlasLapackLA.hpp
  src/coreComponents/denseLinearAlgebra/unitTests/CMakeLists.txt
  src/coreComponents/denseLinearAlgebra/unitTests/testBlasLapack.cpp
  src/coreComponents/linearAlgebra/CMakeLists.txt
  src/coreComponents/linearAlgebra/common/common.hpp
  src/coreComponents/linearAlgebra/solvers/GmresSolver.cpp
  src/coreComponents/linearAlgebra/solvers/PreconditionerBlockJacobi.hpp
  src/coreComponents/linearAlgebra/unitTests/CMakeLists.txt
  src/coreComponents/linearAlgebra/utilities/Arnoldi.hpp
  src/coreComponents/linearAlgebra/utilities/BlockOperatorView.hpp
  src/coreComponents/linearAlgebra/utilities/BlockOperatorWrapper.hpp
  src/coreComponents/linearAlgebra/utilities/BlockVectorView.hpp
  src/docs/doxygen/GeosxConfig.hpp
Labels: flag: ready to be merged

#2143 Create a relpermDriver to test 3-phase interpolators and tables validity
  inputFiles/relpermDriver/drainagePhaseVolFraction_gas.txt
  inputFiles/relpermDriver/drainagePhaseVolFraction_water.txt
  inputFiles/relpermDriver/drainageRelPerm_gas.txt
  inputFiles/relpermDriver/drainageRelPerm_water.txt
  inputFiles/relpermDriver/imbibitionPhaseVolFraction_gas.txt
  inputFiles/relpermDriver/imbibitionPhaseVolFraction_water.txt
  inputFiles/relpermDriver/imbibitionRelPerm_gas.txt
  inputFiles/relpermDriver/imbibitionRelPerm_water.txt
  inputFiles/relpermDriver/testRelpermDriverBCBaker.xml
  inputFiles/relpermDriver/testRelpermDriverTableHyst2ph.xml
  scripts/postProcessing/plotRelpermDriver.py
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/PVTDriver.cpp
  src/coreComponents/constitutive/relativePermeability/BrooksCoreyBakerRelativePermeability.hpp
  src/coreComponents/constitutive/relativePermeability/BrooksCoreyRelativePermeability.hpp
  src/coreComponents/constitutive/relativePermeability/RelativePermeabilityBase.cpp
  src/coreComponents/constitutive/relativePermeability/RelativePermeabilityBase.hpp
  src/coreComponents/constitutive/relativePermeability/RelativePermeabilitySelector.hpp
  src/coreComponents/constitutive/relativePermeability/RelpermDriver.cpp
  src/coreComponents/constitutive/relativePermeability/RelpermDriver.hpp
  src/coreComponents/constitutive/relativePermeability/RelpermDriverBrooksCoreyBakerRunTest.cpp
  src/coreComponents/constitutive/relativePermeability/RelpermDriverBrooksCoreyRunTest.cpp
  src/coreComponents/constitutive/relativePermeability/RelpermDriverRunTest.hpp
  src/coreComponents/constitutive/relativePermeability/RelpermDriverTableRelativeHysteresisRunTest.cpp
  src/coreComponents/constitutive/relativePermeability/RelpermDriverTableRelativeRunTest.cpp
  src/coreComponents/constitutive/relativePermeability/RelpermDriverVanGenuchtenBakerRunTest.cpp
  src/coreComponents/constitutive/relativePermeability/TableRelativePermeability.hpp
  src/coreComponents/constitutive/relativePermeability/TableRelativePermeabilityHysteresis.cpp
  src/coreComponents/constitutive/relativePermeability/TableRelativePermeabilityHysteresis.hpp
  src/coreComponents/constitutive/relativePermeability/VanGenuchtenBakerRelativePermeability.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/unitTests/constitutiveTests/constitutiveTestHelpers.hpp
Labels: type: feature, flag: ready to be merged

#2218 fix abs namespace
  src/coreComponents/finiteElement/elementFormulations/Qk_Hexahedron_Lagrange_GaussLobatto.hpp
Labels: type: bug, flag: ready to be merged
