Repository GEOS-DEV/GEOS, pull requests merged in 2022-02, with the labels that each got.

#1741 buildrootdir/installrootdir options in config-build.py
  scripts/config-build.py
  src/docs/sphinx/buildGuide/BuildProcess.rst
Labels: flag: ready to be merged

#1754 Bugfix/castelletto1/issue 1708
  .travis.yml
  src/coreComponents/linearAlgebra/unitTests/testLinearAlgebraUtils.hpp
Labels: type: bug, type: testing, flag: ready to be merged

#1760 Unified mass/molar conversions in fluid models
  src/coreComponents/constitutive/fluid/BlackOilFluid.hpp
  src/coreComponents/constitutive/fluid/CompositionalMultiphaseFluid.hpp
  src/coreComponents/constitutive/fluid/DeadOilFluid.hpp
  src/coreComponents/constitutive/fluid/MultiFluidBase.hpp
  src/coreComponents/constitutive/fluid/MultiPhaseMultiComponentFluid.cpp
  src/coreComponents/constitutive/fluid/MultiPhaseMultiComponentFluid.hpp
Labels: type: cleanup / refactor, flag: ready to be merged

#1765 Delay initialization of HistoryOuput
  src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp
  src/coreComponents/fileIO/Outputs/TimeHistoryOutput.hpp
Labels: flag: ready to be merged

#1690 VEM support in FEM kernel interface
  inputFiles/simplePDE/10x10x10Hex_LaplaceFEM_smoke.xml
  inputFiles/simplePDE/10x10x10Hex_LaplaceVEM_smoke.xml
  inputFiles/simplePDE/10x10x10_LaplaceFEM.xml
  inputFiles/simplePDE/10x5x15Wedges_LaplaceVEM.xml
  inputFiles/simplePDE/10x5x15Wedges_LaplaceVEM_smoke.xml
  inputFiles/simplePDE/15x5x10Tets_LaplaceVEM.xml
  inputFiles/simplePDE/15x5x10Tets_LaplaceVEM_smoke.xml
  inputFiles/simplePDE/50x10x5Hex_LaplaceFEM_smoke.xml
  inputFiles/simplePDE/50x10x5_LaplaceFEM.xml
  inputFiles/simplePDE/Laplace_base.xml
  src/coreComponents/CMakeLists.txt
  src/coreComponents/discretizationMethods/CMakeLists.txt
  src/coreComponents/finiteElement/CMakeLists.txt
  src/coreComponents/finiteElement/FiniteElementDiscretization.cpp
  src/coreComponents/finiteElement/FiniteElementDiscretization.hpp
  src/coreComponents/finiteElement/FiniteElementDispatch.hpp
  src/coreComponents/finiteElement/elementFormulations/ConformingVirtualElementOrder1.hpp
  src/coreComponents/finiteElement/elementFormulations/ConformingVirtualElementOrder1_impl.hpp
  src/coreComponents/finiteElement/elementFormulations/FiniteElementBase.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_Hexahedron_Lagrange1_GaussLegendre2.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_Pyramid_Lagrange1_Gauss5.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_QuadrilateralFace_Lagrange1_GaussLegendre2.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_Tetrahedron_Lagrange1_Gauss1.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_TriangleFace_Lagrange1_Gauss1.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_Wedge_Lagrange1_Gauss6.hpp
  src/coreComponents/finiteElement/kernelInterface/ImplicitKernelBase.hpp
  src/coreComponents/finiteElement/kernelInterface/KernelBase.hpp
  src/coreComponents/finiteElement/unitTests/testFiniteElementBase.cpp
  src/coreComponents/mainInterface/ProblemManager.cpp
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanicsKernel.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEFEMKernel.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsKernel.hpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceFEMKernels.hpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceVEM.cpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceVEM.hpp
  src/coreComponents/physicsSolvers/simplePDE/PhaseFieldDamageFEMKernels.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsEFEMKernels.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsSmallStrainExplicitNewmarkKernel.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsSmallStrainImplicitNewmarkKernel.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsSmallStrainQuasiStaticKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEMKernel.hpp
  src/coreComponents/schema/docs/FiniteElementSpace.rst
  src/coreComponents/schema/docs/LaplaceVEM.rst
  src/coreComponents/schema/docs/LaplaceVEM_other.rst
  src/coreComponents/schema/docs/Solvers.rst
  src/coreComponents/schema/docs/Solvers_other.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/unitTests/virtualElementTests/testConformingVirtualElementOrder1.cpp
  src/coreComponents/virtualElement/CMakeLists.txt
  src/coreComponents/virtualElement/ConformingVirtualElementOrder1.hpp
  src/docs/sphinx/CompleteXMLSchema.rst
Labels: flag: ready to be merged, flag: requires rebaseline

#1787 Fix a couple minor issues with XML preprocessor
  examples/advanced_xml_features/included/included_a.xml
  examples/advanced_xml_features/parameters_example.xml
  examples/advanced_xml_features/symbolic_math_example.xml
  scripts/setupPythonEnvironment.bash
  src/coreComponents/functions/SymbolicFunction.cpp
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/xml_formatter.py
Labels: flag: ready to be merged, flag: ready for review
