Repository GEOS-DEV/GEOS, pull requests merged in 2022-09, with the labels that each got.

#2027 add multiBody/multiLevel support to VTK output system
  inputFiles/multipleMeshBodies/testMultipleBodies.xml
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.hpp
  src/coreComponents/fileIO/vtk/VTKVTMWriter.cpp
  src/coreComponents/fileIO/vtk/VTKVTMWriter.hpp
  src/coreComponents/mesh/generators/InternalMeshGenerator.cpp
Labels: flag: ready to be merged

#2037 Rollback Azure Pipelines Jobs To Travis
  .travis.yml
  azure-pipelines.yml
  scripts/build_test_helper.sh
Labels: type: testing, flag: ready to be merged

#2048 split fracture stencil and trigger fracture stencil for imported faults
  src/coreComponents/finiteVolume/FluxApproximationBase.cpp
  src/coreComponents/finiteVolume/FluxApproximationBase.hpp
  src/coreComponents/finiteVolume/TwoPointFluxApproximation.cpp
  src/coreComponents/finiteVolume/TwoPointFluxApproximation.hpp
  src/coreComponents/mesh/CMakeLists.txt
Labels: type: cleanup / refactor

#2049 Remove script and duplicated variables.
  .travis.yml
  scripts/ci_build_and_test.sh
  scripts/travis_build_and_test.sh
Labels: type: build system

#2050 Skipped the shallow mesh copies in the vtk output
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
Labels: type: cleanup / refactor, flag: ready to be merged

#2053 travis stage for draft PR
  .travis.yml
Labels: type: build system

#2055 Fix submodules quick start doc.
  src/docs/sphinx/QuickStart.rst
Labels: type: documentation

#1989 Improve performance of ghost map unpacking
  src/coreComponents/dataRepository/BufferOps_inline.hpp
  src/coreComponents/mesh/BufferOps.cpp
  src/coreComponents/mesh/EdgeManager.cpp
  src/coreComponents/mesh/EdgeManager.hpp
  src/coreComponents/mesh/FaceManager.cpp
  src/coreComponents/mesh/FaceManager.hpp
  src/coreComponents/mesh/NodeManager.cpp
  src/coreComponents/mesh/ObjectManagerBase.cpp
  src/coreComponents/mesh/ObjectManagerBase.hpp
  src/coreComponents/mesh/generators/VTKMeshGenerator.cpp
  src/coreComponents/mesh/mpiCommunications/CommunicationTools.cpp
  src/coreComponents/mesh/mpiCommunications/CommunicationTools.hpp
  src/coreComponents/physicsSolvers/surfaceGeneration/SurfaceGenerator.cpp
Labels: flag: ready to be merged, type: optimization, flag: ready for review

#2058 Force GEOSX organisation in submodules
  .gitmodules
Labels: type: build system

#2061 Fixed a crash in the statistics on GPU
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseBaseKernels.hpp
Labels: type: bug, flag: ready for review

#2067 Add openmp and/or hdf5 to the dependencyList when needed with slurm MPI
  src/coreComponents/unitTests/constitutiveTests/CMakeLists.txt
  src/coreComponents/unitTests/dataRepositoryTests/CMakeLists.txt
  src/coreComponents/unitTests/fieldSpecificationTests/CMakeLists.txt
  src/coreComponents/unitTests/fileIOTests/CMakeLists.txt
  src/coreComponents/unitTests/finiteVolumeTests/CMakeLists.txt
  src/coreComponents/unitTests/fluidFlowTests/CMakeLists.txt
  src/coreComponents/unitTests/functionsTests/CMakeLists.txt
  src/coreComponents/unitTests/linearAlgebraTests/CMakeLists.txt
  src/coreComponents/unitTests/meshTests/CMakeLists.txt
  src/coreComponents/unitTests/virtualElementTests/CMakeLists.txt
  src/coreComponents/unitTests/wavePropagationTests/CMakeLists.txt
  src/coreComponents/unitTests/wellsTests/CMakeLists.txt
  src/coreComponents/unitTests/xmlTests/CMakeLists.txt
Labels: flag: ready to be merged, flag: ready for review

#1991 Add python tools documentation to sphinx
  .gitignore
  host-configs/LLNL/quartz-base.cmake
  scripts/setupPythonEnvironment.bash
  src/conf.py
  src/coreComponents/fileIO/doc/InputXMLFiles.rst
  src/coreComponents/mesh/docs/Mesh.rst
  src/coreComponents/python/modules/geosx_mesh_tools_package/geosx_mesh_tools/abaqus_converter.py
  src/coreComponents/python/modules/geosx_mesh_tools_package/geosx_mesh_tools/main.py
  src/coreComponents/python/modules/geosx_mesh_tools_package/geosx_mesh_tools/py.typed
  src/coreComponents/python/modules/geosx_mesh_tools_package/pyproject.toml
  src/coreComponents/python/modules/geosx_mesh_tools_package/setup.cfg
  src/coreComponents/python/modules/geosx_mesh_tools_package/setup.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/__init__.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/attribute_coverage.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/command_line_parsers.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/main.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/py.typed
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/regex_tools.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/table_generator.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/unit_manager.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/xml_formatter.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/xml_processor.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/xml_redundancy_check.py
  src/coreComponents/python/modules/geosx_xml_tools_package/pyproject.toml
  src/coreComponents/python/modules/geosx_xml_tools_package/setup.cfg
  src/coreComponents/python/modules/geosx_xml_tools_package/setup.py
  src/coreComponents/python/modules/hdf5_wrapper_package/hdf5_wrapper/py.typed
  src/coreComponents/python/modules/hdf5_wrapper_package/hdf5_wrapper/use_example.py
  src/coreComponents/python/modules/hdf5_wrapper_package/hdf5_wrapper/wrapper.py
  src/coreComponents/python/modules/hdf5_wrapper_package/hdf5_wrapper/wrapper_tests.py
  src/coreComponents/python/modules/hdf5_wrapper_package/pyproject.toml
  src/coreComponents/python/modules/hdf5_wrapper_package/setup.cfg
  src/coreComponents/python/modules/hdf5_wrapper_package/setup.py
  src/coreComponents/python/modules/pygeosx_tools_package/pygeosx_tools/file_io.py
  src/coreComponents/python/modules/pygeosx_tools_package/pygeosx_tools/mesh_interpolation.py
  src/coreComponents/python/modules/pygeosx_tools_package/pygeosx_tools/py.typed
  src/coreComponents/python/modules/pygeosx_tools_package/pygeosx_tools/wrapper.py
  src/coreComponents/python/modules/pygeosx_tools_package/pyproject.toml
  src/coreComponents/python/modules/pygeosx_tools_package/setup.cfg
  src/coreComponents/python/modules/pygeosx_tools_package/setup.py
  src/coreComponents/python/modules/timehistory_package/pyproject.toml
  src/coreComponents/python/modules/timehistory_package/setup.cfg
  src/coreComponents/python/modules/timehistory_package/setup.py
  src/coreComponents/python/modules/timehistory_package/timehistory/__init__.py
  src/coreComponents/python/modules/timehistory_package/timehistory/plot_time_history.py
  src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/faultVerification/faultVerificationFigure.py
  src/docs/sphinx/advancedExamples/validationStudies/hydraulicFracture/pennyFracToughnessDominated/pennyFracToughnessDominatedFigure.py
  src/docs/sphinx/advancedExamples/validationStudies/hydraulicFracture/pennyFracViscosityDominated/pennyFracViscosityDominatedFigure.py
  src/docs/sphinx/advancedExamples/validationStudies/hydraulicFracture/pknFracViscosityDominated/pknViscosityDominatedFigure.py
  src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/deviatedPoroElasticWellbore/deviatedPoroElasticWellboreExample2Figure.py
  src/docs/sphinx/pythonTools/geosx_mesh_tools.rst
  src/docs/sphinx/pythonTools/geosx_xml_tools.rst
  src/docs/sphinx/pythonTools/hdf5_wrapper.rst
  src/docs/sphinx/pythonTools/pygeosx_tools.rst
  src/docs/sphinx/pythonTools/pythonAPI.rst
  src/docs/sphinx/pythonTools/timehistory.rst
  src/docs/sphinx/requirements.txt
  src/index.rst
  src/pygeosx/pygeosx_documentation.rst
Labels: type: documentation, flag: ready to be merged

#1980 Add support for NVTX in cuda traces using existing instrumentation
  host-configs/TOTAL/pangea3-gcc8.4.1-openmpi-4.1.2.cmake
  src/cmake/GeosxConfig.cmake
  src/cmake/thirdparty/SetupGeosxThirdParty.cmake
  src/coreComponents/CMakeLists.txt
  src/coreComponents/common/GeosxConfig.hpp.in
  src/coreComponents/common/TimingMacros.hpp
  src/coreComponents/constitutive/unitTests/CMakeLists.txt
  src/coreComponents/dataRepository/unitTests/CMakeLists.txt
  src/coreComponents/fileIO/CMakeLists.txt
  src/coreComponents/finiteElement/CMakeLists.txt
  src/coreComponents/finiteElement/unitTests/CMakeLists.txt
  src/coreComponents/finiteVolume/CMakeLists.txt
  src/coreComponents/functions/CMakeLists.txt
  src/coreComponents/linearAlgebra/CMakeLists.txt
  src/coreComponents/mainInterface/CMakeLists.txt
  src/coreComponents/mesh/CMakeLists.txt
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/schema/CMakeLists.txt
  src/coreComponents/unitTests/constitutiveTests/CMakeLists.txt
  src/coreComponents/unitTests/dataRepositoryTests/CMakeLists.txt
  src/coreComponents/unitTests/fieldSpecificationTests/CMakeLists.txt
  src/coreComponents/unitTests/fileIOTests/CMakeLists.txt
  src/coreComponents/unitTests/finiteVolumeTests/CMakeLists.txt
  src/coreComponents/unitTests/fluidFlowTests/CMakeLists.txt
  src/coreComponents/unitTests/functionsTests/CMakeLists.txt
  src/coreComponents/unitTests/linearAlgebraTests/CMakeLists.txt
  src/coreComponents/unitTests/meshTests/CMakeLists.txt
  src/coreComponents/unitTests/virtualElementTests/CMakeLists.txt
  src/coreComponents/unitTests/wavePropagationTests/CMakeLists.txt
  src/coreComponents/unitTests/wellsTests/CMakeLists.txt
  src/coreComponents/unitTests/xmlTests/CMakeLists.txt
  src/docs/doxygen/GeosxConfig.hpp
  src/docs/sphinx/buildGuide/BuildProcess.rst
  src/docs/sphinx/developerGuide/Contributing/Caliper.rst
Labels: flag: ready to be merged, flag: ready for review

#2081 Renable parallelDevicePolicy in SEM
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.hpp
Labels: type: bug, flag: ready to be merged

#2088 Implemented source flux boundary condition in OBL
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/ReactiveCompositionalMultiphaseOBL.cpp
  src/coreComponents/physicsSolvers/fluidFlow/ReactiveCompositionalMultiphaseOBL.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
Labels: type: feature, flag: ready to be merged
