Repository GEOS-DEV/GEOS, pull requests merged in 2022-05, with the labels that each got.

#1895 Fix VTK element output
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
Labels: type: bug, priority: critical, flag: ready to be merged, flag: ready for review

#1896 Bugfix/castelletto1/pamela wedge import
  inputFiles/singlePhaseFlow/pamela_test/cube_10x10x10_pyramid.msh
  src/coreComponents/mesh/CellElementSubRegion.cpp
  src/coreComponents/mesh/generators/PAMELAMeshGenerator.cpp
Labels: type: bug, flag: ready to be merged

#1808 add reinit method to waveSolverBase
  src/coreComponents/physicsSolvers/wavePropagation/WaveSolverBase.cpp
  src/coreComponents/physicsSolvers/wavePropagation/WaveSolverBase.hpp
Labels: flag: ready to be merged, type: pygeosx

#1899 Fix misplaced initialization for boundary tags
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.cpp
Labels: type: bug, flag: ready to be merged

#1894 Add a tutorial example for the triaxialDriver
  inputFiles/triaxialDriver/tables/axialStrain.geos
  inputFiles/triaxialDriver/tables/radialStress.geos
  inputFiles/triaxialDriver/tables/time.geos
  inputFiles/triaxialDriver/triaxialDriver_ExtendedDruckerPrager.xml
  src/coreComponents/constitutive/docs/solid/TriaxialDriver.rst
  src/docs/sphinx/basicExamples/Index.rst
  src/docs/sphinx/basicExamples/triaxialDriver/Example.rst
  src/docs/sphinx/basicExamples/triaxialDriver/simulationResults.txt
  src/docs/sphinx/basicExamples/triaxialDriver/triaxialDriverFigure.py
Labels: type: documentation, flag: ready to be merged, flag: ready for review

#1897 Using mermaid for class diagrams
  .readthedocs.yml
  src/conf.py
  src/coreComponents/mesh/docs/MeshObjectInstantiationHierarchy.mmd
  src/coreComponents/mesh/docs/MeshObjectInstantiationHierarchy.png
  src/coreComponents/mesh/docs/meshDeveloperGuide.rst
  src/docs/sphinx/requirements.txt
Labels: type: documentation

#1916 Update Publications.rst
  src/docs/sphinx/Publications.rst
Labels: type: documentation

#1873 Little time history reorganization
  src/coreComponents/dataRepository/wrapperHelpers.hpp
  src/coreComponents/fileIO/CMakeLists.txt
  src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp
  src/coreComponents/fileIO/Outputs/TimeHistoryOutput.hpp
  src/coreComponents/fileIO/python/PyHistoryCollection.cpp
  src/coreComponents/fileIO/timeHistory/BufferedHistoryIO.hpp
  src/coreComponents/fileIO/timeHistory/HDFFile.cpp
  src/coreComponents/fileIO/timeHistory/HDFFile.hpp
  src/coreComponents/fileIO/timeHistory/HDFHistoryIO.cpp
  src/coreComponents/fileIO/timeHistory/HDFHistoryIO.hpp
  src/coreComponents/fileIO/timeHistory/HistoryCollection.hpp
  src/coreComponents/fileIO/timeHistory/HistoryCollectionBase.cpp
  src/coreComponents/fileIO/timeHistory/HistoryCollectionBase.hpp
  src/coreComponents/fileIO/timeHistory/PackCollection.cpp
  src/coreComponents/fileIO/timeHistory/PackCollection.hpp
  src/coreComponents/fileIO/timeHistory/TimeHistHDF.hpp
  src/coreComponents/fileIO/timeHistory/TimeHistoryCollection.hpp
  src/coreComponents/mesh/ObjectManagerBase.cpp
  src/coreComponents/mesh/ObjectManagerBase.hpp
  src/coreComponents/unitTests/fileIOTests/testHDFFile.cpp
  src/coreComponents/unitTests/fileIOTests/testHDFParallelFile.cpp
Labels: type: bug, type: cleanup / refactor

#1918 Fixed parallel field import in VTKMeshGenerator
  src/coreComponents/mesh/generators/VTKMeshGenerator.cpp
Labels: type: bug, flag: ready to be merged

#1781 Attempting to make the xml processing mpi aware
  examples/pygeosxExamples/hydraulicFractureWithMonitor/hydraulicFractureWithMonitor.py
  examples/pygeosxExamples/sedovWithStressFunction/run_sedov_problem.py
  scripts/automatic_xml_preprocess.sh
  scripts/pygeosx_preprocess.py
  scripts/setupPythonEnvironment.bash
  src/coreComponents/python/.gitignore
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/__main__.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/main.py
  src/coreComponents/python/modules/geosx_xml_tools_package/setup.py
  src/coreComponents/python/modules/pygeosx_tools_package/pygeosx_tools/xml.py
Labels: flag: ready to be merged, type: pygeosx
