Repository GEOS-DEV/GEOS, pull requests merged in 2022-04, with the labels that each got.

#1864 Better warning message when wrapper is not here.
  src/coreComponents/mesh/ObjectManagerBase.cpp
Labels: type: cleanup / refactor

#1857 Increased readibility for hypre interface
  src/coreComponents/codingUtilities/Utilities.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGR.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGR.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HyprePreconditioner.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreSolver.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreUtils.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreUtils.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/HybridSinglePhasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/Hydrofracture.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/LagrangianContactMechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/MultiphasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhaseHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhaseReservoirFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhaseReservoirHybridFVM.hpp
Labels: type: cleanup / refactor, flag: ready to be merged

#1885 Renaming prism to wedge
  src/coreComponents/fileIO/Outputs/BlueprintOutput.cpp
  src/coreComponents/fileIO/silo/SiloFile.cpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
  src/coreComponents/finiteElement/FiniteElementDiscretization.cpp
  src/coreComponents/finiteElement/FiniteElementDispatch.hpp
  src/coreComponents/mesh/CellElementSubRegion.cpp
  src/coreComponents/mesh/ElementType.hpp
  src/coreComponents/mesh/generators/CellBlock.cpp
  src/coreComponents/mesh/generators/CellBlockUtilities.cpp
  src/coreComponents/mesh/generators/InternalMeshGenerator.cpp
  src/coreComponents/mesh/generators/InternalMeshGenerator.hpp
  src/coreComponents/mesh/generators/PAMELAMeshGenerator.cpp
  src/coreComponents/mesh/generators/VTKMeshGenerator.cpp
  src/coreComponents/schema/docs/InternalMesh.rst
  src/coreComponents/schema/docs/InternalWellbore.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/unitTests/meshTests/testMeshEnums.cpp
  src/docs/sphinx/basicExamples/multiphaseFlowWithWells/Example.rst
  src/docs/sphinx/tutorials/step01/Tutorial.rst
  src/docs/sphinx/tutorials/step02/Tutorial.rst
Labels: type: cleanup / refactor, flag: ready for review
