Repository GEOS-DEV/GEOS, pull requests merged in 2022-08, with the labels that each got.

#1999 Restore Pangea2 deployment
  .travis.yml
  scripts/ci_build_and_test.sh
Labels: priority: critical, type: build, flag: ready to be merged, type: dev environment

#1990 Bugfix/castelletto1/tutorial3
  inputFiles/singlePhaseFlow/FieldCaseTutorial3_base.xml
  src/docs/sphinx/tutorials/step03/Tutorial.rst
Labels: type: bug, type: documentation, flag: ready to be merged

#2008 Use brew's tap to install precise version of open-mpi
  .travis.yml
Labels: priority: critical, type: build

#1956 Add VTK Outputs wrappers for PyGEOSX
  src/coreComponents/fileIO/CMakeLists.txt
  src/coreComponents/fileIO/Outputs/VTKOutput.cpp
  src/coreComponents/fileIO/Outputs/VTKOutput.hpp
  src/coreComponents/fileIO/python/PyHistoryCollection.cpp
  src/coreComponents/fileIO/python/PyHistoryOutput.cpp
  src/coreComponents/fileIO/python/PyVTKOutput.cpp
  src/coreComponents/fileIO/python/PyVTKOutputType.hpp
  src/coreComponents/fileIO/vtk/VTKPVDWriter.cpp
  src/coreComponents/fileIO/vtk/VTKPVDWriter.hpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.hpp
  src/coreComponents/physicsSolvers/python/PySolver.cpp
  src/pygeosx/pygeosx.cpp
Labels: type: feature, flag: ready for review, type: pygeosx

#1987 Feature/ascuotto/vtk import
  src/coreComponents/mesh/generators/VTKMeshGenerator.cpp
  src/coreComponents/mesh/generators/VTKMeshGenerator.hpp
  src/coreComponents/unitTests/meshTests/cube.pvts
  src/coreComponents/unitTests/meshTests/cube.vts
  src/coreComponents/unitTests/meshTests/cube/cube_0.vts
  src/coreComponents/unitTests/meshTests/cube/cube_1.vts
  src/coreComponents/unitTests/meshTests/cube/cube_2.vts
  src/coreComponents/unitTests/meshTests/cube/cube_3.vts
  src/coreComponents/unitTests/meshTests/testVTKImport.cpp
Labels: type: feature, flag: ready for review

#2013 Fix TPL discrepancy between travis and azure
  azure-pipelines.yml
Labels: type: build

#2012 Add getter for region type.
  src/coreComponents/finiteVolume/TwoPointFluxApproximation.cpp
Labels: flag: ready to be merged

#2019 Re-enable unit tests in OSX CI and fix catalog registration
  .travis.yml
  host-configs/darwin-clang.cmake
Labels: type: testing

#1983 Improved parsing speed for table files
  src/coreComponents/codingUtilities/CMakeLists.txt
  src/coreComponents/codingUtilities/Parsing.hpp
  src/coreComponents/codingUtilities/tests/CMakeLists.txt
  src/coreComponents/codingUtilities/tests/testParsing.cpp
  src/coreComponents/events/CMakeLists.txt
  src/coreComponents/functions/CMakeLists.txt
  src/coreComponents/functions/TableFunction.cpp
  src/coreComponents/functions/TableFunction.hpp
  src/thirdparty/CMakeLists.txt
  src/thirdparty/fast_float/CMakeLists.txt
  src/thirdparty/fast_float/VERSION
  src/thirdparty/fast_float/include/fast_float.h
Labels: type: optimization, flag: ready for review

#2001 Cleanup of face/cell boundary condition in flow solvers
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
Labels: type: cleanup / refactor, flag: ready to be merged

#2025 Using `large` VMs travis
  .travis.yml
  scripts/build_test_helper.sh
Labels: type: build, flag: ready to be merged

#2018 Re-enable object libraries build
  scripts/build_test_helper.sh
  src/cmake/GeosxOptions.cmake
  src/cmake/thirdparty/SetupGeosxThirdParty.cmake
Labels: type: testing, type: build, flag: ready to be merged

#2038 Update TPL
  .travis.yml
Labels: flag: requires updated TPL(s)
