Repository GEOS-DEV/GEOS, pull requests merged in 2022-10, with the labels that each got.

#2095 Enabled PEBI cells in single-phase hybrid FVM
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVMKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBaseExtrinsicData.hpp
  src/coreComponents/physicsSolvers/fluidFlow/HybridFVMHelperKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVMKernels.hpp
  src/coreComponents/unitTests/fluidFlowTests/CMakeLists.txt
  src/coreComponents/unitTests/fluidFlowTests/testSinglePhaseHybridFVMKernels.cpp
Labels: type: cleanup / refactor, flag: ready to be merged

#2105 Updating sphinx publications
  src/docs/sphinx/Publications.rst
Labels: type: documentation, flag: ready to be merged

#2112 Fix outdated rst files
  src/docs/sphinx/advancedExamples/validationStudies/carbonStorage/isothermalLeakyWell/Example.rst
  src/docs/sphinx/basicExamples/co2Injection/Example.rst
  src/docs/sphinx/basicExamples/multiphaseFlow/Example.rst
  src/docs/sphinx/basicExamples/multiphaseFlowWithWells/Example.rst
  src/docs/sphinx/tutorials/step03/Tutorial.rst
  src/docs/sphinx/tutorials/step04/Tutorial.rst
Labels: type: documentation, flag: ready for review

#2091 First version of `meshDoctor`
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/__init__.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/collocated_nodes.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/generate_fractures.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/generate_global_ids.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/register.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/vtk_utils.py
  src/coreComponents/python/modules/geosx_mesh_doctor/mesh_doctor.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/__init__.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/cli_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/collocated_nodes_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/generate_fractures_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/generate_global_ids_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/register.py
  src/coreComponents/python/modules/geosx_mesh_doctor/pyproject.toml
  src/coreComponents/python/modules/geosx_mesh_doctor/setup.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_collocated_nodes.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_generate_fractures.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_generate_global_ids.py
Labels: flag: ready for review

#2120 Reduce linux capabilities for docker in CI
  .travis.yml
  src/docs/sphinx/developerGuide/Contributing/InstallWin.rst
  src/docs/sphinx/developerGuide/Contributing/UsingDocker.rst
Labels: type: build system

#2080 Fix nvcc crash related to fast_float
  src/coreComponents/codingUtilities/CMakeLists.txt
  src/coreComponents/codingUtilities/Parsing.cpp
  src/coreComponents/codingUtilities/Parsing.hpp
  src/coreComponents/mesh/CMakeLists.txt
Labels: type: bug, flag: ready for review

#2114 Modify compositional FaceBasedAssemblyKernel to work with interesecting fractures.
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/ThermalCompositionalMultiphaseFVMKernels.hpp
Labels: flag: ready to be merged

#2124 Output hypre version
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreInterface.cpp
  src/coreComponents/mainInterface/initialization.cpp
  src/main/main.cpp
Labels: flag: ready for review

#2140 Update Multi-resolution publication data.
  src/docs/sphinx/Publications.rst
Labels: flag: ready to be merged

#2134 fix scotch compilation
  src/coreComponents/mesh/CMakeLists.txt
  src/coreComponents/mesh/generators/VTKUtilities.cpp
Labels: type: bug, type: build system, flag: ready to be merged

#2139 Support for more vtk mesh formats
  src/coreComponents/mesh/generators/VTKMeshGenerator.cpp
  src/coreComponents/mesh/generators/VTKMeshGenerator.hpp
  src/coreComponents/mesh/generators/VTKUtilities.cpp
  src/coreComponents/mesh/generators/VTKUtilities.hpp
  src/coreComponents/unitTests/meshTests/cube.pvti
  src/coreComponents/unitTests/meshTests/cube.pvtr
  src/coreComponents/unitTests/meshTests/cube.pvts
  src/coreComponents/unitTests/meshTests/cube.pvtu
  src/coreComponents/unitTests/meshTests/cube.vti
  src/coreComponents/unitTests/meshTests/cube.vtr
  src/coreComponents/unitTests/meshTests/cube.vts
  src/coreComponents/unitTests/meshTests/cube.vtu
  src/coreComponents/unitTests/meshTests/cube/cube_0.vti
  src/coreComponents/unitTests/meshTests/cube/cube_0.vtr
  src/coreComponents/unitTests/meshTests/cube/cube_0.vts
  src/coreComponents/unitTests/meshTests/cube/cube_0.vtu
  src/coreComponents/unitTests/meshTests/cube/cube_1.vti
  src/coreComponents/unitTests/meshTests/cube/cube_1.vtr
  src/coreComponents/unitTests/meshTests/cube/cube_1.vts
  src/coreComponents/unitTests/meshTests/cube/cube_1.vtu
  src/coreComponents/unitTests/meshTests/cube/cube_2.vti
  src/coreComponents/unitTests/meshTests/cube/cube_2.vtr
  src/coreComponents/unitTests/meshTests/cube/cube_2.vts
  src/coreComponents/unitTests/meshTests/cube/cube_2.vtu
  src/coreComponents/unitTests/meshTests/cube/cube_3.vti
  src/coreComponents/unitTests/meshTests/cube/cube_3.vtr
  src/coreComponents/unitTests/meshTests/cube/cube_3.vts
  src/coreComponents/unitTests/meshTests/cube/cube_3.vtu
  src/coreComponents/unitTests/meshTests/cube_RECTILINEAR_GRID.vtk
  src/coreComponents/unitTests/meshTests/cube_STRUCTURED_GRID.vtk
  src/coreComponents/unitTests/meshTests/cube_STRUCTURED_POINTS.vtk
  src/coreComponents/unitTests/meshTests/cube_UNSTRUCTURED_GRID.vtk
  src/coreComponents/unitTests/meshTests/testVTKImport.cpp
Labels: type: feature, flag: ready for review
