Repository GEOS-DEV/GEOS, pull requests merged in 2022-01, with the labels that each got.

#1720 Reduce visibility of nested structures after refactoring.
  src/coreComponents/constitutive/fluid/CompressibleSinglePhaseFluid.hpp
  src/coreComponents/constitutive/fluid/ParticleFluid.hpp
  src/coreComponents/constitutive/fluid/ParticleFluidBase.hpp
  src/coreComponents/constitutive/fluid/ProppantSlurryFluid.hpp
  src/coreComponents/constitutive/fluid/SingleFluidBase.hpp
  src/coreComponents/constitutive/fluid/SlurryFluidBase.hpp
Labels: flag: ready to be merged

#1564 [Feature] implement fault permeability models
  inputFiles/poromechanics/SlipPermeability_embeddedFrac.xml
  inputFiles/poromechanics/SlipPermeability_pEDFM_base.xml
  inputFiles/poromechanics/SlipPermeability_pEDFM_smoke.xml
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/ConstitutivePassThru.hpp
  src/coreComponents/constitutive/docs/PermeabilityModels.rst
  src/coreComponents/constitutive/docs/SlipDependentPermeability.rst
  src/coreComponents/constitutive/permeability/ParallelPlatesPermeability.cpp
  src/coreComponents/constitutive/permeability/ParallelPlatesPermeability.hpp
  src/coreComponents/constitutive/permeability/PermeabilityBase.hpp
  src/coreComponents/constitutive/permeability/PermeabilityExtrinsicData.hpp
  src/coreComponents/constitutive/permeability/ProppantPermeability.cpp
  src/coreComponents/constitutive/permeability/ProppantPermeability.hpp
  src/coreComponents/constitutive/permeability/SlipDependentPermeability.cpp
  src/coreComponents/constitutive/permeability/SlipDependentPermeability.hpp
  src/coreComponents/constitutive/permeability/StrainDependentPermeability.cpp
  src/coreComponents/constitutive/permeability/StrainDependentPermeability.hpp
  src/coreComponents/constitutive/solid/CompressibleSolid.cpp
  src/coreComponents/constitutive/solid/CompressibleSolid.hpp
  src/coreComponents/constitutive/solid/CoupledSolidBase.hpp
  src/coreComponents/finiteVolume/SurfaceElementStencil.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVMKernels.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEFEMKernel.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsFluxKernels.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsFluxKernels.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsSolverEmbeddedFractures.cpp
  src/coreComponents/schema/docs/CompressibleSolidSlipDependentPermeability.rst
  src/coreComponents/schema/docs/CompressibleSolidSlipDependentPermeability_other.rst
  src/coreComponents/schema/docs/Constitutive.rst
  src/coreComponents/schema/docs/Constitutive_other.rst
  src/coreComponents/schema/docs/ParallelPlatesPermeability_other.rst
  src/coreComponents/schema/docs/ProppantPermeability_other.rst
  src/coreComponents/schema/docs/SlipDependentPermeability.rst
  src/coreComponents/schema/docs/SlipDependentPermeability_other.rst
  src/coreComponents/schema/docs/StrainDependentPermeability.rst
  src/coreComponents/schema/docs/StrainDependentPermeability_other.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/docs/sphinx/CompleteXMLSchema.rst
Labels: type: feature, flag: ready to be merged, flag: requires rebaseline

#1714 Implemented multivariable multidimensional interpolators for future OBL solver
  src/coreComponents/functions/CMakeLists.txt
  src/coreComponents/functions/MultivariableTableFunction.cpp
  src/coreComponents/functions/MultivariableTableFunction.hpp
  src/coreComponents/functions/MultivariableTableFunctionKernels.hpp
  src/coreComponents/schema/docs/Functions.rst
  src/coreComponents/schema/docs/Functions_other.rst
  src/coreComponents/schema/docs/MultivariableTableFunction.rst
  src/coreComponents/schema/docs/MultivariableTableFunction_other.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/functionsTests/testFunctions.cpp
  src/docs/sphinx/CompleteXMLSchema.rst
Labels: type: feature, effort: 1 week, flag: ready to be merged

#1729 Improved the Newton solver for solubility and density in CO2-brine fluid
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/PVTFunctions/BrineEnthalpy.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/CO2EOSSolver.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/CO2EOSSolver.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/CO2Enthalpy.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/CO2Solubility.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/FenghourCO2Viscosity.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/SpanWagnerCO2Density.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/SpanWagnerCO2Density.hpp
  src/coreComponents/mesh/WellElementRegion.cpp
  src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp
Labels: type: cleanup / refactor, flag: ready to be merged

#1747 Correct traits and add template getter protection.
  src/coreComponents/codingUtilities/tests/testGeosxTraits.cpp
  src/coreComponents/codingUtilities/traits.hpp
  src/coreComponents/physicsSolvers/fluidFlow/StencilAccessors.hpp
  src/coreComponents/physicsSolvers/fluidFlow/proppantTransport/ProppantTransportKernels.hpp
Labels: type: bug

#1624 Updating geosx_xml_tools installation method
  scripts/setupPythonEnvironment.bash
  scripts/setupVirtualPythonEnvironment.bash
  src/coreComponents/fileIO/doc/InputXMLFiles.rst
  src/coreComponents/python/CMakeLists.txt
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/regex_tools.py
Labels: flag: ready to be merged

#1749 Simplification of the return_script in travis.
  .travis.yml
Labels: type: cleanup / refactor
