Repository GEOS-DEV/GEOS, pull requests merged in 2022-07, with the labels that each got.

#1890 Refactored well solvers before coupling with poromechanics
  inputFiles/compositionalMultiphaseWell/dead_oil_wells_hybrid_2d.xml
  src/coreComponents/codingUtilities/Utilities.hpp
  src/coreComponents/mesh/CMakeLists.txt
  src/coreComponents/mesh/ObjectManagerBase.hpp
  src/coreComponents/mesh/PerforationData.cpp
  src/coreComponents/mesh/PerforationData.hpp
  src/coreComponents/mesh/PerforationExtrinsicData.hpp
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellSolverBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoir.cpp
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.hpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.cpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/ReservoirSolverBase.cpp
  src/coreComponents/physicsSolvers/multiphysics/ReservoirSolverBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoirAndWells.hpp
  src/coreComponents/schema/docs/CompositionalMultiphaseReservoir.rst
  src/coreComponents/schema/docs/SinglePhaseReservoir.rst
  src/coreComponents/schema/docs/wellElementSubRegion_other.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/wellsTests/testReservoirCompositionalMultiphaseMSWells.cpp
  src/coreComponents/unitTests/wellsTests/testReservoirSinglePhaseMSWells.cpp
Labels: type: cleanup / refactor, flag: ready to be merged

#1969 Azure Pipelines
  .travis.yml
  azure-pipelines.yml
  azure-pipelines.yml.old
  scripts/build_test_helper.sh
  scripts/ci_build_and_test.sh
Labels: type: testing, flag: ready for review

#1988 Move gcc 10 debug job back to Travis
  .travis.yml
  azure-pipelines.yml
Labels: type: bug, type: testing, type: dev environment

#1966 Point to last build of TPL PR #187
  .travis.yml
Labels: flag: ready to be merged
