Repository GEOS-DEV/GEOS, pull requests merged in 2022-03, with the labels that each got.

#1793 Restored compatibility checks in compositional solvers
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVMKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.hpp
Labels: type: cleanup / refactor, flag: ready to be merged

#1704 Feature/besset pygeosx
  src/CMakeLists.txt
  src/coreComponents/CMakeLists.txt
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/unitTests/CMakeLists.txt
  src/coreComponents/dataRepository/CMakeLists.txt
  src/coreComponents/dataRepository/Group.cpp
  src/coreComponents/dataRepository/Group.hpp
  src/coreComponents/dataRepository/python/CMakeLists.txt
  src/coreComponents/dataRepository/python/PyGroup.cpp
  src/coreComponents/dataRepository/python/PyGroup.hpp
  src/coreComponents/dataRepository/python/PyGroupType.hpp
  src/coreComponents/dataRepository/python/PyWrapper.cpp
  src/coreComponents/dataRepository/python/PyWrapper.hpp
  src/coreComponents/dataRepository/unitTests/CMakeLists.txt
  src/coreComponents/fileIO/CMakeLists.txt
  src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp
  src/coreComponents/fileIO/Outputs/TimeHistoryOutput.hpp
  src/coreComponents/fileIO/python/CMakeLists.txt
  src/coreComponents/fileIO/python/PyHistoryCollection.cpp
  src/coreComponents/fileIO/python/PyHistoryCollectionType.hpp
  src/coreComponents/fileIO/python/PyHistoryOutput.cpp
  src/coreComponents/fileIO/python/PyHistoryOutputType.hpp
  src/coreComponents/fileIO/timeHistory/TimeHistoryCollection.hpp
  src/coreComponents/finiteElement/unitTests/CMakeLists.txt
  src/coreComponents/linearAlgebra/unitTests/CMakeLists.txt
  src/coreComponents/mainInterface/ProblemManager.hpp
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/SolverBase.cpp
  src/coreComponents/physicsSolvers/SolverBase.hpp
  src/coreComponents/physicsSolvers/python/CMakeLists.txt
  src/coreComponents/physicsSolvers/python/PySolver.cpp
  src/coreComponents/physicsSolvers/python/PySolver.hpp
  src/coreComponents/physicsSolvers/python/PySolverType.hpp
  src/coreComponents/schema/docs/AcousticSEM_other.rst
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/CMakeLists.txt
  src/coreComponents/unitTests/constitutiveTests/CMakeLists.txt
  src/coreComponents/unitTests/dataRepositoryTests/CMakeLists.txt
  src/coreComponents/unitTests/fieldSpecificationTests/CMakeLists.txt
  src/coreComponents/unitTests/fileIOTests/CMakeLists.txt
  src/coreComponents/unitTests/finiteVolumeTests/CMakeLists.txt
  src/coreComponents/unitTests/fluidFlowTests/CMakeLists.txt
  src/coreComponents/unitTests/functionsTests/CMakeLists.txt
  src/coreComponents/unitTests/linearAlgebraTests/CMakeLists.txt
  src/coreComponents/unitTests/meshTests/CMakeLists.txt
  src/coreComponents/unitTests/virtualElementTests/CMakeLists.txt
  src/coreComponents/unitTests/wellsTests/CMakeLists.txt
  src/coreComponents/unitTests/xmlTests/CMakeLists.txt
  src/pygeosx/CMakeLists.txt
  src/pygeosx/pygeosx.cpp
  src/pygeosx/pygeosx.hpp
Labels: type: feature, flag: ready to be merged, type: pygeosx

#1777 Add tpls include in dummy cmake for doc.
  src/docs/sphinx/QuickStart.rst
Labels: type: documentation

#1807 fix clang10 issue by modifying dependency in unitTests CmakeLists
  src/coreComponents/CMakeLists.txt
  src/coreComponents/common/unitTests/CMakeLists.txt
  src/coreComponents/constitutive/unitTests/CMakeLists.txt
  src/coreComponents/dataRepository/CMakeLists.txt
  src/coreComponents/dataRepository/unitTests/CMakeLists.txt
  src/coreComponents/finiteElement/unitTests/CMakeLists.txt
  src/coreComponents/linearAlgebra/unitTests/CMakeLists.txt
  src/coreComponents/schema/docs/AcousticSEM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseFVM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseHybridFVM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseReservoir_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseWell_other.rst
  src/coreComponents/schema/docs/EmbeddedSurfaceGenerator_other.rst
  src/coreComponents/schema/docs/FlowProppantTransport_other.rst
  src/coreComponents/schema/docs/Hydrofracture_other.rst
  src/coreComponents/schema/docs/LagrangianContact_other.rst
  src/coreComponents/schema/docs/LaplaceFEM_other.rst
  src/coreComponents/schema/docs/MultiphasePoromechanics_other.rst
  src/coreComponents/schema/docs/PhaseFieldDamageFEM_other.rst
  src/coreComponents/schema/docs/PhaseFieldFracture_other.rst
  src/coreComponents/schema/docs/ProppantTransport_other.rst
  src/coreComponents/schema/docs/SinglePhaseFVM_other.rst
  src/coreComponents/schema/docs/SinglePhaseHybridFVM_other.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanicsEmbeddedFractures_other.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanics_other.rst
  src/coreComponents/schema/docs/SinglePhaseProppantFVM_other.rst
  src/coreComponents/schema/docs/SinglePhaseReservoir_other.rst
  src/coreComponents/schema/docs/SinglePhaseWell_other.rst
  src/coreComponents/schema/docs/SolidMechanicsEmbeddedFractures_other.rst
  src/coreComponents/schema/docs/SolidMechanicsLagrangianSSLE_other.rst
  src/coreComponents/schema/docs/SolidMechanics_LagrangianFEM_other.rst
  src/coreComponents/schema/docs/SurfaceGenerator_other.rst
  src/coreComponents/schema/docs/TwoPointFluxApproximation_other.rst
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/CMakeLists.txt
  src/coreComponents/unitTests/constitutiveTests/CMakeLists.txt
  src/coreComponents/unitTests/dataRepositoryTests/CMakeLists.txt
  src/coreComponents/unitTests/fieldSpecificationTests/CMakeLists.txt
  src/coreComponents/unitTests/fileIOTests/CMakeLists.txt
  src/coreComponents/unitTests/finiteVolumeTests/CMakeLists.txt
  src/coreComponents/unitTests/fluidFlowTests/CMakeLists.txt
  src/coreComponents/unitTests/functionsTests/CMakeLists.txt
  src/coreComponents/unitTests/linearAlgebraTests/CMakeLists.txt
  src/coreComponents/unitTests/meshTests/CMakeLists.txt
  src/coreComponents/unitTests/virtualElementTests/CMakeLists.txt
  src/coreComponents/unitTests/wellsTests/CMakeLists.txt
  src/coreComponents/unitTests/xmlTests/CMakeLists.txt
Labels: type: bug, priority: critical, flag: ready for review

#1570 Documentation: constitutive models in the developer guide
  src/coreComponents/constitutive/docs/constitutiveDeveloperGuide.rst
  src/coreComponents/constitutive/fluid/SingleFluidBase.cpp
  src/coreComponents/constitutive/fluid/SingleFluidBase.hpp
  src/coreComponents/constitutive/solid/CoupledSolid.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/docs/sphinx/developerGuide/KeyComponents/constitutiveModels_link.rst
  src/docs/sphinx/developerGuide/KeyComponents/index_KeyComponents.rst
Labels: type: documentation, flag: ready for review

#1820 Correct argument order inconsistency.
  src/coreComponents/mesh/EmbeddedSurfaceSubRegion.cpp
  src/coreComponents/physicsSolvers/surfaceGeneration/EmbeddedSurfaceGenerator.cpp
Labels: type: cleanup / refactor

#1809 Refactored compositional flow unit tests
  src/coreComponents/constitutive/capillaryPressure/VanGenuchtenCapillaryPressure.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBaseExtrinsicData.hpp
  src/coreComponents/schema/docs/AcousticSEM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseFVM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseHybridFVM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseReservoir_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseWell_other.rst
  src/coreComponents/schema/docs/EmbeddedSurfaceGenerator_other.rst
  src/coreComponents/schema/docs/FlowProppantTransport_other.rst
  src/coreComponents/schema/docs/Hydrofracture_other.rst
  src/coreComponents/schema/docs/LagrangianContact_other.rst
  src/coreComponents/schema/docs/LaplaceFEM_other.rst
  src/coreComponents/schema/docs/MultiphasePoromechanics_other.rst
  src/coreComponents/schema/docs/PhaseFieldDamageFEM_other.rst
  src/coreComponents/schema/docs/PhaseFieldFracture_other.rst
  src/coreComponents/schema/docs/ProppantTransport_other.rst
  src/coreComponents/schema/docs/SinglePhaseFVM_other.rst
  src/coreComponents/schema/docs/SinglePhaseHybridFVM_other.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanicsEmbeddedFractures_other.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanics_other.rst
  src/coreComponents/schema/docs/SinglePhaseProppantFVM_other.rst
  src/coreComponents/schema/docs/SinglePhaseReservoir_other.rst
  src/coreComponents/schema/docs/SinglePhaseWell_other.rst
  src/coreComponents/schema/docs/SolidMechanicsEmbeddedFractures_other.rst
  src/coreComponents/schema/docs/SolidMechanicsLagrangianSSLE_other.rst
  src/coreComponents/schema/docs/SolidMechanics_LagrangianFEM_other.rst
  src/coreComponents/schema/docs/SurfaceGenerator_other.rst
  src/coreComponents/schema/docs/TwoPointFluxApproximation_other.rst
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/fluidFlowTests/testCompFlowUtils.hpp
  src/coreComponents/unitTests/fluidFlowTests/testCompMultiphaseFlow.cpp
  src/coreComponents/unitTests/fluidFlowTests/testCompMultiphaseFlowHybrid.cpp
Labels: type: cleanup / refactor, flag: ready to be merged

#1600 Poromechanics kernels refactoring
  src/coreComponents/constitutive/solid/PorousSolid.hpp
  src/coreComponents/constitutive/solid/SolidModelDiscretizationOps.hpp
  src/coreComponents/constitutive/solid/SolidModelDiscretizationOpsFullyAnisotroipic.hpp
  src/coreComponents/constitutive/solid/SolidModelDiscretizationOpsIsotropic.hpp
  src/coreComponents/constitutive/solid/SolidModelDiscretizationOpsOrthotropic.hpp
  src/coreComponents/constitutive/solid/SolidModelDiscretizationOpsTransverseIsotropic.hpp
  src/coreComponents/constitutive/solid/porosity/BiotPorosity.hpp
  src/coreComponents/finiteElement/BilinearFormUtilities.hpp
  src/coreComponents/finiteElement/CMakeLists.txt
  src/coreComponents/finiteElement/LinearFormUtilities.hpp
  src/coreComponents/finiteElement/PDEUtilities.hpp
  src/coreComponents/finiteElement/elementFormulations/FiniteElementBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanicsKernel.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsKernel.hpp
  src/coreComponents/schema/docs/AcousticSEM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseFVM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseHybridFVM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseReservoir_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseWell_other.rst
  src/coreComponents/schema/docs/EmbeddedSurfaceGenerator_other.rst
  src/coreComponents/schema/docs/FlowProppantTransport_other.rst
  src/coreComponents/schema/docs/Hydrofracture_other.rst
  src/coreComponents/schema/docs/LagrangianContact_other.rst
  src/coreComponents/schema/docs/LaplaceFEM_other.rst
  src/coreComponents/schema/docs/MultiphasePoromechanics_other.rst
  src/coreComponents/schema/docs/PhaseFieldDamageFEM_other.rst
  src/coreComponents/schema/docs/PhaseFieldFracture_other.rst
  src/coreComponents/schema/docs/ProppantTransport_other.rst
  src/coreComponents/schema/docs/SinglePhaseFVM_other.rst
  src/coreComponents/schema/docs/SinglePhaseHybridFVM_other.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanicsEmbeddedFractures_other.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanics_other.rst
  src/coreComponents/schema/docs/SinglePhaseProppantFVM_other.rst
  src/coreComponents/schema/docs/SinglePhaseReservoir_other.rst
  src/coreComponents/schema/docs/SinglePhaseWell_other.rst
  src/coreComponents/schema/docs/SolidMechanicsEmbeddedFractures_other.rst
  src/coreComponents/schema/docs/SolidMechanicsLagrangianSSLE_other.rst
  src/coreComponents/schema/docs/SolidMechanics_LagrangianFEM_other.rst
  src/coreComponents/schema/docs/SurfaceGenerator_other.rst
  src/coreComponents/schema/docs/TwoPointFluxApproximation_other.rst
  src/coreComponents/schema/schema.xsd.other
Labels: type: cleanup / refactor, flag: ready for review

#1822 Cleaned up isPointInsidePolyhedron
  src/coreComponents/mesh/WellElementSubRegion.cpp
  src/coreComponents/mesh/utilities/ComputationalGeometry.hpp
Labels: type: cleanup / refactor, flag: ready to be merged

#1828 Correct implementation for right-preconditioned BiCGStab
  src/coreComponents/linearAlgebra/solvers/BicgstabSolver.cpp
  src/coreComponents/linearAlgebra/solvers/BicgstabSolver.hpp
Labels: type: bug, flag: ready to be merged

#1792 `*packByIndex*` functions of Wrapper depends on `sizedFromParent() == 1`.
  src/coreComponents/codingUtilities/Utilities.hpp
  src/coreComponents/dataRepository/Group.cpp
  src/coreComponents/dataRepository/Group.hpp
  src/coreComponents/dataRepository/Wrapper.hpp
  src/coreComponents/dataRepository/WrapperBase.hpp
  src/coreComponents/fileIO/timeHistory/PackCollection.cpp
  src/coreComponents/mesh/CellElementSubRegion.cpp
  src/coreComponents/mesh/CellElementSubRegion.hpp
  src/coreComponents/mesh/EmbeddedSurfaceNodeManager.cpp
  src/coreComponents/mesh/EmbeddedSurfaceNodeManager.hpp
  src/coreComponents/mesh/EmbeddedSurfaceSubRegion.cpp
  src/coreComponents/mesh/EmbeddedSurfaceSubRegion.hpp
  src/coreComponents/mesh/FaceElementSubRegion.cpp
  src/coreComponents/mesh/FaceElementSubRegion.hpp
  src/coreComponents/mesh/FaceManager.cpp
  src/coreComponents/mesh/FaceManager.hpp
  src/coreComponents/mesh/NodeManager.cpp
  src/coreComponents/mesh/NodeManager.hpp
  src/coreComponents/mesh/ObjectManagerBase.cpp
  src/coreComponents/mesh/ObjectManagerBase.hpp
  src/coreComponents/mesh/WellElementSubRegion.cpp
  src/coreComponents/mesh/WellElementSubRegion.hpp
Labels: type: cleanup / refactor

#1813 Fixed the double free corruption problem in the unit tests after integration of pygeosx
  src/CMakeLists.txt
  src/cmake/thirdparty/SetupGeosxThirdParty.cmake
  src/coreComponents/constitutive/unitTests/CMakeLists.txt
  src/coreComponents/dataRepository/CMakeLists.txt
  src/coreComponents/dataRepository/python/CMakeLists.txt
  src/coreComponents/dataRepository/python/PyGroup.hpp
  src/coreComponents/dataRepository/unitTests/CMakeLists.txt
  src/coreComponents/fileIO/CMakeLists.txt
  src/coreComponents/fileIO/python/CMakeLists.txt
  src/coreComponents/fileIO/python/PyHistoryCollection.cpp
  src/coreComponents/fileIO/python/PyHistoryOutput.cpp
  src/coreComponents/finiteElement/unitTests/CMakeLists.txt
  src/coreComponents/linearAlgebra/unitTests/CMakeLists.txt
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/python/CMakeLists.txt
  src/coreComponents/physicsSolvers/python/PySolver.cpp
  src/coreComponents/physicsSolvers/python/PySolver.hpp
  src/coreComponents/unitTests/constitutiveTests/CMakeLists.txt
  src/coreComponents/unitTests/dataRepositoryTests/CMakeLists.txt
  src/coreComponents/unitTests/fieldSpecificationTests/CMakeLists.txt
  src/coreComponents/unitTests/fileIOTests/CMakeLists.txt
  src/coreComponents/unitTests/finiteVolumeTests/CMakeLists.txt
  src/coreComponents/unitTests/fluidFlowTests/CMakeLists.txt
  src/coreComponents/unitTests/functionsTests/CMakeLists.txt
  src/coreComponents/unitTests/linearAlgebraTests/CMakeLists.txt
  src/coreComponents/unitTests/meshTests/CMakeLists.txt
  src/coreComponents/unitTests/virtualElementTests/CMakeLists.txt
  src/coreComponents/unitTests/wellsTests/CMakeLists.txt
  src/coreComponents/unitTests/xmlTests/CMakeLists.txt
  src/pygeosx/CMakeLists.txt
Labels: type: bug, flag: ready for review, type: pygeosx

#1850 Correct Group::pack
  src/coreComponents/dataRepository/Group.cpp
Labels: type: bug, priority: critical

#1832 Improve config-build.py and put cache option at the end of the command line.
  scripts/config-build.py
Labels: type: bug, flag: ready for review

#1846 Improved phase internal energy computation
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/CO2BrineFluid.cpp
  src/coreComponents/constitutive/fluid/CO2BrineFluid.hpp
  src/coreComponents/constitutive/fluid/MultiFluidBase.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/BrineInternalEnergy.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/BrineInternalEnergy.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/CO2InternalEnergy.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/CO2InternalEnergy.hpp
  src/coreComponents/constitutive/fluid/PhaseModel.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanicsSolver.cpp
  src/coreComponents/schema/docs/AcousticSEM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseFVM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseHybridFVM_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseReservoir_other.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseWell_other.rst
  src/coreComponents/schema/docs/EmbeddedSurfaceGenerator_other.rst
  src/coreComponents/schema/docs/FlowProppantTransport_other.rst
  src/coreComponents/schema/docs/Hydrofracture_other.rst
  src/coreComponents/schema/docs/LagrangianContact_other.rst
  src/coreComponents/schema/docs/LaplaceFEM_other.rst
  src/coreComponents/schema/docs/MultiphasePoromechanics_other.rst
  src/coreComponents/schema/docs/PhaseFieldDamageFEM_other.rst
  src/coreComponents/schema/docs/PhaseFieldFracture_other.rst
  src/coreComponents/schema/docs/ProppantTransport_other.rst
  src/coreComponents/schema/docs/SinglePhaseFVM_other.rst
  src/coreComponents/schema/docs/SinglePhaseHybridFVM_other.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanicsEmbeddedFractures_other.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanics_other.rst
  src/coreComponents/schema/docs/SinglePhaseProppantFVM_other.rst
  src/coreComponents/schema/docs/SinglePhaseReservoir_other.rst
  src/coreComponents/schema/docs/SinglePhaseWell_other.rst
  src/coreComponents/schema/docs/SolidMechanicsEmbeddedFractures_other.rst
  src/coreComponents/schema/docs/SolidMechanicsLagrangianSSLE_other.rst
  src/coreComponents/schema/docs/SolidMechanics_LagrangianFEM_other.rst
  src/coreComponents/schema/docs/SurfaceGenerator_other.rst
  src/coreComponents/schema/docs/TwoPointFluxApproximation_other.rst
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp
Labels: type: cleanup / refactor, flag: ready for review
