Repository GEOS-DEV/GEOS, pull requests merged in 2022-06, with the labels that each got.

#1931 Fixed misleading behavior in source flux boundary condition
  src/coreComponents/fieldSpecification/FieldSpecificationBase.cpp
  src/coreComponents/fieldSpecification/FieldSpecificationBase.hpp
  src/coreComponents/fieldSpecification/SourceFluxBoundaryCondition.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
Labels: flag: ready to be merged

#1938 update pangea3 host-config file and remove hard-coded Python version
  host-configs/TOTAL/pangea3-gcc8.4.1-openmpi-4.1.2.cmake
  src/pygeosx/CMakeLists.txt
Labels: flag: ready to be merged, flag: ready for review

#1946 Remove mermaid support and use plantuml instead.
  src/conf.py
  src/coreComponents/mesh/docs/MeshObjectInstantiationHierarchy.plantuml
  src/coreComponents/mesh/docs/meshDeveloperGuide.rst
  src/docs/sphinx/requirements.txt
Labels: type: bug, flag: ready to be merged

#1888 Use Gitlab CI for nightly testing
  .gitlab-ci.yml
Labels: flag: ready to be merged, flag: ready for review

#1929 Fix some warning when compiled with some version of gcc
  src/coreComponents/functions/TableFunction.hpp
  src/coreComponents/mainInterface/ProblemManager.cpp
  src/coreComponents/mesh/mpiCommunications/NeighborCommunicator.cpp
Labels: flag: ready to be merged

#1954 missing mass intialization
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.cpp
Labels: flag: ready to be merged

#1951 fix OpenBLAS in Pangea3 host-config, add pygeosx to install process
  host-configs/TOTAL/pangea3-gcc8.4.1-openmpi-4.1.2.cmake
  src/pygeosx/CMakeLists.txt
Labels: flag: ready to be merged
