Repository GEOS-DEV/GEOS, pull requests merged in 2022-11, with the labels that each got.

#2151 Restored logging in VTKMeshGenerator
  src/coreComponents/mesh/generators/VTKMeshGenerator.cpp
  src/coreComponents/mesh/generators/VTKUtilities.cpp
  src/coreComponents/mesh/generators/VTKUtilities.hpp
Labels: type: cleanup / refactor, flag: ready to be merged

#2152 Fix failing integrated tests on gitlab
  .gitlab-ci.yml
Labels: type: build system, flag: ready for review

#2149 Allow choice of finite element types in Finite Element Dispatch
  src/coreComponents/finiteElement/FiniteElementDispatch.hpp
  src/coreComponents/finiteElement/kernelInterface/KernelBase.hpp
  src/coreComponents/mainInterface/ProblemManager.cpp
  src/coreComponents/physicsSolvers/multiphysics/PhaseFieldFractureSolver.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEM.hpp
  src/coreComponents/physicsSolvers/wavePropagation/WaveSolverBase.hpp
Labels: type: bug, flag: ready to be merged, type: optimization

#2117 add flags to enable fesapi
  .travis.yml
  host-configs/tpls.cmake
  src/cmake/GeosxOptions.cmake
  src/cmake/thirdparty/SetupGeosxThirdParty.cmake
Labels: type: build system, flag: ready to be merged, flag: requires updated TPL(s)

#2076 Shared Library
  host-configs/LLNL/lassen-base.cmake
  src/cmake/GeosxOptions.cmake
  src/coreComponents/CMakeLists.txt
Labels: type: build system, flag: ready to be merged

#2150 Feature/karimifard/supported elements unit test
  src/coreComponents/unitTests/meshTests/medley-42.vtk
  src/coreComponents/unitTests/meshTests/medley.vtk
  src/coreComponents/unitTests/meshTests/supportedElements.vtk
  src/coreComponents/unitTests/meshTests/supportedElementsAsVTKPolyhedra.vtk
  src/coreComponents/unitTests/meshTests/testVTKImport.cpp
Labels: type: testing, flag: ready to be merged

#2142 Add python unit tests
  inputFiles/hydraulicFracturing/scripts/hydrofractureQueries.py
  scripts/makeSampleMeshFiles.py
  scripts/processIntegratedTestCheckFailures.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/collocated_nodes.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/generate_fractures.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/generate_global_ids.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/vtk_utils.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/cli_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/collocated_nodes_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/generate_fractures_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/generate_global_ids_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_collocated_nodes.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_generate_fractures.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_generate_global_ids.py
  src/coreComponents/python/modules/geosx_xml_tools_package/geosx_xml_tools/command_line_parsers.py
  src/coreComponents/python/modules/pygeosx_tools_package/setup.cfg
  src/docs/doxygen/GeosxConfig.hpp
  src/docs/sphinx/advancedExamples/validationStudies/carbonStorage/buckleyLeverett/buckleyLeverettFigure.py
  src/docs/sphinx/advancedExamples/validationStudies/carbonStorage/thermalLeakyWell/thermalLeakyWell.py
  src/docs/sphinx/advancedExamples/validationStudies/hydraulicFracture/kgdToughnessDominated/kgdToughnessDominatedFigure.py
  src/docs/sphinx/advancedExamples/validationStudies/hydraulicFracture/kgdValidation/kgdValidationQueries.py
  src/docs/sphinx/advancedExamples/validationStudies/hydraulicFracture/kgdViscosityDominated/kgdViscosityDominatedFigure.py
  src/docs/sphinx/advancedExamples/validationStudies/hydraulicFracture/pennyFracToughnessDominated/pennyShapedToughnessDominatedFigure.py
  src/docs/sphinx/advancedExamples/validationStudies/hydraulicFracture/pennyFracViscosityDominated/pennyShapedViscosityDominatedFigure.py
  src/docs/sphinx/advancedExamples/validationStudies/hydraulicFracture/pknFracViscosityDominated/pknViscosityDominatedFigure.py
  src/pygeosx/CMakeLists.txt
  src/pygeosx/reentrantTest.py
  src/pygeosx/test.py
  src/pygeosx/unitTests/CMakeLists.txt
  src/pygeosx/unitTests/dataRepositoryTests/pygeosx_only.xml
  src/pygeosx/unitTests/dataRepositoryTests/test_pygeosxDataRepository.py
Labels: type: testing, flag: ready to be merged, type: pygeosx

#2157 Build should not stop if FESAPI is not defined.
  src/cmake/thirdparty/SetupGeosxThirdParty.cmake
Labels: type: build system

#2084 Optimization of initialization phase
  src/coreComponents/dataRepository/BufferOps_inline.hpp
  src/coreComponents/mesh/MeshLevel.cpp
Labels: flag: ready to be merged, type: optimization

#2160 avoid warning on non reachable statement after return
  src/coreComponents/common/MpiWrapper.cpp
Labels: flag: ready to be merged

#2156 Feature/enable hypre gpu on pangea3
  host-configs/TOTAL/pangea3-gcc8.4.1-openmpi-4.1.2.cmake
Labels: flag: ready to be merged

#2181 Fixed compilation issue on Lassen
  src/coreComponents/mesh/generators/VTKFaceBlockUtilities.cpp
Labels: type: bug, flag: ready to be merged
