Repository GEOS-DEV/GEOS, pull requests merged in 2023-04, with the labels that each got.

#2342 Fix flow gravity term in fractures
  inputFiles/singlePhaseFlowFractures/fractureFlowWithGravity_conforming_2d.xml
  inputFiles/singlePhaseFlowFractures/fractureMatrixFlowWithGravity_edfm_verticalFrac_smoke.xml
  inputFiles/singlePhaseFlowFractures/fractureMatrixFlow_conforming_2d_gravity.xml
  src/coreComponents/physicsSolvers/surfaceGeneration/EmbeddedSurfaceGenerator.cpp
  src/coreComponents/physicsSolvers/surfaceGeneration/SurfaceGenerator.cpp
Labels: flag: requires rebaseline

#2354 Improve wording for travis jobs
  .travis.yml
Labels: type: documentation

#2351 Improved WellControls input control
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellControls.cpp
Labels: type: bug

#2387 Fixed uninitialized variables in flux kernels
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsFluxKernels.cpp
Labels: type: bug, flag: ready to be merged

#2382 Documentation for GitHub codespaces
  src/docs/sphinx/developerGuide/Contributing/UsingDocker.rst
Labels: type: documentation

#2391 Update .gitmodules
  .gitmodules
Labels: flag: ready to be merged

#2341 ObjectPath XML errors feedback
  src/coreComponents/codingUtilities/StringUtilities.hpp
  src/coreComponents/common/Logger.cpp
  src/coreComponents/common/Logger.hpp
  src/coreComponents/dataRepository/Group.cpp
  src/coreComponents/dataRepository/Group.hpp
  src/coreComponents/fieldSpecification/FieldSpecificationBase.cpp
  src/coreComponents/fileIO/timeHistory/HistoryCollectionBase.cpp
  src/coreComponents/mesh/ElementRegionBase.hpp
  src/coreComponents/mesh/ElementRegionManager.hpp
  src/coreComponents/mesh/MeshObjectPath.cpp
  src/coreComponents/mesh/MeshObjectPath.hpp
  src/coreComponents/mesh/unitTests/testMeshObjectPath.cpp
  src/coreComponents/unitTests/dataRepositoryTests/CMakeLists.txt
  src/coreComponents/unitTests/dataRepositoryTests/testGroupPath.cpp
Labels: type: bug, flag: ready for review

#2414 Proppant smoke tests with gcc
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsFluxKernels.cpp
Labels: type: bug
