Repository GEOS-DEV/GEOS, pull requests merged in 2023-05, with the labels that each got.

#2396 Bugfix/jmeng/validatebchighorder2
  src/coreComponents/fieldSpecification/FieldSpecificationManager.cpp
  src/coreComponents/mesh/MeshLevel.cpp
  src/coreComponents/mesh/MeshObjectPath.cpp
  src/coreComponents/mesh/MeshObjectPath.hpp
Labels: flag: ready to be merged

#2395 Cleaned up sparsity pattern of pore volume constraint
  src/coreComponents/linearAlgebra/DofManager.cpp
  src/coreComponents/linearAlgebra/DofManager.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/MultiphasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalCompositionalMultiphaseFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalMultiphasePoromechanics.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
Labels: type: cleanup / refactor, flag: ready to be merged

#2274 Improvements in `mesh_doctor`
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/element_volumes.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/fix_elements_orderings.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/generate_cube.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/generate_fractures.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/generate_global_ids.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/non_conformal.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/reorient_mesh.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/self_intersecting_elements.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/supported_elements.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/triangle_distance.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/vtk_polyhedron.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/vtk_utils.py
  src/coreComponents/python/modules/geosx_mesh_doctor/mesh_doctor.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/__init__.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/cli_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/collocated_nodes_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/element_volumes_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/fix_elements_orderings_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/generate_cube_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/generate_fractures_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/generate_global_ids_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/non_conformal_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/self_intersecting_elements_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/supported_elements_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/vtk_output_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/register.py
  src/coreComponents/python/modules/geosx_mesh_doctor/requirements.txt
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_generate_cube.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_generate_fractures.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_generate_global_ids.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_non_conformal.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_reorient_mesh.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_supported_elements.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_triangle_distance.py
Labels: type: feature, EPIC - FF/Import

#2419 Remove utility functions from SolidBaseUpdates
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/solid/Damage.hpp
  src/coreComponents/constitutive/solid/ElasticOrthotropic.hpp
  src/coreComponents/constitutive/solid/ElasticTransverseIsotropic.hpp
  src/coreComponents/constitutive/solid/SolidBase.hpp
  src/coreComponents/constitutive/solid/SolidUtilities.hpp
  src/coreComponents/constitutive/unitTests/testDruckerPrager.cpp
  src/coreComponents/constitutive/unitTests/testElasticIsotropic.cpp
  src/coreComponents/constitutive/unitTests/testModifiedCamClay.cpp
  src/coreComponents/physicsSolvers/solidMechanics/kernels/ExplicitFiniteStrain_impl.hpp
  src/coreComponents/unitTests/constitutiveTests/testDamage.cpp
Labels: type: cleanup / refactor, flag: ready to be merged

#2426 Output run start/end/ranks
  src/cmake/thirdparty/SetupGeosxThirdParty.cmake
  src/coreComponents/codingUtilities/EnumStrings.hpp
  src/coreComponents/common/Format.hpp
  src/coreComponents/common/initializeEnvironment.cpp
  src/main/main.cpp
Labels: flag: ready to be merged

#2405 Doc for the viscoplastic theory
  src/coreComponents/constitutive/docs/solid/SolidModels.rst
  src/coreComponents/constitutive/docs/solid/ViscoPlasticity.rst
Labels: type: documentation, flag: ready for review

#2439 Fix regression in config-build
  scripts/config-build.py
Labels: flag: ready for review

#2460 Bugfix for {fmt} cmake
  src/cmake/thirdparty/SetupGeosxThirdParty.cmake
  src/coreComponents/common/CMakeLists.txt
Labels: type: bug, flag: ready to be merged

#2437 fix compatibility with cmake 3.17
  src/cmake/thirdparty/SetupGeosxThirdParty.cmake
Labels: flag: ready for review

#2458 Fixed a few xmls
  inputFiles/lagrangianContactMechanics/ContactMechanics_slippingFault_horizontal_smoke.xml
  inputFiles/lagrangianContactMechanics/ContactMechanics_slippingFault_vertical_smoke.xml
  inputFiles/phaseField/PhaseFieldFracture_Nucleation_base.xml
  inputFiles/proppant/ProppantGelTransport_base.xml
  inputFiles/solidMechanics/ExtendedDruckerPragerWellbore_benchmark.xml
  inputFiles/solidMechanics/KirschProblem_benchmark.xml
  inputFiles/solidMechanics/ModifiedCamClayWellbore_benchmark.xml
  inputFiles/solidMechanics/solidMechBlock.xml
  inputFiles/thermoPoromechanics/ThermoPoroElastic_consolidation_benchmark_sequential.xml
  src/coreComponents/constitutive/contact/ContactBase.cpp
  src/coreComponents/unitTests/xmlTests/basic_input.xml
  src/coreComponents/unitTests/xmlTests/multifile_input/boundary_conditions/velocity.xml
Labels: type: bug, flag: ready for review

#2459 Refactor in flux kernel in prep. for upwinding work
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseFVMKernelUtilities.hpp
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseFVMKernels.hpp
Labels: type: cleanup / refactor, flag: ready to be merged

#2433 Fix assert variable scope.
  src/coreComponents/mesh/generators/CellBlockManager.cpp
Labels: flag: ready to be merged

#2457 Upwind enthalpy flux for sourceFlux b.c. for producers (positive fluxes)
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
Labels: flag: ready for review

#2464 Ensure unit tests are enabled by default.
  .travis.yml
  host-configs/LLNL/lassen-clang10-cuda11.cmake
  host-configs/LLNL/lassen-clang13-cuda11.cmake
  host-configs/ORNL/frontier-base.cmake
  scripts/uberenv/packages/geosx/package.py
  src/cmake/GeosxOptions.cmake
  src/coreComponents/CMakeLists.txt
  src/coreComponents/codingUtilities/CMakeLists.txt
  src/coreComponents/codingUtilities/UnitTestUtilities.hpp
  src/coreComponents/common/CMakeLists.txt
  src/coreComponents/common/GEOS_RAJA_Interface.hpp
  src/coreComponents/common/unitTests/CMakeLists.txt
  src/coreComponents/common/unitTests/testLifoStorage.cpp
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/unitTests/testDruckerPrager.cpp
  src/coreComponents/constitutive/unitTests/testModifiedCamClay.cpp
  src/coreComponents/dataRepository/CMakeLists.txt
  src/coreComponents/denseLinearAlgebra/CMakeLists.txt
  src/coreComponents/finiteElement/CMakeLists.txt
  src/coreComponents/finiteElement/unitTests/CMakeLists.txt
  src/coreComponents/linearAlgebra/CMakeLists.txt
  src/coreComponents/linearAlgebra/unitTests/testVectors.cpp
  src/coreComponents/mesh/CMakeLists.txt
  src/coreComponents/unitTests/functionsTests/testFunctions.cpp
  src/coreComponents/unitTests/linearAlgebraTests/testLAIHelperFunctions.cpp
  src/coreComponents/unitTests/virtualElementTests/testConformingVirtualElementOrder1.cpp
  src/docs/doxygen/GeosxConfig.hpp
  src/pygeosx/CMakeLists.txt
Labels: type: bug, type: testing, type: build system, flag: ready for review
