Repository GEOS-DEV/GEOS, pull requests merged in 2023-11, with the labels that each got.

#2791 Update TPL tag to point back to the HEAD of the repo
  .github/workflows/ci_tests.yml
Labels: flag: ready to be merged, flag: ready for review

#2760 Activate `sccache` in the `CI/CD`
  .devcontainer/devcontainer.json
  .github/workflows/build_and_test.yml
  .github/workflows/ci_tests.yml
  scripts/ci_build_and_test.sh
  scripts/ci_build_and_test_in_container.sh
  src/coreComponents/mesh/FaceElementSubRegion.cpp
Labels: flag: ready to be merged, flag: requires updated TPL(s)

#2450 Add more context to errors - mesh/ files
  src/coreComponents/dataRepository/GroupContext.cpp
  src/coreComponents/mainInterface/ProblemManager.cpp
  src/coreComponents/mesh/CellElementRegion.cpp
  src/coreComponents/mesh/CellElementSubRegion.cpp
  src/coreComponents/mesh/ElementType.hpp
  src/coreComponents/mesh/FaceManager.cpp
  src/coreComponents/mesh/Perforation.cpp
  src/coreComponents/mesh/PerforationData.cpp
  src/coreComponents/mesh/SurfaceElementRegion.hpp
  src/coreComponents/mesh/WellElementRegion.cpp
  src/coreComponents/mesh/WellElementSubRegion.cpp
  src/coreComponents/mesh/generators/CellBlock.cpp
  src/coreComponents/mesh/generators/CellBlockUtilities.cpp
  src/coreComponents/mesh/generators/ExternalMeshGeneratorBase.cpp
  src/coreComponents/mesh/generators/InternalMeshGenerator.cpp
  src/coreComponents/mesh/generators/InternalMeshGenerator.hpp
  src/coreComponents/mesh/generators/InternalWellGenerator.cpp
  src/coreComponents/mesh/generators/InternalWellboreGenerator.cpp
  src/coreComponents/mesh/generators/PrismUtilities.hpp
  src/coreComponents/mesh/generators/VTKUtilities.cpp
  src/coreComponents/mesh/simpleGeometricObjects/Box.cpp
  src/coreComponents/mesh/simpleGeometricObjects/ThickPlane.cpp
  src/coreComponents/schema/schema.xsd
Labels: flag: ready to be merged, flag: ready for review

#2797 Remove unused variables
  src/coreComponents/constitutive/unitTests/testCubicEOS.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
Labels: type: cleanup / refactor, flag: ready to be merged, ci: ready for review

#2772 Add phase composition to PVTDriver output
  src/coreComponents/constitutive/docs/PVTDriver.rst
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidUtils.hpp
  src/coreComponents/constitutive/fluid/multifluid/PVTDriver.cpp
  src/coreComponents/constitutive/fluid/multifluid/PVTDriver.hpp
  src/coreComponents/constitutive/fluid/multifluid/PVTDriverRunTest.hpp
  src/coreComponents/schema/docs/PVTDriver.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/unitTests/constitutiveTests/CMakeLists.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_PhaseComposition.xml
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/deadOilPVDO.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/dryGasPVDG.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/liveOilPVDG.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/liveOilPVTO.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/watPVT.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_deadOilA.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_deadOilB.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_hydrocarbonMixture.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_liveBlackOil.txt
Labels: type: feature, flag: ready to be merged, ci: ready for review

#2769 Create compositional multiphase fluid
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidSelector.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluidPVTPackage.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluidPVTPackage.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluidUpdates.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluidUpdates.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/PVTDriverRunTestCompositionalMultiphaseFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/ComponentProperties.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/CompositionalDensity.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/CompositionalDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/ConstantViscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/ConstantViscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/FunctionBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/NegativeTwoPhaseFlashModel.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/NegativeTwoPhaseFlashModel.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/NullModel.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/PhaseModel.hpp
  src/coreComponents/schema/docs/CompositonalTwoPhaseFluidPengRobinson.rst
  src/coreComponents/schema/docs/CompositonalTwoPhaseFluidPengRobinson_other.rst
  src/coreComponents/schema/docs/CompositonalTwoPhaseFluidSoaveRedlichKwong.rst
  src/coreComponents/schema/docs/CompositonalTwoPhaseFluidSoaveRedlichKwong_other.rst
  src/coreComponents/schema/docs/Constitutive.rst
  src/coreComponents/schema/docs/Constitutive_other.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/constitutiveTests/testMultiFluid.cpp
  src/docs/sphinx/CompleteXMLSchema.rst
Labels: flag: ready to be merged

#2829 Upgrade version of `sccache` for GPU builds
  .devcontainer/devcontainer.json
  scripts/ci_build_and_test_in_container.sh
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/PVTDriverRunTestCO2BrineEzrokhiThermalFluid.cpp
Labels: ci: ready to be merged, flag: requires updated TPL(s)

#2527 Feature in-tree external components
  .gitignore
  src/cmake/GeosxOptions.cmake
  src/externalComponents/CMakeLists.txt
  src/externalComponents/newComponentTemplate/src/CMakeLists.txt
  src/externalComponents/newComponentTemplate/src/NewComponent.cpp
  src/externalComponents/newComponentTemplate/src/NewComponent.hpp
Labels: type: build system, ci: ready to be merged

#2818 allow empty source and receivers
  src/coreComponents/physicsSolvers/wavePropagation/WaveSolverBase.cpp
  src/coreComponents/schema/docs/AcousticFirstOrderSEM.rst
  src/coreComponents/schema/docs/AcousticSEM.rst
  src/coreComponents/schema/docs/AcousticVTISEM.rst
  src/coreComponents/schema/docs/ElasticFirstOrderSEM.rst
  src/coreComponents/schema/docs/ElasticSEM.rst
  src/coreComponents/schema/schema.xsd
Labels: type: bug, ci: ready to be merged

#2409 MGR strategies cleanup
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGR.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreUtils.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/HybridSinglePhasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/Hydrofracture.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/LagrangianContactMechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/MultiphasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/MultiphasePoromechanicsReservoirFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ReactiveCompositionalMultiphaseOBL.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhaseHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhasePoromechanicsEmbeddedFractures.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhasePoromechanicsReservoirFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhaseReservoirFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhaseReservoirHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SolidMechanicsEmbeddedFractures.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalCompositionalMultiphaseFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalMultiphasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalSinglePhasePoromechanics.hpp
Labels: type: cleanup / refactor, ci: ready to be merged

#2799 Use ComponentProperties in calculation functions
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/CompositionalProperties.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/CompositionalProperties.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/CubicEOSPhaseModel.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/KValueInitialization.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/NegativeTwoPhaseFlash.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/NegativeTwoPhaseFlashModel.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/NegativeTwoPhaseFlashModel.hpp
  src/coreComponents/constitutive/unitTests/TestFluid.hpp
  src/coreComponents/constitutive/unitTests/testCompositionalProperties.cpp
  src/coreComponents/constitutive/unitTests/testCubicEOS.cpp
  src/coreComponents/constitutive/unitTests/testKValueInitialization.cpp
  src/coreComponents/constitutive/unitTests/testNegativeTwoPhaseFlash.cpp
Labels: type: cleanup / refactor, ci: ready to be merged, flag: ready for review
