Repository GEOS-DEV/GEOS, pull requests merged in 2023-08, with the labels that each got.

#2598 Github Actions - Separate CUDA builds
  .github/workflows/ci_tests.yml
Labels: type: testing, flag: ready to be merged

#2573 [Testing] Test Github Actions tagged Docker Images
  .github/workflows/ci_tests.yml
Labels: type: testing

#2608 Fix a bug in MappedVector::erase
  src/coreComponents/dataRepository/MappedVector.hpp
Labels: flag: ready to be merged

#2510 Fix validation of injection streams
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
Labels: type: bug, flag: ready to be merged

#2495 Adding list of types dispatch capabilities.
  .github/workflows/ci_tests.yml
  src/coreComponents/common/TypeDispatch.hpp
  src/coreComponents/common/unitTests/CMakeLists.txt
  src/coreComponents/common/unitTests/testTypeDispatch.cpp
  src/coreComponents/fieldSpecification/FieldSpecificationBase.hpp
  src/coreComponents/fileIO/silo/SiloFile.cpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
  src/coreComponents/functions/CMakeLists.txt
  src/coreComponents/functions/FunctionBase.hpp
  src/coreComponents/functions/unitTests/CMakeLists.txt
  src/coreComponents/functions/unitTests/testFunctions.cpp
  src/coreComponents/linearAlgebra/DofManager.cpp
  src/coreComponents/mesh/CellElementSubRegion.cpp
  src/coreComponents/mesh/generators/VTKUtilities.cpp
  src/coreComponents/unitTests/CMakeLists.txt
  src/docs/doxygen/GeosxConfig.hpp
Labels: type: cleanup / refactor
