Repository GEOS-DEV/GEOS, pull requests merged in 2023-02, with the labels that each got.

#2254 Skipped system setup to reduce data movement to GPU
  src/coreComponents/common/DataTypes.hpp
  src/coreComponents/mesh/MeshLevel.cpp
  src/coreComponents/mesh/MeshLevel.hpp
  src/coreComponents/physicsSolvers/SolverBase.cpp
  src/coreComponents/physicsSolvers/SolverBase.hpp
  src/coreComponents/physicsSolvers/contact/ContactSolverBase.cpp
  src/coreComponents/physicsSolvers/contact/ContactSolverBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/ReactiveCompositionalMultiphaseOBL.cpp
  src/coreComponents/physicsSolvers/fluidFlow/ReactiveCompositionalMultiphaseOBL.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.cpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceBaseH1.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
  src/coreComponents/physicsSolvers/surfaceGeneration/SurfaceGenerator.cpp
Labels: type: cleanup / refactor, flag: ready to be merged

#2269 Validate well to reservoir connections
  src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.cpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.hpp
Labels: type: bug, flag: ready to be merged

#2276 Improve doc for docker development.
  src/docs/sphinx/developerGuide/Contributing/Dockerfile-remote-dev.example
  src/docs/sphinx/developerGuide/Contributing/InstallWin.rst
  src/docs/sphinx/developerGuide/Contributing/UsingDocker.rst
Labels: type: documentation

#2288 Fix build issue #2287
  src/coreComponents/common/lifoStorage.hpp
Labels: type: bug, flag: ready for review

#2281 Fix compilation warning/error with clang
  src/coreComponents/constitutive/fluid/BlackOilFluid.hpp
  src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp
Labels: type: bug
