Repository GEOS-DEV/GEOS, pull requests merged in 2023-01, with the labels that each got.

#2229 Changed abs to LvArray::math::abs
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/WaveSolverUtils.hpp
Labels: type: bug, flag: ready to be merged

#2234 Remove hardcoded number of degrees of freedom
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEM.cpp
Labels: type: bug

#2237 Added dedicated MGR recipe for OBL
  src/coreComponents/linearAlgebra/CMakeLists.txt
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGR.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ReactiveCompositionalMultiphaseOBL.hpp
  src/coreComponents/linearAlgebra/utilities/LinearSolverParameters.hpp
  src/coreComponents/physicsSolvers/fluidFlow/ReactiveCompositionalMultiphaseOBL.cpp
Labels: type: feature, flag: ready to be merged

#2239 Fix bug when we get the number of degrees of freedom which implies resize with 0 as dimension
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEM.cpp
Labels: type: bug, flag: ready to be merged

#2241 Remove OSX job from Travis
  .travis.yml
Labels: flag: ready to be merged

#1817 Add Reactions for Geochemistry and a ReactiveMultiFluidModel
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/ConstitutiveBase.hpp
  src/coreComponents/constitutive/fluid/MultiFluidBase.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/PureWaterProperties.hpp
  src/coreComponents/constitutive/fluid/PVTFunctions/WaterDensity.cpp
  src/coreComponents/constitutive/fluid/PVTFunctions/WaterDensity.hpp
  src/coreComponents/constitutive/fluid/ReactiveBrineFluid.cpp
  src/coreComponents/constitutive/fluid/ReactiveBrineFluid.hpp
  src/coreComponents/constitutive/fluid/ReactiveFluidDriver.cpp
  src/coreComponents/constitutive/fluid/ReactiveFluidDriver.hpp
  src/coreComponents/constitutive/fluid/ReactiveMultiFluid.cpp
  src/coreComponents/constitutive/fluid/ReactiveMultiFluid.hpp
  src/coreComponents/constitutive/fluid/ReactiveMultiFluidFields.hpp
  src/coreComponents/constitutive/fluid/chemicalReactions/EquilibriumReactions.cpp
  src/coreComponents/constitutive/fluid/chemicalReactions/EquilibriumReactions.hpp
  src/coreComponents/constitutive/fluid/chemicalReactions/KineticReactions.cpp
  src/coreComponents/constitutive/fluid/chemicalReactions/KineticReactions.hpp
  src/coreComponents/constitutive/fluid/chemicalReactions/ReactionsBase.cpp
  src/coreComponents/constitutive/fluid/chemicalReactions/ReactionsBase.hpp
  src/coreComponents/constitutive/fluid/reactiveFluidSelector.hpp
  src/coreComponents/schema/docs/Constitutive.rst
  src/coreComponents/schema/docs/Constitutive_other.rst
  src/coreComponents/schema/docs/ReactiveBrine.rst
  src/coreComponents/schema/docs/ReactiveBrineThermal.rst
  src/coreComponents/schema/docs/ReactiveBrineThermal_other.rst
  src/coreComponents/schema/docs/ReactiveBrine_other.rst
  src/coreComponents/schema/docs/ReactiveFluidDriver.rst
  src/coreComponents/schema/docs/ReactiveFluidDriver_other.rst
  src/coreComponents/schema/docs/Tasks.rst
  src/coreComponents/schema/docs/Tasks_other.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/constitutiveTests/CMakeLists.txt
  src/coreComponents/unitTests/constitutiveTests/testDistilledWater.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/reactiveBrinePVT.txt
  src/coreComponents/unitTests/constitutiveTests/testReactiveBrine.txt
  src/coreComponents/unitTests/constitutiveTests/testReactiveFluid.cpp
  src/coreComponents/unitTests/constitutiveTests/testReactiveFluid.xml
  src/docs/sphinx/CompleteXMLSchema.rst
Labels: flag: ready to be merged

#2092 Feature/add lifo storage
  src/coreComponents/common/CMakeLists.txt
  src/coreComponents/common/fixedSizeDeque.hpp
  src/coreComponents/common/lifoStorage.hpp
  src/coreComponents/common/unitTests/CMakeLists.txt
  src/coreComponents/common/unitTests/testFixedSizeDeque.cpp
  src/coreComponents/common/unitTests/testLifoStorage.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/WaveSolverBase.cpp
  src/coreComponents/physicsSolvers/wavePropagation/WaveSolverBase.hpp
  src/coreComponents/schema/schema.xsd
  src/docs/doxygen/GeosxConfig.hpp
Labels: type: feature, flag: ready to be merged, flag: ready for review

#2212 move non mesh parts of importFields to meshManager
  src/coreComponents/mainInterface/ProblemManager.cpp
  src/coreComponents/mesh/DomainPartition.hpp
  src/coreComponents/mesh/MeshManager.cpp
  src/coreComponents/mesh/generators/ExternalMeshGeneratorBase.cpp
  src/coreComponents/mesh/generators/InternalMeshGenerator.hpp
  src/coreComponents/mesh/generators/InternalWellGenerator.hpp
  src/coreComponents/mesh/generators/MeshGeneratorBase.hpp
  src/coreComponents/mesh/generators/VTKMeshGenerator.cpp
  src/coreComponents/mesh/generators/VTKMeshGenerator.hpp
  src/coreComponents/mesh/generators/VTKUtilities.cpp
  src/coreComponents/mesh/generators/VTKUtilities.hpp
Labels: type: cleanup / refactor

#2251 Fixed bug in MGR recipe
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/MultiphasePoromechanicsReservoirFVM.hpp
Labels: type: bug, flag: ready to be merged
