Repository GEOS-DEV/GEOS, pull requests merged in 2023-06, with the labels that each got.

#2468 Preparatory work for local chop implementation
  .travis.yml
  src/coreComponents/linearAlgebra/DofManager.cpp
  src/coreComponents/linearAlgebra/DofManager.hpp
Labels: flag: ready to be merged

#2472 add missing geosx_core_libs removed in #2453
  src/coreComponents/CMakeLists.txt
Labels: type: bug, flag: ready for review

#2357 XML string array errors feedback
  src/coreComponents/common/DataTypes.hpp
  src/coreComponents/dataRepository/Wrapper.hpp
  src/coreComponents/dataRepository/WrapperBase.cpp
  src/coreComponents/dataRepository/WrapperBase.hpp
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
Labels: flag: ready to be merged

#2451 Implemented Rachford-Rice and cubic EOS
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/CubicEOSPhaseModel.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/RachfordRice.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/RachfordRice.hpp
  src/coreComponents/constitutive/fluid/singlefluid/ParticleFluidBase.hpp
  src/coreComponents/constitutive/unitTests/CMakeLists.txt
  src/coreComponents/constitutive/unitTests/testCubicEOS.cpp
  src/coreComponents/constitutive/unitTests/testRachfordRice.cpp
Labels: type: feature, flag: ready to be merged

#2497 Fix description for `forceDt` attribute in Geos doc tutorial 3
  src/docs/sphinx/tutorials/step03/Tutorial.rst
Labels: type: documentation, flag: ready to be merged

#2442 Update XMLs & Add script for analytical results of the EDP wellbore example
  inputFiles/solidMechanics/ExtendedDruckerPragerWellbore_base.xml
  inputFiles/solidMechanics/ExtendedDruckerPragerWellbore_benchmark.xml
  inputFiles/solidMechanics/ExtendedDruckerPragerWellbore_smoke.xml
  src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/edpWellbore/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/edpWellbore/Verification.png
  src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/edpWellbore/WellMesh.png
  src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/edpWellbore/edpWellboreVerification.png
  src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/edpWellbore/edpWellbore_analyticalResults.py
  src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/edpWellbore/edpWellbore_plot.py
  src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/elastoPlasticWellboreAnalyticalSolutions.py
Labels: type: documentation, flag: ready for review, flag: requires rebaseline, changes XML input

#2500 Fix unit test tests for Q3 and Q5 Gauss-Lobatto
  src/coreComponents/finiteElement/unitTests/CMakeLists.txt
  src/coreComponents/finiteElement/unitTests/testQ3_Hexahedron_Lagrange_GaussLobatto.cpp
  src/coreComponents/finiteElement/unitTests/testQ5_Hexahedron_Lagrange_GaussLobatto.cpp
Labels: flag: ready to be merged

#2506 Fix device build
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/RachfordRice.cpp
Labels: type: build system, flag: ready to be merged

#2400 Github Actions
  .github/workflows/ci_tests.yml
  scripts/ci_build_and_test.sh
Labels: flag: ready to be merged, type: dev environment

#2522 Bugfix/jmeng/multiregion for highorder
  src/coreComponents/mesh/MeshLevel.cpp
  src/coreComponents/mesh/generators/CellBlockManager.cpp
Labels: type: bug, flag: ready to be merged

#2492 Implement k-value initialisation
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/KValueInitialization.hpp
  src/coreComponents/constitutive/unitTests/CMakeLists.txt
  src/coreComponents/constitutive/unitTests/testKValueInitialization.cpp
Labels: type: feature, flag: ready to be merged

#2508 Added a warning for porosity above 1
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBaseKernels.hpp
Labels: type: cleanup / refactor, flag: ready to be merged

#2520 Implement Cubic EOS derivatives
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/CubicEOSPhaseModel.hpp
  src/coreComponents/constitutive/unitTests/TestFluid.hpp
  src/coreComponents/constitutive/unitTests/testCubicEOS.cpp
Labels: type: feature, flag: ready to be merged

#2531 Improve robustness of MGR strategies for THM problems
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalMultiphasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalSinglePhasePoromechanics.hpp
Labels: flag: ready to be merged, type: optimization

#2487 Stop validation of PeriodicEvent without a target
  src/coreComponents/dataRepository/ExecutableGroup.hpp
  src/coreComponents/events/PeriodicEvent.cpp
Labels: type: bug, flag: ready to be merged

#2499 Implemented RCM to reorder degrees of freedom
  src/coreComponents/linearAlgebra/CMakeLists.txt
  src/coreComponents/linearAlgebra/DofManager.cpp
  src/coreComponents/linearAlgebra/DofManager.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ReactiveCompositionalMultiphaseOBL.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalCompositionalMultiphaseFVM.hpp
  src/coreComponents/linearAlgebra/unitTests/CMakeLists.txt
  src/coreComponents/linearAlgebra/unitTests/testReverseCutHillMcKeeOrdering.cpp
  src/coreComponents/linearAlgebra/utilities/ReverseCutHillMcKeeOrdering.cpp
  src/coreComponents/linearAlgebra/utilities/ReverseCutHillMcKeeOrdering.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
Labels: type: feature, flag: ready to be merged

#2539 Fix compilation issue
  src/coreComponents/constitutive/unitTests/testCubicEOS.cpp
Labels: flag: ready to be merged

#2555 Github Actions - Check for all job completion
  .github/workflows/ci_tests.yml
Labels: type: testing, flag: ready to be merged
