Repository GEOS-DEV/GEOS, pull requests merged in 2023-12, with the labels that each got.

#2850 Run the integrated tests on GHA
  .devcontainer/devcontainer.json
  .github/workflows/build_and_test.yml
  .github/workflows/ci_tests.yml
  scripts/ci_build_and_test_in_container.sh
Labels: ci: ready to be merged, flag: requires updated TPL(s), ci: run integrated tests

#2872 Use GHA's `if:` instead of dedicated jobs
  .github/workflows/ci_tests.yml
Labels: ci: ready to be merged

#2783 A few solver messages rework
  src/coreComponents/common/MpiWrapper.hpp
  src/coreComponents/physicsSolvers/SolverBase.hpp
  src/coreComponents/physicsSolvers/contact/LagrangianContactSolver.hpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsEmbeddedFractures.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/ReactiveCompositionalMultiphaseOBL.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/proppantTransport/ProppantTransport.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.hpp
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.hpp
  src/coreComponents/physicsSolvers/multiphysics/FlowProppantTransportSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.hpp
  src/coreComponents/physicsSolvers/multiphysics/PhaseFieldFractureSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEmbeddedFractures.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoirAndWells.hpp
  src/coreComponents/physicsSolvers/simplePDE/LaplaceFEM.hpp
  src/coreComponents/physicsSolvers/simplePDE/PhaseFieldDamageFEM.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianSSLE.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsMPM.hpp
  src/coreComponents/physicsSolvers/surfaceGeneration/EmbeddedSurfaceGenerator.hpp
  src/coreComponents/physicsSolvers/surfaceGeneration/SurfaceGenerator.hpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticFirstOrderWaveEquationSEM.hpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticVTIWaveEquationSEM.hpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticFirstOrderWaveEquationSEM.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEM.hpp
  src/externalComponents/newComponentTemplate/src/NewComponent.hpp
Labels: type: cleanup / refactor, ci: ready to be merged, flag: ready for review

#2798 Properly reactivate PVT throwing
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellControls.cpp
Labels: ci: ready to be merged, flag: ready for review, flag: no rebaseline

#2844 A few mesh messages edit
  src/coreComponents/dataRepository/Group.cpp
  src/coreComponents/dataRepository/Group.hpp
  src/coreComponents/mesh/ElementType.hpp
  src/coreComponents/mesh/FaceManager.cpp
  src/coreComponents/mesh/generators/CellBlockUtilities.cpp
  src/coreComponents/mesh/generators/InternalMeshGenerator.cpp
  src/coreComponents/mesh/generators/PrismUtilities.hpp
  src/coreComponents/mesh/generators/VTKUtilities.cpp
  src/coreComponents/unitTests/meshTests/testVTKImport.cpp
Labels: ci: ready to be merged, flag: no rebaseline

#2859 Fix Issue #2833 and #2755
  inputFiles/poromechanicsFractures/SlipPermeability_embeddedFrac.xml
  inputFiles/proppant/ProppantGelTransport_base.xml
Labels: type: testing, ci: ready to be merged, flag: no rebaseline

#2802 Remove value only compute method from fluid models
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/CO2BrineFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/BrineEnthalpy.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Enthalpy.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineViscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/FenghourCO2Viscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/NoOpPVTFunction.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineViscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/SpanWagnerCO2Density.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/WaterDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/blackOil/BlackOilFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/blackOil/DeadOilFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluidPVTPackage.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluidUpdates.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/ComponentProperties.hpp
  src/coreComponents/constitutive/fluid/multifluid/reactive/ReactiveBrineFluid.hpp
  src/coreComponents/constitutive/fluid/singlefluid/CompressibleSinglePhaseFluid.hpp
  src/coreComponents/constitutive/fluid/singlefluid/SingleFluidBase.hpp
  src/coreComponents/constitutive/fluid/singlefluid/ThermalCompressibleSinglePhaseFluid.hpp
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVMKernels.hpp
Labels: type: cleanup / refactor, ci: ready to be merged, flag: ready for review, flag: no rebaseline

#2793 Enhance the fracture generation feature of `mesh_doctor`
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/check_fractures.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/collocated_nodes.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/element_volumes.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/fix_elements_orderings.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/generate_cube.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/generate_fractures.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/non_conformal.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/reorient_mesh.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/self_intersecting_elements.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/supported_elements.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/triangle_distance.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/vtk_polyhedron.py
  src/coreComponents/python/modules/geosx_mesh_doctor/checks/vtk_utils.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/check_fractures_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/collocated_nodes_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/generate_cube_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/generate_fractures_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/non_conformal_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/self_intersecting_elements_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/pyproject.toml
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_cli_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/tests/test_generate_fractures.py
Labels: ci: ready to be merged, flag: no rebaseline

#2825 Updating error checking in python setup script
  scripts/setupPythonEnvironment.bash
  src/coreComponents/python/CMakeLists.txt
  src/coreComponents/schema/docs/Constitutive.rst
  src/coreComponents/schema/docs/Constitutive_other.rst
  src/coreComponents/schema/docs/TableRelativePermeability.rst
  src/coreComponents/schema/docs/TableRelativePermeabilityHysteresis.rst
  src/coreComponents/schema/docs/TableRelativePermeabilityHysteresis_other.rst
  src/coreComponents/schema/docs/TableRelativePermeability_other.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/docs/sphinx/CompleteXMLSchema.rst
Labels: type: bug, ci: ready to be merged, ci: run integrated tests, flag: no rebaseline

#2602 Disable auto updating of docs/doxygen/GeosxConfig.hpp
  src/cmake/GeosxConfig.cmake
  src/cmake/thirdparty/SetupGeosxThirdParty.cmake
  src/coreComponents/common/GeosxConfig.hpp.in
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreInterface.cpp
  src/coreComponents/mainInterface/GeosxVersion.hpp.in
  src/coreComponents/mainInterface/initialization.cpp
  src/coreComponents/mainInterface/version.cpp
  src/coreComponents/mainInterface/version.hpp
  src/docs/doxygen/CMakeLists.txt
  src/docs/doxygen/GeosxConfig.hpp
  src/main/main.cpp
Labels: ci: ready to be merged, flag: no rebaseline

#2812 Cleanup compositional fluid model
  src/coreComponents/common/PhysicsConstants.hpp
  src/coreComponents/common/Units.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.cpp
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidConstants.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/CompositionalProperties.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/CubicEOSPhaseModel.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/ComponentProperties.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/FunctionBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/reactive/chemicalReactions/KineticReactions.hpp
  src/coreComponents/constitutive/solid/ElasticOrthotropic.hpp
  src/coreComponents/constitutive/solid/ElasticTransverseIsotropic.hpp
Labels: type: cleanup / refactor, ci: ready to be merged, flag: ready for review, flag: no rebaseline

#2884 Fix issue #2882 by using output dir in wells rates output
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellSolverBase.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsStatistics.cpp
Labels: ci: ready to be merged, flag: no rebaseline

#2842 SourceFlux & RegionStatistics crash fixes
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseStatistics.cpp
Labels: ci: ready to be merged, ci: run integrated tests, flag: no rebaseline

#2854 Fix Rachford-Rice solver
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/RachfordRice.hpp
  src/coreComponents/constitutive/unitTests/testRachfordRice.cpp
Labels: type: bug, ci: ready to be merged, flag: ready for review, flag: no rebaseline

#2889 Fix minCompDens
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
Labels: type: bug, ci: ready to be merged, flag: no rebaseline

#2892 Gitlab CI - cleanup untracked files
  .gitlab-ci.yml
Labels: ci: ready to be merged, flag: no rebaseline

#2877 Simulation duration output fix + timestep separator
  src/coreComponents/common/CMakeLists.txt
  src/coreComponents/common/Units.cpp
  src/coreComponents/common/Units.hpp
  src/coreComponents/common/unitTests/CMakeLists.txt
  src/coreComponents/common/unitTests/testUnits.cpp
  src/coreComponents/events/EventManager.cpp
  src/coreComponents/events/EventManager.hpp
  src/main/main.cpp
Labels: type: bug, ci: ready to be merged, flag: ready for review, ci: run integrated tests, flag: no rebaseline

#2861 Time step cut support for sequential solver
  src/coreComponents/physicsSolvers/SolverBase.cpp
  src/coreComponents/physicsSolvers/SolverBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
Labels: ci: ready to be merged, ci: run integrated tests, flag: no rebaseline
