Repository GEOS-DEV/GEOS, pull requests merged in 2023-09, with the labels that each got.

#2635 Build/modify apple builds
  host-configs/apple/darwin-clang.cmake
  host-configs/apple/macOS_Matteo.cmake
  host-configs/apple/macOS_arm.cmake
  host-configs/apple/macOS_base.cmake
  host-configs/apple/macOS_x86.cmake
  host-configs/appleM1-clang.cmake
  src/coreComponents/common/LifoStorageCommon.hpp
  src/docs/doxygen/GeosxConfig.hpp
Labels: type: dev environment

#2650 fix `fmtlib/fmt` padding bug
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
Labels: type: bug, flag: ready for review

#2404 Add Group & Wrapper source XML line in errors
  src/coreComponents/common/DataTypes.hpp
  src/coreComponents/common/Logger.hpp
  src/coreComponents/constitutive/unitTests/testDruckerPrager.cpp
  src/coreComponents/constitutive/unitTests/testElasticIsotropic.cpp
  src/coreComponents/constitutive/unitTests/testModifiedCamClay.cpp
  src/coreComponents/dataRepository/CMakeLists.txt
  src/coreComponents/dataRepository/DataContext.cpp
  src/coreComponents/dataRepository/DataContext.hpp
  src/coreComponents/dataRepository/Group.cpp
  src/coreComponents/dataRepository/Group.hpp
  src/coreComponents/dataRepository/GroupContext.cpp
  src/coreComponents/dataRepository/GroupContext.hpp
  src/coreComponents/dataRepository/Wrapper.hpp
  src/coreComponents/dataRepository/WrapperBase.cpp
  src/coreComponents/dataRepository/WrapperBase.hpp
  src/coreComponents/dataRepository/WrapperContext.cpp
  src/coreComponents/dataRepository/WrapperContext.hpp
  src/coreComponents/dataRepository/xmlWrapper.cpp
  src/coreComponents/dataRepository/xmlWrapper.hpp
  src/coreComponents/fieldSpecification/FieldSpecificationBase.cpp
  src/coreComponents/fileIO/timeHistory/HistoryCollectionBase.cpp
  src/coreComponents/fileIO/vtk/VTKPVDWriter.cpp
  src/coreComponents/fileIO/vtk/VTKVTMWriter.cpp
  src/coreComponents/mainInterface/ProblemManager.cpp
  src/coreComponents/mainInterface/ProblemManager.hpp
  src/coreComponents/mesh/ElementRegionBase.cpp
  src/coreComponents/mesh/ElementRegionManager.cpp
  src/coreComponents/mesh/ElementRegionManager.hpp
  src/coreComponents/mesh/MeshObjectPath.cpp
  src/coreComponents/schema/schemaUtilities.cpp
  src/coreComponents/unitTests/constitutiveTests/testDamage.cpp
  src/coreComponents/unitTests/dataRepositoryTests/testGroupPath.cpp
  src/coreComponents/unitTests/fluidFlowTests/testCompFlowUtils.hpp
  src/coreComponents/unitTests/fluidFlowTests/testSingleFlowUtils.hpp
  src/coreComponents/unitTests/linearAlgebraTests/testDofManagerUtils.hpp
  src/coreComponents/unitTests/meshTests/testMeshGeneration.cpp
  src/coreComponents/unitTests/meshTests/testVTKImport.cpp
  src/coreComponents/unitTests/virtualElementTests/testConformingVirtualElementOrder1.cpp
  src/coreComponents/unitTests/xmlTests/testXMLFile.cpp
Labels: flag: ready for review

#2605 Initialization of coupled solver is added
  src/coreComponents/physicsSolvers/multiphysics/CoupledSolver.hpp
Labels: type: bug, flag: ready to be merged

#2641 simplify `computeSeismoTrace` - add `writeSeismoTrace`
  src/coreComponents/physicsSolvers/wavePropagation/WaveSolverUtils.hpp
Labels: type: bug, type: cleanup / refactor

#2677 Fix python globbing to fix erroneous *py files
  src/coreComponents/python/CMakeLists.txt
Labels: type: bug, flag: ready to be merged, flag: ready for review

#2675 Fix deployment folder issues.
  .devcontainer/devcontainer.json
  .github/workflows/ci_tests.yml
  .gitignore
Labels: flag: requires updated TPL(s)

#2542 Compositional multiphase fluid properties
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/CompositionalProperties.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/CompositionalProperties.hpp
  src/coreComponents/constitutive/unitTests/CMakeLists.txt
  src/coreComponents/constitutive/unitTests/TestFluid.hpp
  src/coreComponents/constitutive/unitTests/testCompositionalProperties.cpp
Labels: type: feature, flag: ready to be merged

#2448 Add more context to errors - physicsSolvers/ files
  src/coreComponents/physicsSolvers/FieldStatisticsBase.hpp
  src/coreComponents/physicsSolvers/LinearSolverParameters.cpp
  src/coreComponents/physicsSolvers/NonlinearSolverParameters.cpp
  src/coreComponents/physicsSolvers/SolverBase.cpp
  src/coreComponents/physicsSolvers/contact/ContactSolverBase.cpp
  src/coreComponents/physicsSolvers/contact/LagrangianContactSolver.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/ReactiveCompositionalMultiphaseOBL.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseProppantBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/proppantTransport/ProppantTransport.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWellKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWellKernels.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellControls.cpp
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.cpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/PoromechanicsInitialization.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp
  src/coreComponents/physicsSolvers/multiphysics/poromechanicsKernels/MultiphasePoromechanics_impl.hpp
  src/coreComponents/physicsSolvers/simplePDE/PhaseFieldDamageFEM.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsStateReset.cpp
  src/coreComponents/physicsSolvers/surfaceGeneration/SurfaceGenerator.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticFirstOrderWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticFirstOrderWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/WaveSolverBase.cpp
Labels: flag: ready for review

#2447 Add more context to errors - constitutive/ files
  src/coreComponents/constitutive/ConstitutiveBase.hpp
  src/coreComponents/constitutive/ConstitutiveManager.cpp
  src/coreComponents/constitutive/ConstitutivePassThru.hpp
  src/coreComponents/constitutive/ConstitutivePassThruHandler.hpp
  src/coreComponents/constitutive/contact/ContactBase.cpp
  src/coreComponents/constitutive/contact/CoulombContact.cpp
  src/coreComponents/constitutive/contact/deprecated/ApertureTableContact.cpp
  src/coreComponents/constitutive/fluid/singlefluid/ParticleFluid.cpp
  src/coreComponents/constitutive/fluid/singlefluid/ProppantSlurryFluid.cpp
  src/coreComponents/constitutive/fluid/singlefluid/SlurryFluidBase.cpp
  src/coreComponents/constitutive/relativePermeability/TableRelativePermeabilityHelpers.cpp
  src/coreComponents/constitutive/solid/CoupledSolid.hpp
  src/coreComponents/constitutive/solid/Damage.cpp
  src/coreComponents/constitutive/solid/DelftEgg.cpp
  src/coreComponents/constitutive/solid/Deprecated/PoreVolumeCompressibleSolid.cpp
  src/coreComponents/constitutive/solid/DruckerPrager.cpp
  src/coreComponents/constitutive/solid/DruckerPragerExtended.cpp
  src/coreComponents/constitutive/solid/ElasticIsotropic.cpp
  src/coreComponents/constitutive/solid/ElasticIsotropicPressureDependent.cpp
  src/coreComponents/constitutive/solid/ElasticOrthotropic.cpp
  src/coreComponents/constitutive/solid/ModifiedCamClay.cpp
  src/coreComponents/constitutive/solid/TriaxialDriver.cpp
Labels: flag: ready for review

#2449 Add more context to errors - other files
  src/coreComponents/events/EventBase.cpp
  src/coreComponents/events/PeriodicEvent.cpp
  src/coreComponents/fieldSpecification/AquiferBoundaryCondition.cpp
  src/coreComponents/fieldSpecification/EquilibriumInitialCondition.cpp
  src/coreComponents/fieldSpecification/FieldSpecificationBase.hpp
  src/coreComponents/fieldSpecification/FieldSpecificationManager.cpp
  src/coreComponents/fieldSpecification/PerfectlyMatchedLayer.cpp
  src/coreComponents/fieldSpecification/TractionBoundaryCondition.cpp
  src/coreComponents/fileIO/Outputs/SiloOutput.cpp
  src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp
  src/coreComponents/fileIO/Outputs/VTKOutput.cpp
  src/coreComponents/fileIO/timeHistory/PackCollection.cpp
  src/coreComponents/finiteElement/FiniteElementDiscretization.cpp
  src/coreComponents/finiteVolume/HybridMimeticDiscretization.cpp
  src/coreComponents/functions/FunctionBase.hpp
  src/coreComponents/functions/MultivariableTableFunction.cpp
  src/coreComponents/functions/TableFunction.cpp
Labels: flag: ready for review

#2659 Github Actions - Run CUDA jobs only when read to merge
  .github/workflows/build_and_test.yml
  .github/workflows/ci_tests.yml
Labels: flag: ready to be merged
