Repository GEOS-DEV/GEOS, pull requests merged in 2023-10, with the labels that each got.

#2727 ReadTheDocs equations
  src/docs/sphinx/requirements.txt
Labels: type: documentation, flag: ready to be merged, flag: ready for review

#2684 Documentation for `mesh_doctor`
  src/conf.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/self_intersecting_elements_parsing.py
  src/coreComponents/python/modules/geosx_mesh_doctor/parsing/supported_elements_parsing.py
  src/docs/sphinx/pythonTools/mesh_doctor.rst
  src/docs/sphinx/pythonTools/pythonAPI.rst
  src/docs/sphinx/requirements.txt
Labels: type: documentation, flag: ready to be merged

#2702 Solve compilation issue with NVCC on some PowerPC machines
  host-configs/TOTAL/pangea3-gcc8.4.1-openmpi-4.1.2.cmake
  src/cmake/GeosxConfig.cmake
  src/coreComponents/common/GeosxConfig.hpp.in
  src/coreComponents/dataRepository/DataContext.hpp
Labels: type: bug, type: build system, flag: ready to be merged

#2711 Add a simple check for internal mesh partitioning
  src/coreComponents/mesh/generators/InternalMeshGenerator.cpp
Labels: flag: ready to be merged, flag: ready for review

#2712 More meaningful error message when mesh is missing in the input
  src/coreComponents/mesh/ElementRegionBase.cpp
Labels: flag: ready to be merged, flag: ready for review

#2649 Add solver timers for logLevel > 1
  src/coreComponents/common/CMakeLists.txt
  src/coreComponents/common/Timer.hpp
  src/coreComponents/mainInterface/GeosxState.cpp
  src/coreComponents/mainInterface/GeosxState.hpp
  src/coreComponents/physicsSolvers/SolverBase.cpp
  src/coreComponents/physicsSolvers/SolverBase.hpp
Labels: flag: ready to be merged, flag: ready for review

#2726 Github Actions - Make CUDA jobs check and PR draft check dynamic
  .github/workflows/ci_tests.yml
Labels: type: testing, flag: ready to be merged, flag: ready for review

#2734 Fixed bug in VTKUtilities related to sortedArrayManipulation::find
  src/coreComponents/mesh/generators/VTKUtilities.cpp
Labels: type: bug, flag: ready to be merged, flag: ready for review

#2736 Fix for issue #2634 "Single Phase Well Prints Incorrect Mass Flow Rate"
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp
Labels: type: bug, flag: ready to be merged, flag: ready for review

#2714 Minor docs updates
  src/docs/sphinx/advancedExamples/validationStudies/thermoPoromechanics/thermalConsolidation/Example.rst
  src/docs/sphinx/basicExamples/co2Injection/Example.rst
  src/docs/sphinx/basicExamples/multiphaseFlowWithWells/Example.rst
Labels: type: documentation, flag: ready to be merged, flag: ready for review

#2730 rewrite wave propagation damping kernels
  src/coreComponents/physicsSolvers/wavePropagation/AcousticFirstOrderWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticFirstOrderWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticFirstOrderWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticFirstOrderWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEMKernel.hpp
Labels: type: bug, flag: ready to be merged, flag: requires rebaseline

#2722 support high order hex Q2 output in VTK
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
Labels: type: feature, flag: ready to be merged, type: visualization

#2705 More fixes in SurfaceGenerator to allow for intersecting cracks
  src/coreComponents/physicsSolvers/surfaceGeneration/SurfaceGenerator.cpp
Labels: flag: ready to be merged

#2717 check build against TPLs #228
  .github/workflows/ci_tests.yml
Labels: flag: ready to be merged, flag: ready for review, flag: TPL(s) build check

#2737 Output well rates to a simple csv file (in addition to the already implemented screen output)
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellSolverBase.hpp
Labels: type: feature, flag: ready to be merged, flag: ready for review

#2751 Fix EDFM cases from multiphaseFlowFractures
  inputFiles/multiphaseFlowFractures/deadoil_3ph_corey_2d_edfm.xml
  inputFiles/multiphaseFlowFractures/deadoil_3ph_corey_2d_impermeableFault.xml
  inputFiles/multiphaseFlowFractures/deadoil_3ph_corey_edfm_1d.xml
  inputFiles/multiphaseFlowFractures/deadoil_3ph_corey_pedfm_impermeableFault_smoke.xml
Labels: type: testing, flag: ready to be merged, flag: ready for review

#2758 damping faces/elements consistency
  src/coreComponents/physicsSolvers/wavePropagation/AcousticFirstOrderWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticVTIWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticVTIWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticFirstOrderWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEMKernel.hpp
Labels: type: cleanup / refactor, flag: ready to be merged

#2552 Adding an error when input temperature / pressure is out of PVT tables range
  src/coreComponents/common/CMakeLists.txt
  src/coreComponents/common/Logger.cpp
  src/coreComponents/common/Logger.hpp
  src/coreComponents/common/PhysicsConstants.hpp
  src/coreComponents/common/Units.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/CO2BrineFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/CO2BrineFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/BrineEnthalpy.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/BrineEnthalpy.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2EOSSolver.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Enthalpy.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Enthalpy.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineDensity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineViscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineViscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/FenghourCO2Viscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/FenghourCO2Viscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/FlashModelBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/NoOpPVTFunction.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PVTFunctionBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PVTFunctionHelpers.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineDensity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineViscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineViscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PureWaterProperties.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/SpanWagnerCO2Density.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/SpanWagnerCO2Density.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/WaterDensity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/WaterDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidBase.cpp
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/blackOil/BlackOilFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/blackOil/BlackOilFluidBase.cpp
  src/coreComponents/constitutive/fluid/multifluid/blackOil/BlackOilFluidBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/blackOil/DeadOilFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/reactive/ReactiveBrineFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/reactive/ReactiveBrineFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/reactive/chemicalReactions/KineticReactions.cpp
  src/coreComponents/fieldSpecification/AquiferBoundaryCondition.cpp
  src/coreComponents/functions/TableFunction.cpp
  src/coreComponents/functions/TableFunction.hpp
  src/coreComponents/functions/unitTests/testFunctions.cpp
  src/coreComponents/math/CMakeLists.txt
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/ThermalCompositionalMultiphaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellControls.cpp
  src/coreComponents/unitTests/constitutiveTests/testCapillaryPressure.cpp
  src/coreComponents/unitTests/constitutiveTests/testMultiFluid.cpp
  src/docs/doxygen/GeosxConfig.hpp
Labels: flag: ready to be merged

#2759 Solve reappearing compilation issue on PPC machines with NVCC due to FMT bug
  src/coreComponents/common/Format.hpp
  src/coreComponents/dataRepository/DataContext.hpp
Labels: type: bug, flag: ready to be merged

#2718 prevent `SIGFPE` in `vtk`
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
Labels: type: bug, flag: ready to be merged

#2780 Reenabling sphinx imgmath
  src/conf.py
Labels: type: bug, type: documentation, flag: ready to be merged

#2763 Tune the hydrofrac example so that it at least runs
  inputFiles/hydraulicFracturing/heterogeneousInSitu_base.xml
Labels: type: documentation, flag: ready to be merged, Theme - HF

#2695 Refactor fluid unit tests
  src/coreComponents/constitutive/unitTests/TestFluidUtilities.hpp
  src/coreComponents/constitutive/unitTests/testCompositionalProperties.cpp
  src/coreComponents/constitutive/unitTests/testCubicEOS.cpp
Labels: type: cleanup / refactor, flag: ready to be merged, flag: ready for review

#2661 Compositional tidy up
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.cpp
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidConstants.hpp
  src/coreComponents/constitutive/fluid/multifluid/PVTDriver.cpp
  src/coreComponents/constitutive/fluid/multifluid/PVTDriver.hpp
  src/coreComponents/constitutive/fluid/multifluid/blackOil/BlackOilFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/CompositionalProperties.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/CompositionalProperties.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/CubicEOSPhaseModel.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/NegativeTwoPhaseFlash.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/RachfordRice.hpp
  src/coreComponents/constitutive/fluid/multifluid/reactive/ReactiveFluidDriver.hpp
  src/coreComponents/constitutive/fluid/multifluid/reactive/chemicalReactions/EquilibriumReactions.hpp
  src/coreComponents/constitutive/fluid/multifluid/reactive/chemicalReactions/KineticReactions.hpp
Labels: type: cleanup / refactor, flag: ready to be merged, flag: ready for review

#2692 Add gcc compiler to nightly tests
  .gitlab-ci.yml
Labels: type: testing, flag: ready to be merged, flag: ready for review

#2762 Add a few solver options plus some useful output for hydrofrac solver
  src/coreComponents/constitutive/contact/ContactBase.cpp
  src/coreComponents/physicsSolvers/NonlinearSolverParameters.cpp
  src/coreComponents/physicsSolvers/NonlinearSolverParameters.hpp
  src/coreComponents/physicsSolvers/SolverBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/ThermalCompositionalMultiphaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/ThermalSinglePhaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/proppantTransport/ProppantTransport.cpp
  src/coreComponents/physicsSolvers/fluidFlow/proppantTransport/ProppantTransportKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWellKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWellKernels.hpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolverKernels.hpp
Labels: flag: ready to be merged, flag: requires rebaseline, Theme - HF

#2735 Merge SolidMechanicsStateReset into PoromechanicsInitialization to simplify users life
  inputFiles/poromechanics/PoroElastic_staircase_co2_3d.xml
  inputFiles/poromechanics/PoroElastic_staircase_singlephase_3d.xml
  inputFiles/thermoPoromechanics/ThermoPoroElastic_staircase_co2_smoke.xml
  src/coreComponents/dataRepository/Group.hpp
  src/coreComponents/physicsSolvers/multiphysics/PoromechanicsInitialization.cpp
  src/coreComponents/physicsSolvers/multiphysics/PoromechanicsInitialization.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsStateReset.hpp
Labels: flag: ready to be merged
