Repository GEOS-DEV/GEOS, pull requests merged in 2023-07, with the labels that each got.

#2554 Sequential flow-mechanics follow-up, iteration 2
  inputFiles/poromechanics/PoroElastic_Mandel_base.xml
  inputFiles/poromechanics/PoroElastic_Mandel_benchmark.xml
  inputFiles/poromechanics/PoroElastic_Mandel_benchmark_fim.xml
  inputFiles/poromechanics/PoroElastic_Mandel_benchmark_sequential.xml
  inputFiles/poromechanics/PoroElastic_Mandel_smoke_fim.xml
  inputFiles/poromechanics/PoroElastic_Mandel_smoke_sequential.xml
  inputFiles/poromechanics/PoroElastic_deadoil_3ph_baker_2d_base.xml
  inputFiles/poromechanics/PoroElastic_deadoil_3ph_baker_2d_fim.xml
  inputFiles/poromechanics/PoroElastic_deadoil_3ph_baker_2d_sequential.xml
  inputFiles/thermoPoromechanics/ThermoPoroElastic_consolidation_benchmark_sequential.xml
  src/coreComponents/constitutive/capillaryPressure/JFunctionCapillaryPressure.cpp
  src/coreComponents/constitutive/solid/CompressibleSolid.hpp
  src/coreComponents/constitutive/solid/CoupledSolid.hpp
  src/coreComponents/constitutive/solid/CoupledSolidBase.hpp
  src/coreComponents/constitutive/solid/PorousSolid.hpp
  src/coreComponents/constitutive/solid/porosity/BiotPorosity.cpp
  src/coreComponents/constitutive/solid/porosity/BiotPorosity.hpp
  src/coreComponents/constitutive/solid/porosity/PorosityBase.cpp
  src/coreComponents/constitutive/solid/porosity/PorosityBase.hpp
  src/coreComponents/constitutive/solid/porosity/PorosityFields.hpp
  src/coreComponents/constitutive/solid/porosity/PressurePorosity.hpp
  src/coreComponents/constitutive/solid/porosity/ProppantPorosity.hpp
  src/coreComponents/constitutive/thermalConductivity/MultiPhaseVolumeWeightedThermalConductivity.cpp
  src/coreComponents/events/EventBase.hpp
  src/coreComponents/events/PeriodicEvent.cpp
  src/coreComponents/finiteElement/elementFormulations/H1_Hexahedron_Lagrange1_GaussLegendre2.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_Pyramid_Lagrange1_Gauss5.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_Tetrahedron_Lagrange1_Gauss1.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_Wedge_Lagrange1_Gauss6.hpp
  src/coreComponents/mesh/CMakeLists.txt
  src/coreComponents/mesh/generators/VTKUtilities.cpp
  src/coreComponents/mesh/utilities/AverageOverQuadraturePointsKernel.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBaseFields.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBaseFields.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.hpp
  src/coreComponents/physicsSolvers/multiphysics/poromechanicsKernels/PoromechanicsBase.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.hpp
Labels: type: bug, flag: ready to be merged, flag: requires rebaseline

#2562 fix a few typos and `404`s
  src/coreComponents/finiteElement/kernelInterface/kernelInterface.rst
  src/coreComponents/linearAlgebra/docs/DofManager.rst
  src/coreComponents/physicsSolvers/solidMechanics/docs/SolidMechanics.rst
Labels: type: documentation

#2583 Remove erroneous `template` from non-template member function calls.
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoirAndWells.cpp
Labels: type: bug, flag: ready to be merged

#2484 Implement negative two-phase flash
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/NegativeTwoPhaseFlash.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/RachfordRice.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/RachfordRice.hpp
  src/coreComponents/constitutive/unitTests/CMakeLists.txt
  src/coreComponents/constitutive/unitTests/testNegativeTwoPhaseFlash.cpp
  src/coreComponents/constitutive/unitTests/testRachfordRice.cpp
Labels: type: feature, flag: ready to be merged, flag: ready for review

#2563 Update .gitlab-ci.yml host-config paths, CMake version to 3.23.1
  .gitlab-ci.yml
Labels: type: testing, flag: ready for review

#2575 Change GEOSX to GEOS in README
  README.md
Labels: type: documentation, flag: ready for review

#2576 fix two tutorial examples
  src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/mandel/mandelFigure.py
  src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/sneddon/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/sneddon/sneddonFigure.py
Labels: type: documentation, flag: ready for review

#2596 Update tutorial example for CO2 injection
  inputFiles/compositionalMultiphaseWell/simpleCo2InjTutorial_smoke.xml
Labels: type: documentation, flag: ready for review

#2588 Add reordering steps in Box definition
  src/coreComponents/mesh/simpleGeometricObjects/Box.cpp
Labels: type: feature
