Repository GEOS-DEV/GEOS, pull requests merged in 2024-02, with the labels that each got.

#2907 Add HYPRE warning
  src/coreComponents/mainInterface/version.cpp
Labels: ci: ready to be merged, flag: no rebaseline

#2935 Print Hypre preconditioner setup error
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreInterface.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HyprePreconditioner.cpp
Labels: ci: ready to be merged, ci: run integrated tests, flag: no rebaseline

#2978 Change code coverage CI VM to 4 core - 16 GB
  .github/workflows/ci_tests.yml
Labels: ci: ready to be merged

#2873 use streak.llnl.gov as runner for GHA
  .github/workflows/build_and_test.yml
  .github/workflows/ci_tests.yml
  scripts/buildOrTest.py
  scripts/ci_build_and_test_in_container.sh
  src/coreComponents/constitutive/solid/SolidBase.hpp
Labels: ci: ready to be merged, ci: run integrated tests

#2977 Adding Sherlock GPU to CI tests
  .devcontainer/devcontainer.json
  .github/workflows/ci_tests.yml
  host-configs/Stanford/sherlock-gcc10-ompi4.1.2-openblas0.3.10-cuda11.7.1-sm70.cmake
  host-configs/Stanford/sherlock-modules.sh
  scripts/ci_build_and_test_in_container.sh
Labels: ci: ready to be merged, flag: ready for review, flag: requires updated TPL(s), ci: run integrated tests, flag: no rebaseline
