Repository GEOS-DEV/GEOS, pull requests merged in 2024-10, with the labels that each got.

#3149 feat: Log refactor - Output PVT
  .integrated_tests.yaml
  BASELINE_NOTES.md
  src/coreComponents/common/format/table/TableData.cpp
  src/coreComponents/common/format/table/TableData.hpp
  src/coreComponents/common/format/table/TableFormatter.cpp
  src/coreComponents/common/format/table/TableFormatter.hpp
  src/coreComponents/common/format/table/TableLayout.hpp
  src/coreComponents/common/format/table/unitTests/testTable.cpp
  src/coreComponents/constitutive/ConstitutiveBase.cpp
  src/coreComponents/constitutive/ConstitutiveBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/CO2BrineFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/CO2BrineFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/PhaseModel.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/BrineEnthalpy.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/BrineEnthalpy.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Enthalpy.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Enthalpy.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineDensity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineViscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineViscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/FenghourCO2Viscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/FenghourCO2Viscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/FlashModelBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/NoOpPVTFunction.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PVTFunctionBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineDensity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineViscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineViscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/SpanWagnerCO2Density.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/SpanWagnerCO2Density.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/WaterDensity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/WaterDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/reactive/ReactiveBrineFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/reactive/ReactiveBrineFluid.hpp
  src/coreComponents/functions/TableFunction.cpp
  src/coreComponents/functions/TableFunction.hpp
  src/coreComponents/schema/schema.xsd
  src/coreComponents/unitTests/constitutiveTests/testCO2BrinePVTModels.cpp
  src/coreComponents/unitTests/constitutiveTests/testCO2SpycherPruessModels.cpp
  src/docs/sphinx/developerGuide/Contributing/Sphinx.rst
  src/docs/sphinx/developerGuide/Contributing/githubtestsummary.png
  src/docs/sphinx/developerGuide/Contributing/readthedocsbuildsummary.png
Labels: ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests, ci: run code coverage

#3364 feat: Separate mass and volume residuals for output in compositional flow solver
  .integrated_tests.yaml
  BASELINE_NOTES.md
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/ThermalCompositionalMultiphaseBaseKernels.hpp
Labels: ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests, ci: run code coverage

#3378 refactor: log levels solvers
  src/coreComponents/dataRepository/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/SolverBase.cpp
  src/coreComponents/physicsSolvers/SolverBase.hpp
  src/coreComponents/physicsSolvers/contact/CMakeLists.txt
  src/coreComponents/physicsSolvers/contact/ContactSolverBase.cpp
  src/coreComponents/physicsSolvers/contact/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsAugmentedLagrangianContact.cpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CMakeLists.txt
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/fluidFlow/ReactiveCompositionalMultiphaseOBL.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellControls.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellSolverBase.cpp
  src/coreComponents/physicsSolvers/multiphysics/CMakeLists.txt
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/FlowProppantTransportSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/PoromechanicsInitialization.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp
  src/coreComponents/physicsSolvers/solidMechanics/CMakeLists.txt
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsStateReset.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsStatistics.cpp
  src/coreComponents/physicsSolvers/surfaceGeneration/CMakeLists.txt
  src/coreComponents/physicsSolvers/surfaceGeneration/EmbeddedSurfaceGenerator.cpp
  src/coreComponents/physicsSolvers/surfaceGeneration/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/surfaceGeneration/SurfaceGenerator.cpp
  src/coreComponents/schema/schema.xsd
Labels: flag: ready for review

#3358 fix: Remove reference to fem space in kernelBase.
  src/coreComponents/finiteElement/elementFormulations/ConformingVirtualElementOrder1.hpp
  src/coreComponents/finiteElement/elementFormulations/FiniteElementBase.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_Hexahedron_Lagrange1_GaussLegendre2.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_Pyramid_Lagrange1_Gauss5.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_QuadrilateralFace_Lagrange1_GaussLegendre2.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_Tetrahedron_Lagrange1_Gauss1.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_TriangleFace_Lagrange1_Gauss1.hpp
  src/coreComponents/finiteElement/elementFormulations/H1_Wedge_Lagrange1_Gauss6.hpp
  src/coreComponents/finiteElement/elementFormulations/Qk_Hexahedron_Lagrange_GaussLobatto.hpp
  src/coreComponents/finiteElement/kernelInterface/KernelBase.hpp
Labels: ci: run CUDA builds, ci: run integrated tests, ci: run code coverage

#3373 fix: add proper labels when registering strain wrapper
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
Labels: ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#2610 feat: Add freeOnDevice calls on Wave Propagation Solvers
  src/coreComponents/physicsSolvers/wavePropagation/sem/acoustic/firstOrderEqn/isotropic/AcousticFirstOrderWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/acoustic/secondOrderEqn/anisotropic/AcousticVTIWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/acoustic/secondOrderEqn/isotropic/AcousticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/elastic/firstOrderEqn/isotropic/ElasticFirstOrderWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/elastic/secondOrderEqn/isotropic/ElasticWaveEquationSEM.cpp
Labels: type: feature, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, ci: run code coverage

#3387 fix: testLifoStorage CI failures
  src/coreComponents/common/unitTests/testLifoStorage.cpp
Labels: type: bug, ci: run CUDA builds, ci: run integrated tests, ci: run code coverage

#3230 refactor: Log level documentation on SolverBase and children
  src/coreComponents/common/CMakeLists.txt
  src/coreComponents/common/logger/Logger.hpp
  src/coreComponents/dataRepository/CMakeLists.txt
  src/coreComponents/dataRepository/Group.cpp
  src/coreComponents/dataRepository/Group.hpp
  src/coreComponents/dataRepository/LogLevelsInfo.hpp
  src/coreComponents/dataRepository/LogLevelsRegistry.cpp
  src/coreComponents/dataRepository/LogLevelsRegistry.hpp
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/SolverBase.cpp
  src/coreComponents/physicsSolvers/SolverBase.hpp
  src/coreComponents/physicsSolvers/contact/CMakeLists.txt
  src/coreComponents/physicsSolvers/contact/ContactSolverBase.cpp
  src/coreComponents/physicsSolvers/contact/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsAugmentedLagrangianContact.cpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CMakeLists.txt
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/fluidFlow/ReactiveCompositionalMultiphaseOBL.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellControls.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellSolverBase.cpp
  src/coreComponents/physicsSolvers/multiphysics/CMakeLists.txt
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/FlowProppantTransportSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.hpp
  src/coreComponents/physicsSolvers/multiphysics/PoromechanicsInitialization.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp
  src/coreComponents/physicsSolvers/solidMechanics/CMakeLists.txt
  src/coreComponents/physicsSolvers/solidMechanics/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsStateReset.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsStatistics.cpp
  src/coreComponents/physicsSolvers/surfaceGeneration/CMakeLists.txt
  src/coreComponents/physicsSolvers/surfaceGeneration/EmbeddedSurfaceGenerator.cpp
  src/coreComponents/physicsSolvers/surfaceGeneration/LogLevelsInfo.hpp
  src/coreComponents/physicsSolvers/surfaceGeneration/SurfaceGenerator.cpp
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
Labels: type: feature, ci: run CUDA builds, flag: ready for review, ci: run integrated tests

#3390 fix: clarify well messages and fix copy-paste typo
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellControls.cpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.hpp
Labels: type: bug, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3356 feat: Enable reservoir+wells+contact mechanics
  .integrated_tests.yaml
  BASELINE_NOTES.md
  inputFiles/poromechanicsFractures/singlePhasePoromechanics_FaultModel_well_base.xml
  inputFiles/poromechanicsFractures/singlePhasePoromechanics_FaultModel_well_fim_smoke.xml
  inputFiles/poromechanicsFractures/singlePhasePoromechanics_FaultModel_well_seq_smoke.xml
  src/coreComponents/mesh/generators/WellGeneratorBase.cpp
  src/coreComponents/physicsSolvers/SolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWellKernels.hpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/PoromechanicsInitialization.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp
Labels: type: feature, ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests, ci: run code coverage

#3402 fix: Fix misuse of CommID
  src/coreComponents/mesh/mpiCommunications/CommID.hpp
  src/coreComponents/mesh/mpiCommunications/CommunicationTools.cpp
  src/coreComponents/mesh/mpiCommunications/MPI_iCommData.cpp
  src/coreComponents/mesh/mpiCommunications/MPI_iCommData.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsMPM.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsMPM.hpp
  src/coreComponents/physicsSolvers/surfaceGeneration/EmbeddedSurfacesParallelSynchronization.cpp
  src/coreComponents/physicsSolvers/surfaceGeneration/ParallelTopologyChange.cpp
Labels: ci: run CUDA builds, ci: run integrated tests, ci: run code coverage

#3403 fix: Regex validation bugfix & unit test
  src/coreComponents/codingUtilities/EnumStrings.hpp
  src/coreComponents/dataRepository/unitTests/testXmlWrapper.cpp
  src/coreComponents/dataRepository/xmlWrapper.cpp
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
Labels: ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3409 fix: Crashes in some wave propagation cases after some varaibles are free'd on device
  src/coreComponents/physicsSolvers/wavePropagation/sem/acoustic/firstOrderEqn/isotropic/AcousticFirstOrderWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/acoustic/secondOrderEqn/anisotropic/AcousticVTIWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/acoustic/secondOrderEqn/isotropic/AcousticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/elastic/firstOrderEqn/isotropic/ElasticFirstOrderWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/elastic/secondOrderEqn/isotropic/ElasticWaveEquationSEM.cpp
Labels: type: bug, ci: run CUDA builds, ci: run integrated tests, ci: run code coverage

#3399 fix: Bug fix for residual computation
  src/coreComponents/physicsSolvers/fluidFlow/ThermalCompositionalMultiphaseBaseKernels.hpp
Labels: type: bug, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3386 refactor: cleanup setMGRStrategy a bit
  src/coreComponents/physicsSolvers/contact/SolidMechanicsEmbeddedFractures.cpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsEmbeddedFractures.hpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.cpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.hpp
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.hpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEmbeddedFractures.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEmbeddedFractures.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoirAndWells.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
Labels: type: cleanup / refactor, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, flag: no rebaseline, ci: run code coverage
