Repository GEOS-DEV/GEOS, pull requests merged in 2024-08, with the labels that each got.

#3269 fix: testUnits failure on MacOS
  src/coreComponents/common/Units.hpp
Labels: ci: run CUDA builds, ci: run integrated tests

#3091 feat: Transmissibility output
  inputFiles/compositionalMultiphaseFlow/deadoil_3ph_staircase_3d_transmi_output.xml
  src/coreComponents/common/Units.hpp
  src/coreComponents/common/logger/Logger.hpp
  src/coreComponents/dataRepository/Group.hpp
  src/coreComponents/fileIO/timeHistory/PackCollection.cpp
  src/coreComponents/finiteVolume/docs/StencilModel.plantuml
  src/coreComponents/mainInterface/ProblemManager.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CMakeLists.txt
  src/coreComponents/physicsSolvers/fluidFlow/StencilDataCollection.cpp
  src/coreComponents/physicsSolvers/fluidFlow/StencilDataCollection.hpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.hpp
  src/coreComponents/schema/docs/CellToCellDataCollection.rst
  src/coreComponents/schema/docs/CellToCellDataCollection_other.rst
  src/coreComponents/schema/docs/Tasks.rst
  src/coreComponents/schema/docs/Tasks_other.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/fluidFlowTests/CMakeLists.txt
  src/coreComponents/unitTests/fluidFlowTests/testTransmissibility.cpp
  src/docs/sphinx/CompleteXMLSchema.rst
Labels: type: feature, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline

#3270 fix: fix linking error on mac
  src/coreComponents/common/Units.cpp
  src/coreComponents/common/Units.hpp
Labels: ci: run CUDA builds, ci: run integrated tests

#3265 fix: Fix cibadge in Readme.
  README.md
Labels: ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline

#3278 chore: Changing GEOSX to GEOS in external mesh import
  .integrated_tests.yaml
  BASELINE_NOTES.md
  inputFiles/compositionalMultiphaseWell/benchmarks/Class09Pb3/class09_pb3_benchmark.xml
  inputFiles/compositionalMultiphaseWell/benchmarks/Class09Pb3/class09_pb3_benchmark_mc.xml
  inputFiles/compositionalMultiphaseWell/benchmarks/Class09Pb3/class09_pb3_benchmark_mct.xml
  inputFiles/compositionalMultiphaseWell/benchmarks/Egg/deadOilEggVTK_benchmark.xml
  inputFiles/compositionalMultiphaseWell/benchmarks/Egg/deadOilEgg_benchmark.xml
  inputFiles/compositionalMultiphaseWell/staircase_co2_wells_hybrid_3d.xml
  inputFiles/poromechanics/PoroElastic_hybridHexPrism_co2_base.xml
  inputFiles/poromechanics/nonlinearAcceleration/smallEggModel/smallEggModel.xml
  inputFiles/poromechanicsFractures/PoroElastic_efem-edfm_eggModel_large.xml
  inputFiles/poromechanicsFractures/PoroElastic_efem-edfm_eggModel_small.xml
  inputFiles/poromechanicsFractures/verticalFault_ExternalMesh.vtm
  inputFiles/singlePhaseFlow/incompressible_pebi3d.xml
  inputFiles/thermoPoromechanicsFractures/ThermoPoroElastic_efem-edfm_eggModel_small.xml
  src/coreComponents/mesh/generators/ExternalMeshGeneratorBase.cpp
  src/coreComponents/mesh/generators/ExternalMeshGeneratorBase.hpp
  src/coreComponents/mesh/generators/MeshGeneratorBase.hpp
  src/coreComponents/schema/docs/VTKMesh.rst
Labels: type: cleanup / refactor, ci: run CUDA builds, flag: ready for review, flag: requires rebaseline, changes XML input, ci: run integrated tests

#3249 docs: stress_and_pressure_initialization
  .integrated_tests.yaml
  BASELINE_NOTES.md
  inputFiles/initialization/gravityInducedStress_initialization_base.xml
  inputFiles/initialization/gravityInducedStress_initialization_benchmark.xml
  inputFiles/initialization/gravityInducedStress_initialization_smoke.xml
  inputFiles/initialization/initialization.ats
  inputFiles/initialization/userTables/effectiveSigma_xx.csv
  inputFiles/initialization/userTables/effectiveSigma_yy.csv
  inputFiles/initialization/userTables/effectiveSigma_zz.csv
  inputFiles/initialization/userTables/porePressure.csv
  inputFiles/initialization/userTables/x.csv
  inputFiles/initialization/userTables/y.csv
  inputFiles/initialization/userTables/z.csv
  inputFiles/initialization/userdefinedStress_initialization_base.xml
  inputFiles/initialization/userdefinedStress_initialization_benchmark.xml
  inputFiles/initialization/userdefinedStress_initialization_smoke.xml
  src/coreComponents/physicsSolvers/multiphysics/docs/Initialization.rst
  src/coreComponents/physicsSolvers/multiphysics/docs/gravityInducedStressInitialization/Example.rst
  src/coreComponents/physicsSolvers/multiphysics/docs/gravityInducedStressInitialization/effective_SZZ.png
  src/coreComponents/physicsSolvers/multiphysics/docs/gravityInducedStressInitialization/gravityInitializationFigure.py
  src/coreComponents/physicsSolvers/multiphysics/docs/gravityInducedStressInitialization/mesh.png
  src/coreComponents/physicsSolvers/multiphysics/docs/gravityInducedStressInitialization/pressure_field.png
  src/coreComponents/physicsSolvers/multiphysics/docs/gravityInducedStressInitialization/simulation_result_0.csv
  src/coreComponents/physicsSolvers/multiphysics/docs/gravityInducedStressInitialization/sketch_of_problem.png
  src/coreComponents/physicsSolvers/multiphysics/docs/userTableStressInitialization/Example.rst
  src/coreComponents/physicsSolvers/multiphysics/docs/userTableStressInitialization/generateTable.py
  src/coreComponents/physicsSolvers/multiphysics/docs/userTableStressInitialization/pressure_field.png
  src/coreComponents/physicsSolvers/multiphysics/docs/userTableStressInitialization/simulation_result_0.csv
  src/coreComponents/physicsSolvers/multiphysics/docs/userTableStressInitialization/stressZZ_field.png
  src/coreComponents/physicsSolvers/multiphysics/docs/userTableStressInitialization/tableInitializationFigure.py
  src/docs/sphinx/basicExamples/Index.rst
  src/docs/sphinx/userGuide/Index.rst
Labels: type: documentation, ci: run CUDA builds, flag: ready for review, flag: requires rebaseline, ci: run integrated tests

#3250 chore: add a few comments and small code fixes in addTransmissibilityCouplingPattern for poromechanics with conforming fractures
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp
Labels: type: bug, type: cleanup / refactor, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, flag: no rebaseline

#3284 docs: fix python script for a tutorial example
  src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/faultVerification/faultVerificationFigure.py
Labels: type: documentation, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, flag: no rebaseline

#3283 refactor: Reuse computeSinglePhaseFlux
  .integrated_tests.yaml
  BASELINE_NOTES.md
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVMKernels.hpp
Labels: type: cleanup / refactor, ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests

#3234 refactor: Use matrix-matrix interface in LAPACK solve
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/NegativeTwoPhaseFlash.hpp
Labels: type: cleanup / refactor, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, flag: no rebaseline

#3206 feat: Use stability test in flash
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/docs/CompositionalMultiphaseFluid.rst
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/KValueInitialization.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/NegativeTwoPhaseFlash.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/StabilityTest.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/CriticalVolume.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/CriticalVolume.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/EquationOfState.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/LohrenzBrayClarkViscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/LohrenzBrayClarkViscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/ModelParameters.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/NegativeTwoPhaseFlashModel.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/NegativeTwoPhaseFlashModel.hpp
  src/coreComponents/constitutive/unitTests/testLohrenzBrayClarkViscosity.cpp
  src/coreComponents/constitutive/unitTests/testStabilityTest2Comp.cpp
  src/coreComponents/constitutive/unitTests/testStabilityTest9Comp.cpp
  src/coreComponents/schema/docs/CompositionalTwoPhaseFluid.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/unitTests/constitutiveTests/CMakeLists.txt
  src/coreComponents/unitTests/constitutiveTests/testMultiFluidCompositionalMultiphase.cpp
Labels: ci: run CUDA builds, flag: ready for review, ci: run integrated tests, flag: no rebaseline

#3287 feat: Add kernel callable dense LA solvers for small systems.
  src/coreComponents/denseLinearAlgebra/CMakeLists.txt
  src/coreComponents/denseLinearAlgebra/denseLASolvers.hpp
  src/coreComponents/denseLinearAlgebra/unitTests/CMakeLists.txt
  src/coreComponents/denseLinearAlgebra/unitTests/testDenseLASolvers.cpp
  src/coreComponents/denseLinearAlgebra/unitTests/testUtils.hpp
Labels: ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline

#3303 feat: add log at the end of the timestep with substeps info.
  src/coreComponents/physicsSolvers/SolverBase.cpp
  src/coreComponents/physicsSolvers/SolverBase.hpp
Labels: ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline

#3307 fix: add install commands to component libraries
  src/coreComponents/codingUtilities/CMakeLists.txt
  src/coreComponents/common/CMakeLists.txt
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutiveDrivers/CMakeLists.txt
  src/coreComponents/dataRepository/CMakeLists.txt
  src/coreComponents/denseLinearAlgebra/CMakeLists.txt
  src/coreComponents/discretizationMethods/CMakeLists.txt
  src/coreComponents/events/CMakeLists.txt
  src/coreComponents/fieldSpecification/CMakeLists.txt
  src/coreComponents/fileIO/CMakeLists.txt
  src/coreComponents/finiteElement/CMakeLists.txt
  src/coreComponents/finiteVolume/CMakeLists.txt
  src/coreComponents/functions/CMakeLists.txt
  src/coreComponents/linearAlgebra/CMakeLists.txt
  src/coreComponents/mainInterface/CMakeLists.txt
  src/coreComponents/math/CMakeLists.txt
  src/coreComponents/mesh/CMakeLists.txt
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/schema/CMakeLists.txt
Labels: ci: run CUDA builds, ci: run integrated tests

#3237 feat: Add immiscible water flash model
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/NegativeTwoPhaseFlash.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/ComponentProperties.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/ImmiscibleWaterFlashModel.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/ImmiscibleWaterFlashModel.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/ImmiscibleWaterParameters.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/ImmiscibleWaterParameters.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/ModelParameters.hpp
  src/coreComponents/constitutive/unitTests/CMakeLists.txt
  src/coreComponents/constitutive/unitTests/TestFluid.hpp
  src/coreComponents/constitutive/unitTests/testImmiscibleWaterFlashModel.cpp
Labels: type: feature, ci: run CUDA builds, flag: ready for review, ci: run integrated tests
