Repository GEOS-DEV/GEOS, pull requests merged in 2024-12, with the labels that each got.

#3381 refactor: Clean up ghost unpacking
  .integrated_tests.yaml
  BASELINE_NOTES.md
  host-configs/apple/macOS_base.cmake
  inputFiles/surfaceGeneration/cube_8.vtu
  inputFiles/surfaceGeneration/cube_8.xml
  src/coreComponents/dataRepository/BufferOps_inline.hpp
  src/coreComponents/mesh/CellElementSubRegion.cpp
  src/coreComponents/mesh/EdgeManager.cpp
  src/coreComponents/mesh/ElementRegionManager.cpp
  src/coreComponents/mesh/ElementRegionManager.hpp
  src/coreComponents/mesh/FaceElementSubRegion.cpp
  src/coreComponents/mesh/FaceElementSubRegion.hpp
  src/coreComponents/mesh/FaceManager.cpp
  src/coreComponents/mesh/NodeManager.cpp
  src/coreComponents/mesh/NodeManager.hpp
  src/coreComponents/mesh/ObjectManagerBase.cpp
  src/coreComponents/mesh/ObjectManagerBase.hpp
  src/coreComponents/mesh/mpiCommunications/CommunicationTools.cpp
  src/coreComponents/mesh/mpiCommunications/CommunicationTools.hpp
  src/coreComponents/mesh/mpiCommunications/MPI_iCommData.cpp
  src/coreComponents/mesh/mpiCommunications/NeighborCommunicator.cpp
  src/coreComponents/mesh/mpiCommunications/NeighborCommunicator.hpp
  src/coreComponents/physicsSolvers/surfaceGeneration/CMakeLists.txt
  src/coreComponents/physicsSolvers/surfaceGeneration/ParallelTopologyChange.cpp
  src/coreComponents/physicsSolvers/surfaceGeneration/ParallelTopologyChange.hpp
  src/coreComponents/physicsSolvers/surfaceGeneration/ParallelTopologyChangeNoFixup.cpp
  src/coreComponents/physicsSolvers/surfaceGeneration/SurfaceGenerator.cpp
  src/coreComponents/schema/schema.xsd.other
Labels: ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests, ci: run code coverage

#3469 docs: add short description for adaptive tolerance option in linear solver
  src/coreComponents/linearAlgebra/docs/DofManager.rst
  src/coreComponents/linearAlgebra/docs/LinearSolvers.rst
Labels: type: documentation, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3447 refactor: compositional includes cleanup
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/CompositionalMultiphaseHybridFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/DiffusionDispersionFluxComputeKernel.hpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/SolutionScalingKernel.hpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/singlePhase/SinglePhaseHybridFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/kernels/CompositionalMultiphaseWellKernels.hpp
Labels: type: cleanup / refactor, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3393 fix: detangle and unify flow initialization, fix netToGross bug
  .integrated_tests.yaml
  BASELINE_NOTES.md
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.hpp
Labels: type: bug, type: cleanup / refactor, ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests, ci: run code coverage

#2652 fix: add early check for invalid `toMetricPrefixString` input
  src/coreComponents/common/format/StringUtilities.cpp
Labels: type: bug, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3467 fix: make new gravity treatment from #3337 an option
  .integrated_tests.yaml
  BASELINE_NOTES.md
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/C1PPUPhaseFlux.hpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/CFLKernel.cpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/CFLKernel.hpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/DissipationFluxComputeKernel.hpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/FluxComputeKernel.hpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/FluxComputeKernelBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/IHUPhaseFlux.hpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/PPUPhaseFlux.hpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/PotGrad.hpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/StabilizedFluxComputeKernel.hpp
  src/coreComponents/physicsSolvers/fluidFlow/kernels/compositional/ThermalFluxComputeKernel.hpp
Labels: type: feature, ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests, ci: run code coverage

#3480 feat: IO timers
  .integrated_tests.yaml
  BASELINE_NOTES.md
  src/coreComponents/fileIO/Outputs/BlueprintOutput.cpp
  src/coreComponents/fileIO/Outputs/BlueprintOutput.hpp
  src/coreComponents/fileIO/Outputs/ChomboIO.cpp
  src/coreComponents/fileIO/Outputs/ChomboIO.hpp
  src/coreComponents/fileIO/Outputs/OutputBase.cpp
  src/coreComponents/fileIO/Outputs/OutputBase.hpp
  src/coreComponents/fileIO/Outputs/PythonOutput.cpp
  src/coreComponents/fileIO/Outputs/PythonOutput.hpp
  src/coreComponents/fileIO/Outputs/RestartOutput.cpp
  src/coreComponents/fileIO/Outputs/RestartOutput.hpp
  src/coreComponents/fileIO/Outputs/SiloOutput.cpp
  src/coreComponents/fileIO/Outputs/SiloOutput.hpp
  src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp
  src/coreComponents/fileIO/Outputs/TimeHistoryOutput.hpp
  src/coreComponents/fileIO/Outputs/VTKOutput.cpp
  src/coreComponents/fileIO/Outputs/VTKOutput.hpp
Labels: ci: run CUDA builds, flag: ready for review, flag: requires rebaseline, ci: run integrated tests, ci: run code coverage

#3488 refactor: remove assemblyLaunch duplicates in poromechanics solvers
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.hpp
  src/coreComponents/physicsSolvers/multiphysics/PoromechanicsSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.hpp
Labels: type: cleanup / refactor, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3477 fix: fix issue #2615
  src/coreComponents/mesh/FieldIdentifiers.hpp
  src/coreComponents/mesh/mpiCommunications/NeighborCommunicator.cpp
Labels: type: cleanup / refactor, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3478 fix: fix small typo in ATS docs
  .github/workflows/ci_tests.yml
  src/docs/sphinx/developerGuide/Contributing/IntegratedTests.rst
Labels: type: documentation, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3422 refactor: cleanup setMGRStrategy a bit
  src/coreComponents/physicsSolvers/contact/SolidMechanicsEmbeddedFractures.cpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsEmbeddedFractures.hpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.cpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.hpp
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.hpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEmbeddedFractures.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEmbeddedFractures.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoirAndWells.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
Labels: type: cleanup / refactor, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3388 feat: Enable fully coupled mode for CompositionalMultiphaseReservoirPoromechanics and SinglePhaseReservoirPoromechanics
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp
Labels: type: feature, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3490 fix: remove setNextDt from SolidMechanicsLagrangeContact
  .integrated_tests.yaml
  BASELINE_NOTES.md
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.cpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.hpp
Labels: type: bug, ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests, ci: run code coverage

#3479 test: refine comp flow tests
  .integrated_tests.yaml
  BASELINE_NOTES.md
  inputFiles/compositionalMultiphaseFlow/2ph_cap_1d_ihu.xml
  inputFiles/compositionalMultiphaseFlow/4comp_2ph_1d.xml
  inputFiles/compositionalMultiphaseFlow/4comp_2ph_cap_1d.xml
  inputFiles/compositionalMultiphaseFlow/co2_flux_3d.xml
  inputFiles/compositionalMultiphaseFlow/co2_flux_dirichlet.xml
  inputFiles/compositionalMultiphaseFlow/co2_hybrid_1d.xml
  inputFiles/compositionalMultiphaseFlow/compositionalMultiphaseFlow.ats
  inputFiles/compositionalMultiphaseFlow/deadoil_2ph_staircase_gravity_segregation_3d.xml
  inputFiles/compositionalMultiphaseFlow/deadoil_3ph_baker_1d.xml
  inputFiles/compositionalMultiphaseFlow/deadoil_3ph_corey_1d.xml
  inputFiles/compositionalMultiphaseFlow/deadoil_3ph_corey_1d_fractured.xml
  inputFiles/compositionalMultiphaseFlow/deadoil_3ph_staircase_3d.xml
  inputFiles/compositionalMultiphaseFlow/deadoil_3ph_staircase_hybrid_3d.xml
  inputFiles/compositionalMultiphaseFlow/deadoil_3ph_staircase_obl_3d.xml
  inputFiles/compositionalMultiphaseFlow/deadoil_3ph_stone2_1d.xml
Labels: type: testing, ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests, ci: run code coverage

#3491 fix: fix remaining copyright errors
  src/conf.py
  src/coreComponents/physicsSolvers/inducedSeismicity/QuasiDynamicEQRK32.cpp
  src/coreComponents/physicsSolvers/inducedSeismicity/QuasiDynamicEQRK32.hpp
Labels: ci: run CUDA builds, ci: run integrated tests, ci: run code coverage

#3466 fix: an issue of established f-m connections being duplicated in the run time.
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.cpp
Labels: type: bug, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3493 docs: update publications
  src/docs/sphinx/Publications.rst
Labels: type: documentation, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, flag: no rebaseline, ci: run code coverage
