Repository GEOS-DEV/GEOS, pull requests merged in 2024-03, with the labels that each got.

#3034 Bugfix: min vs lowest
  src/coreComponents/mesh/utilities/ComputationalGeometry.hpp
Labels: type: bug, ci: ready to be merged, ci: run integrated tests, flag: no rebaseline

#2991 Get cpu integrated tests running on streak.
  .github/workflows/build_and_test.yml
  .github/workflows/ci_tests.yml
  scripts/ci_build_and_test_in_container.sh
  src/coreComponents/fileIO/timeHistory/HDFFile.cpp
Labels: ci: ready to be merged, ci: run integrated tests

#3022 Load pretty printers for LvArray in codespace
  .devcontainer/postCreateCommand.sh
Labels: ci: ready to be merged, ci: run integrated tests, flag: no rebaseline

#3028 Correct METIS version
  src/coreComponents/mainInterface/version.cpp
Labels: ci: ready to be merged, flag: ready for review, ci: run integrated tests

#3033 Remove wrong zero diag check
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseBaseKernels.hpp
Labels: ci: ready to be merged, ci: run integrated tests, flag: no rebaseline

#3042 Fix "status 137" error on streak
  .github/workflows/ci_tests.yml
Labels: ci: ready to be merged, ci: run integrated tests, flag: no rebaseline

#3024 Allow building GEOS with `clang >= 15`
  .devcontainer/devcontainer.json
  .github/workflows/build_and_test.yml
  .github/workflows/ci_tests.yml
  src/cmake/thirdparty/SetupGeosxThirdParty.cmake
  src/coreComponents/mesh/generators/CellBlockManager.cpp
Labels: type: build system, ci: ready to be merged, flag: requires updated TPL(s), flag: TPL(s) build check, flag: no rebaseline

#2820 Implement Spycher-Pruess solubility tables
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/CO2BrineFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/CO2BrineFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2SolubilityDuanSun.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2SolubilityDuanSun.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2SolubilitySpycherPruess.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2SolubilitySpycherPruess.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PVTFunctionHelpers.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PVTFunctionHelpers.hpp
  src/coreComponents/unitTests/constitutiveTests/CMakeLists.txt
  src/coreComponents/unitTests/constitutiveTests/testCO2SpycherPruessModels.cpp
  src/coreComponents/unitTests/constitutiveTests/testPVT_CO2Brine.xml
  src/coreComponents/unitTests/constitutiveTests/testPVT_CO2Brine_testCo2SpycherPruessBrinePhillipsMixtureA.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_CO2Brine_testCo2SpycherPruessBrinePhillipsMixtureB.txt
  src/coreComponents/unitTests/constitutiveTests/testPVT_data/carbonDioxideSpycherPruessFlash.txt
Labels: type: feature, ci: ready to be merged, spe11, flag: no rebaseline

#2962 Make dependabot watch github-actions updates
  .github/dependabot.yml
Labels: ci: ready to be merged, flag: ready for review, type: CI, flag: no rebaseline

#3038 Reassess include of the mesh generators
  src/coreComponents/common/MpiWrapper.hpp
  src/coreComponents/mesh/generators/CellBlock.hpp
  src/coreComponents/mesh/generators/CellBlockUtilities.cpp
  src/coreComponents/mesh/generators/CollocatedNodes.cpp
  src/coreComponents/mesh/generators/CollocatedNodes.hpp
  src/coreComponents/mesh/generators/InternalMeshGenerator.cpp
  src/coreComponents/mesh/generators/InternalWellboreGenerator.cpp
  src/coreComponents/mesh/generators/LineBlock.cpp
  src/coreComponents/mesh/generators/LineBlock.hpp
  src/coreComponents/mesh/generators/LineBlockABC.hpp
  src/coreComponents/mesh/generators/MeshGeneratorBase.hpp
  src/coreComponents/mesh/generators/PTScotchInterface.hpp
  src/coreComponents/mesh/generators/ParticleBlock.cpp
  src/coreComponents/mesh/generators/ParticleBlock.hpp
  src/coreComponents/mesh/generators/ParticleBlockABC.hpp
  src/coreComponents/mesh/generators/ParticleBlockManager.cpp
  src/coreComponents/mesh/generators/ParticleBlockManager.hpp
  src/coreComponents/mesh/generators/ParticleBlockManagerABC.hpp
  src/coreComponents/mesh/generators/ParticleMeshGenerator.cpp
  src/coreComponents/mesh/generators/ParticleMeshGenerator.hpp
  src/coreComponents/mesh/generators/VTKFaceBlockUtilities.cpp
  src/coreComponents/mesh/generators/VTKFaceBlockUtilities.hpp
  src/coreComponents/mesh/generators/VTKMeshGenerator.cpp
  src/coreComponents/mesh/generators/VTKMeshGenerator.hpp
  src/coreComponents/mesh/generators/VTKMeshGeneratorTools.cpp
  src/coreComponents/mesh/generators/VTKMeshGeneratorTools.hpp
  src/coreComponents/mesh/generators/VTKUtilities.hpp
  src/coreComponents/mesh/generators/VTKWellGenerator.cpp
  src/coreComponents/mesh/generators/VTKWellGenerator.hpp
Labels: ci: ready to be merged, flag: no rebaseline

#2394 Implementing hybrid upwinding for total velocity schemes
  inputFiles/compositionalMultiphaseFlow/4comp_2ph_cap_1d_upwind.xml
  inputFiles/compositionalMultiphaseFlow/pvdg_m.txt
  inputFiles/compositionalMultiphaseFlow/pvdo_m.txt
  src/coreComponents/finiteVolume/FluxApproximationBase.cpp
  src/coreComponents/finiteVolume/FluxApproximationBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseFVMKernelUtilities.hpp
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseFVMKernels.hpp
  src/coreComponents/schema/docs/TwoPointFluxApproximation.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/unitTests/fluidFlowTests/CMakeLists.txt
Labels: ci: ready to be merged, flag: requires rebaseline, ci: run integrated tests

#3046 Replace result_of of invoke_result to fix macOS compilation.
  src/coreComponents/codingUtilities/Utilities.hpp
Labels: type: bug, ci: ready to be merged, flag: no rebaseline

#3040 Modifying rst table type names
  scripts/SchemaToRSTDocumentation.py
Labels: type: documentation, ci: ready to be merged, flag: no rebaseline

#3047 Small fix in SinglePhasePoromechanicsConformingFractures MGR strategy
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhasePoromechanicsConformingFractures.hpp
Labels: ci: ready to be merged, flag: ready for review, flag: no rebaseline

#3048 Fix solubility message
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWellKernels.cpp
Labels: type: bug, ci: ready to be merged, flag: no rebaseline

#2989 Refactor wave solvers: separation of time and space update inside wave solvers
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/wavePropagation/AcousticElasticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticTimeSchemeSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticVTIWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcoustoElasticTimeSchemeSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticTimeSchemeSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEM.cpp
  src/coreComponents/unitTests/wavePropagationTests/CMakeLists.txt
  src/coreComponents/unitTests/wavePropagationTests/testWavePropagationQ2.cpp
Labels: type: cleanup / refactor, ci: ready to be merged, flag: ready for review, ci: run integrated tests

#2963 documentation for VTKWell
  inputFiles/compositionalMultiphaseWell/benchmarks/Egg/deadOilEggVTK_benchmark.xml
  src/docs/sphinx/basicExamples/multiphaseFlowWithWells/Example.rst
Labels: type: documentation, ci: ready to be merged
