Repository GEOS-DEV/GEOS, pull requests merged in 2024-07, with the labels that each got.

#3196 Bugfix/fix issue 2853 with flag
  .integrated_tests.yaml
  BASELINE_NOTES.md
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.cpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.hpp
Labels: ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests

#3190 Fix compilation warnings.
  src/coreComponents/mesh/FaceElementSubRegion.cpp
  src/coreComponents/physicsSolvers/SolverBase.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsMPM.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsMPM.hpp
Labels: ci: run CUDA builds, ci: run integrated tests

#3195 Update rst files and schema
  src/coreComponents/schema/docs/AcousticElasticSEM.rst
  src/coreComponents/schema/docs/AcousticFirstOrderSEM.rst
  src/coreComponents/schema/docs/AcousticSEM.rst
  src/coreComponents/schema/docs/AcousticVTISEM.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseFVM.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseHybridFVM.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseReservoir.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseReservoirPoromechanics.rst
  src/coreComponents/schema/docs/CompositionalMultiphaseWell.rst
  src/coreComponents/schema/docs/ElasticFirstOrderSEM.rst
  src/coreComponents/schema/docs/ElasticSEM.rst
  src/coreComponents/schema/docs/EmbeddedSurfaceGenerator.rst
  src/coreComponents/schema/docs/FlowProppantTransport.rst
  src/coreComponents/schema/docs/Hydrofracture.rst
  src/coreComponents/schema/docs/LaplaceFEM.rst
  src/coreComponents/schema/docs/MultiphasePoromechanics.rst
  src/coreComponents/schema/docs/MultiphasePoromechanicsReservoir.rst
  src/coreComponents/schema/docs/PhaseFieldDamageFEM.rst
  src/coreComponents/schema/docs/PhaseFieldFracture.rst
  src/coreComponents/schema/docs/ProppantTransport.rst
  src/coreComponents/schema/docs/ReactiveCompositionalMultiphaseOBL.rst
  src/coreComponents/schema/docs/SeismicityRate.rst
  src/coreComponents/schema/docs/SinglePhaseFVM.rst
  src/coreComponents/schema/docs/SinglePhaseHybridFVM.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanics.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanicsConformingFractures.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanicsEmbeddedFractures.rst
  src/coreComponents/schema/docs/SinglePhasePoromechanicsReservoir.rst
  src/coreComponents/schema/docs/SinglePhaseProppantFVM.rst
  src/coreComponents/schema/docs/SinglePhaseReservoir.rst
  src/coreComponents/schema/docs/SinglePhaseReservoirPoromechanics.rst
  src/coreComponents/schema/docs/SinglePhaseWell.rst
  src/coreComponents/schema/docs/SolidMechanicsEmbeddedFractures.rst
  src/coreComponents/schema/docs/SolidMechanicsLagrangeContact.rst
  src/coreComponents/schema/docs/SolidMechanicsLagrangianSSLE.rst
  src/coreComponents/schema/docs/SolidMechanics_LagrangianFEM.rst
  src/coreComponents/schema/docs/SolidMechanics_MPM.rst
  src/coreComponents/schema/docs/Solvers.rst
  src/coreComponents/schema/docs/Solvers_other.rst
  src/coreComponents/schema/docs/SurfaceGenerator.rst
  src/coreComponents/schema/docs/Tasks.rst
  src/coreComponents/schema/docs/Tasks_other.rst
  src/coreComponents/schema/docs/VTK.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/docs/sphinx/CompleteXMLSchema.rst
Labels: type: documentation, ci: run CUDA builds, ci: run integrated tests

#3006 Implemented face-based lagrange contact solver with VEM
  .integrated_tests.yaml
  BASELINE_NOTES.md
  inputFiles/lagrangianContactMechanics/ContactMechanics_PEBICrack_base.xml
  inputFiles/lagrangianContactMechanics/ContactMechanics_PEBICrack_smoke.xml
  inputFiles/lagrangianContactMechanics/contactMechanics.ats
  inputFiles/lagrangianContactMechanics/contact_vem.vtm
  inputFiles/lagrangianContactMechanics/domain_id.vtu
  inputFiles/lagrangianContactMechanics/fracture_id_new.vtu
  inputFiles/poromechanicsFractures/PoroElastic_dfm_PEBICrack_base.xml
  inputFiles/poromechanicsFractures/PoroElastic_dfm_PEBICrack_smoke.xml
  inputFiles/poromechanicsFractures/displacedFault.vtm
  inputFiles/poromechanicsFractures/domain_res5_id.vtu
  inputFiles/poromechanicsFractures/fracture_res5_id.vtu
  inputFiles/poromechanicsFractures/poromechanicsFractures.ats
  src/coreComponents/mesh/utilities/ComputationalGeometry.hpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.cpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.hpp
Labels: ci: run CUDA builds, flag: ready for review, flag: requires rebaseline, ci: run integrated tests

#3201 Remove array1d inside kernels
  host-configs/apple/macOS_base.cmake
  src/coreComponents/mesh/FaceManager.hpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.cpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp
Labels: ci: run CUDA builds, ci: run integrated tests

#3052 Umpire logs refactor - table output + adding percentages
  src/coreComponents/common/CMakeLists.txt
  src/coreComponents/common/MemoryInfos.cpp
  src/coreComponents/common/MemoryInfos.hpp
  src/coreComponents/common/initializeEnvironment.cpp
Labels: ci: run CUDA builds, ci: run integrated tests

#3067 Host configs for new LLNL machines + cuda12
  .devcontainer/devcontainer.json
  .github/workflows/ci_tests.yml
  host-configs/LLNL/dane-gcc-12.cmake
  host-configs/LLNL/lassen-base.cmake
  host-configs/LLNL/lassen-clang-13-cuda-12.cmake
  host-configs/LLNL/llnl-cpu-base.cmake
  host-configs/LLNL/quartz-clang-14.cmake
  host-configs/LLNL/quartz-gcc-12.cmake
  host-configs/LLNL/quartz-icc-19.cmake
  host-configs/LLNL/ruby-clang-14.cmake
  host-configs/LLNL/ruby-gcc-12.cmake
  host-configs/environment.cmake
  src/cmake/thirdparty/SetupGeosxThirdParty.cmake
Labels: ci: run CUDA builds, flag: requires updated TPL(s), ci: run integrated tests

#3166 Remove EOS template parameter from compositional fluid model
  src/coreComponents/constitutive/CMakeLists.txt
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidSelector.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/PVTDriverRunTestCompositionalPR.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/PVTDriverRunTestCompositionalSRK.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/PVTDriverRunTestCompositionalTwoPhaseConstantViscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/PVTDriverRunTestCompositionalTwoPhaseLohrenzBrayClarkViscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/FugacityCalculator.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/NegativeTwoPhaseFlash.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/functions/StabilityTest.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/CompositionalDensity.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/CompositionalDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/EquationOfState.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/LohrenzBrayClarkViscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/NegativeTwoPhaseFlashModel.cpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/models/NegativeTwoPhaseFlashModel.hpp
  src/coreComponents/constitutive/unitTests/testCompositionalDensity.cpp
  src/coreComponents/constitutive/unitTests/testLohrenzBrayClarkViscosity.cpp
  src/coreComponents/constitutive/unitTests/testNegativeTwoPhaseFlash.cpp
  src/coreComponents/constitutive/unitTests/testNegativeTwoPhaseFlash9Comp.cpp
  src/coreComponents/constitutive/unitTests/testStabilityTest2Comp.cpp
  src/coreComponents/constitutive/unitTests/testStabilityTest9Comp.cpp
  src/coreComponents/schema/docs/CompositionalTwoPhaseFluid.rst
  src/coreComponents/schema/docs/CompositionalTwoPhaseFluidLohrenzBrayClark.rst
  src/coreComponents/schema/docs/CompositionalTwoPhaseFluidLohrenzBrayClark_other.rst
  src/coreComponents/schema/docs/CompositionalTwoPhaseFluidSoaveRedlichKwong.rst
  src/coreComponents/schema/docs/CompositionalTwoPhaseFluidSoaveRedlichKwongLBC.rst
  src/coreComponents/schema/docs/CompositionalTwoPhaseFluidSoaveRedlichKwongLBC_other.rst
  src/coreComponents/schema/docs/CompositionalTwoPhaseFluidSoaveRedlichKwong_other.rst
  src/coreComponents/schema/docs/CompositionalTwoPhaseFluid_other.rst
  src/coreComponents/schema/docs/Constitutive.rst
  src/coreComponents/schema/docs/Constitutive_other.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/constitutiveTests/testPVT_Compositional.xml
  src/docs/sphinx/CompleteXMLSchema.rst
Labels: type: cleanup / refactor, ci: run CUDA builds, flag: ready for review, ci: run integrated tests

#3200 Disable generation of globalIDs in GEOS for fracture meshes
  src/coreComponents/mesh/ElementType.hpp
  src/coreComponents/mesh/generators/VTKUtilities.cpp
Labels: type: bug, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, flag: no rebaseline

#3189 Comments/Documentation for New Ghosting Architecture
  src/coreComponents/common/initializeEnvironment.hpp
  src/coreComponents/mainInterface/ProblemManager.cpp
  src/coreComponents/mainInterface/ProblemManager.hpp
  src/coreComponents/mainInterface/initialization.cpp
  src/coreComponents/mesh/generators/BuildPods.cpp
  src/coreComponents/mesh/generators/NewGhosting.cpp
  src/coreComponents/mesh/generators/NewGlobalNumbering.cpp
Labels: type: documentation

#3211 docs: Fixing python scripts in tutorials
  src/docs/sphinx/advancedExamples/validationStudies/poromechanics/mandel/mandelFigure.py
  src/docs/sphinx/basicExamples/poromechanics/poromechanicsFigure.py
Labels: type: documentation, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline

#3043 ci: Check that PR title follows conventional commit prefix
  .github/workflows/ci_tests.yml
Labels: ci: run CUDA builds, flag: ready for review, type: CI, ci: run integrated tests, flag: no rebaseline

#3207 fix: Check for existence of_ SC_AVPHYS_PAGES to fix MacOS compilation.
  .github/workflows/ci_tests.yml
  src/coreComponents/common/MemoryInfos.cpp
Labels: ci: run CUDA builds

#3199 MGR improvements
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGR.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreUtils.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/MultiphasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/MultiphasePoromechanicsReservoirFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhasePoromechanicsConformingFractures.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhasePoromechanicsEmbeddedFractures.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SinglePhasePoromechanicsReservoirFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/SolidMechanicsEmbeddedFractures.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalMultiphasePoromechanics.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalSinglePhasePoromechanics.hpp
  src/coreComponents/physicsSolvers/solidMechanics/kernels/ExplicitMPM.hpp
Labels: flag: ready for review, flag: requires updated TPL(s)

#3194 fix: Use aperture table in poromechanics with conforming fractures
  .integrated_tests.yaml
  BASELINE_NOTES.md
  src/coreComponents/physicsSolvers/contact/ContactSolverBase.cpp
  src/coreComponents/physicsSolvers/contact/ContactSolverBase.hpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsALMKernels.hpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBaseFields.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp
  src/coreComponents/physicsSolvers/multiphysics/poromechanicsKernels/SinglePhasePoromechanicsFractures.hpp
  src/coreComponents/schema/docs/Hydrofracture.rst
Labels: ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests

#3220 docs: Update the documentation with conventional commit prefixes
  src/docs/sphinx/developerGuide/Contributing/GitWorkflow.rst
Labels: type: documentation, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline

#3216 docs: update publications
  src/docs/sphinx/Publications.rst
Labels: type: documentation, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, flag: no rebaseline

#3225 fix: another shot to fix workflow
  .github/workflows/ci_tests.yml
Labels: ci: run CUDA builds, ci: run integrated tests

#3213 refactor: Add component selector for fluid models
  .integrated_tests.yaml
  BASELINE_NOTES.md
  inputFiles/compositionalMultiphaseFlow/co2_flux_dirichlet.xml
  inputFiles/compositionalMultiphaseFlow/compositionalMultiphaseFlow.ats
  src/coreComponents/common/TypeDispatch.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/CO2BrineFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/CO2BrineFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidBase.hpp
  src/coreComponents/constitutive/fluid/multifluid/MultiFluidSelector.hpp
  src/coreComponents/constitutive/fluid/multifluid/blackOil/BlackOilFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/blackOil/BlackOilFluidBase.cpp
  src/coreComponents/constitutive/fluid/multifluid/blackOil/DeadOilFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/blackOil/DeadOilFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluid.hpp
  src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluidPVTPackage.hpp
  src/coreComponents/constitutive/unitTests/CMakeLists.txt
  src/coreComponents/constitutive/unitTests/testMultiFluidSelector.cpp
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseFVMKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/ThermalCompositionalMultiphaseFVMKernels.hpp
Labels: type: cleanup / refactor, ci: run CUDA builds, flag: ready for review, flag: requires rebaseline, ci: run integrated tests

#3239 refactor: Towards modularization of physicsSolver
  src/cmake/GeosxOptions.cmake
  src/coreComponents/fieldSpecification/CMakeLists.txt
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/contact/CMakeLists.txt
  src/coreComponents/physicsSolvers/fluidFlow/CMakeLists.txt
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/ReactiveCompositionalMultiphaseOBL.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SourceFluxStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SourceFluxStatistics.hpp
  src/coreComponents/physicsSolvers/inducedSeismicity/CMakeLists.txt
  src/coreComponents/physicsSolvers/multiphysics/CMakeLists.txt
  src/coreComponents/physicsSolvers/python/CMakeLists.txt
  src/coreComponents/physicsSolvers/simplePDE/CMakeLists.txt
  src/coreComponents/physicsSolvers/solidMechanics/CMakeLists.txt
  src/coreComponents/physicsSolvers/surfaceGeneration/CMakeLists.txt
  src/coreComponents/physicsSolvers/wavePropagation/CMakeLists.txt
  src/coreComponents/schema/docs/ChomboIO.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/unitTests/CMakeLists.txt
  src/coreComponents/unitTests/fluidFlowTests/testCompFlowUtils.hpp
  src/coreComponents/unitTests/fluidFlowTests/testFlowStatistics.cpp
  src/pygeosx/pygeosx.cpp
  src/pygeosx/pygeosx.hpp
Labels: type: cleanup / refactor, ci: run CUDA builds, ci: run integrated tests

#3233 feat: Check pore volume for all element types
  .integrated_tests.yaml
  BASELINE_NOTES.md
  inputFiles/almContactMechanics/ALM_stickFault_base.xml
  inputFiles/lagrangianContactMechanics/ContactMechanics_PEBICrack_base.xml
  inputFiles/lagrangianContactMechanics/ContactMechanics_PassingCrack_base.xml
  inputFiles/lagrangianContactMechanics/ContactMechanics_SimpleCubes_base.xml
  inputFiles/lagrangianContactMechanics/ContactMechanics_SingleFracCompression_base.xml
  inputFiles/lagrangianContactMechanics/ContactMechanics_TFrac_base.xml
  inputFiles/lagrangianContactMechanics/ContactMechanics_UnstructuredCrack_base.xml
  inputFiles/lagrangianContactMechanics/ContactMechanics_slippingFault_base.xml
  inputFiles/lagrangianContactMechanics/Sneddon_contactMechanics_base.xml
  inputFiles/wellbore/CasedElasticWellbore_ImperfectInterfaces_base.xml
  src/coreComponents/mesh/SurfaceElementRegion.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
Labels: ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests

#3215 refactor: fix creation of mass handling.
  .integrated_tests.yaml
  BASELINE_NOTES.md
  src/coreComponents/mesh/SurfaceElementRegion.cpp
  src/coreComponents/mesh/SurfaceElementSubRegion.cpp
  src/coreComponents/mesh/SurfaceElementSubRegion.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBaseFields.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/ThermalSinglePhaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/multiphysics/HydrofractureSolver.cpp
Labels: ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests

#3242 docs: Fix wrong variable names in doc after PR #3219 (GEOSX_ -> GEOS_).
  src/docs/sphinx/buildGuide/BuildProcess.rst
  src/docs/sphinx/buildGuide/ContinuousIntegration.rst
Labels: type: documentation, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, flag: no rebaseline

#3244 fix: Fix link flags after pr#3219
  src/coreComponents/unitTests/constitutiveTests/CMakeLists.txt
  src/coreComponents/unitTests/fieldSpecificationTests/CMakeLists.txt
  src/coreComponents/unitTests/finiteVolumeTests/CMakeLists.txt
  src/coreComponents/unitTests/fluidFlowTests/CMakeLists.txt
  src/externalComponents/CMakeLists.txt
Labels: type: bug, type: build system, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, flag: no rebaseline

#3238 chore: Add myself to constitutive
  .github/CODEOWNERS
Labels: flag: ready for review

#3246 feat: Add partition information to terminal output
  .github/CODEOWNERS
  src/coreComponents/common/Logger.hpp
  src/coreComponents/mainInterface/ProblemManager.cpp
  src/coreComponents/mesh/DomainPartition.cpp
  src/coreComponents/mesh/DomainPartition.hpp
Labels: ci: run CUDA builds, ci: run integrated tests
