Repository GEOS-DEV/GEOS, pull requests merged in 2024-01, with the labels that each got.

#2916 Fix issue #2871
  src/coreComponents/constitutive/capillaryPressure/BrooksCoreyCapillaryPressure.cpp
Labels: ci: ready to be merged, flag: no rebaseline

#2913 Poromechanics solvers cleanup
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.hpp
  src/coreComponents/physicsSolvers/multiphysics/PoromechanicsSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.hpp
Labels: type: cleanup / refactor, ci: ready to be merged, flag: no rebaseline

#2920 fix multiple tutorial problems
  src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/sneddon/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/sneddon/displacementJump_contactMechanics.hdf5
  src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/sneddon/displacementJump_embeddedFrac.hdf5
  src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/sneddon/displacementJump_hydroFrac.hdf5
  src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/sneddon/sneddonFigure.py
  src/docs/sphinx/advancedExamples/validationStudies/poromechanics/mandel/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/poromechanics/mandel/Mandel_Verification.png
  src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/pureThermalDiffusion/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/pureThermalDiffusion/radialThermalDiffusionResults.png
Labels: type: documentation, ci: ready to be merged, flag: no rebaseline

#2921 Some random flow solver cleanup
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/IsothermalCompositionalMultiphaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.hpp
  src/coreComponents/unitTests/fluidFlowTests/testCompFlowUtils.hpp
Labels: type: cleanup / refactor, ci: ready to be merged, flag: no rebaseline

#2911 Correct errors in wave propagation xml files
  inputFiles/wavePropagation/acous3D_Q5_abc_smoke.xml
  inputFiles/wavePropagation/acous3D_Q5_small_base.xml
  inputFiles/wavePropagation/benchmarks/acous3D_benchmark_base.xml
  inputFiles/wavePropagation/benchmarks/elas3D_benchmark_base.xml
  inputFiles/wavePropagation/elas3D_Q5_firstOrder_small_base.xml
  inputFiles/wavePropagation/elas3D_Q5_small_base.xml
Labels: type: bug, ci: ready to be merged, ci: run integrated tests, flag: no rebaseline

#2931 Fix a typo in Example2.rst
  src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/deviatedPoroElasticWellbore/Example2.rst
Labels: type: documentation, ci: ready to be merged, flag: no rebaseline

#2910 Fix compilation issues and PVT Driver unit test on Pangea3
  host-configs/TOTAL/pangea3-gcc8.4.1-openmpi-4.1.2.cmake
  src/coreComponents/constitutive/fluid/multifluid/PVTDriverRunTest.hpp
Labels: type: bug, ci: ready to be merged, flag: ready for review, flag: requires updated TPL(s), flag: no rebaseline

#2934 Updating paths to data repo
  inputFiles/compositionalMultiphaseWell/benchmarks/Class09Pb3/class09_pb3_benchmark.xml
  inputFiles/compositionalMultiphaseWell/benchmarks/Egg/deadOilEgg_benchmark.xml
  inputFiles/poromechanics/PoroElastic_Mandel_prism6_benchmark.xml
  inputFiles/poromechanics/nonlinearAcceleration/smallEggModel/smallEggModel.xml
  inputFiles/poromechanicsFractures/PoroElastic_efem-edfm_eggModel_large.xml
  inputFiles/poromechanicsFractures/PoroElastic_efem-edfm_eggModel_small.xml
  inputFiles/thermoPoromechanicsFractures/ThermoPoroElastic_efem-edfm_eggModel_small.xml
  src/docs/sphinx/advancedExamples/validationStudies/carbonStorage/isothermalHystInjection/Example.rst
  src/docs/sphinx/basicExamples/multiphaseFlowWithWells/Example.rst
Labels: type: cleanup / refactor, ci: ready to be merged, flag: ready for review

#2943 Add action trigger for push to develop
  .github/workflows/ci_tests.yml
Labels: ci: ready to be merged

#2938 Apply min comp dens treatment for initial conditions
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
Labels: ci: ready to be merged, flag: ready for review, flag: no rebaseline

#2904 More single phase outputs
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBaseKernels.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseStatistics.hpp
Labels: ci: ready to be merged, flag: no rebaseline

#2944 Misc cleanup of CI and README
  .github/workflows/ci_tests.yml
  README.md
Labels: ci: ready to be merged

#2927 Use `LvArray::math` functions
  src/coreComponents/physicsSolvers/wavePropagation/ElasticFirstOrderWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/WaveSolverUtils.hpp
Labels: ci: ready to be merged, ci: run integrated tests, flag: no rebaseline

#2948 find bug with ci tests on develop
  .github/workflows/ci_tests.yml
Labels: ci: ready to be merged

#2951 add workflow_dispatch option to actions
  .github/workflows/ci_tests.yml
Labels: ci: ready to be merged

#2950 2nd attempt to fix develop CI runs
  .github/workflows/ci_tests.yml
Labels: ci: ready to be merged

#2932 Add log for opened deck filepath
  src/coreComponents/common/Path.cpp
  src/coreComponents/common/Path.hpp
  src/coreComponents/dataRepository/Group.cpp
  src/coreComponents/dataRepository/xmlWrapper.cpp
  src/coreComponents/mainInterface/ProblemManager.cpp
Labels: ci: ready to be merged, flag: no rebaseline

#2551 Add a VTK well import
  src/coreComponents/mesh/CMakeLists.txt
  src/coreComponents/mesh/generators/InternalWellGenerator.cpp
  src/coreComponents/mesh/generators/InternalWellGenerator.hpp
  src/coreComponents/mesh/generators/VTKUtilities.cpp
  src/coreComponents/mesh/generators/VTKWellGenerator.cpp
  src/coreComponents/mesh/generators/VTKWellGenerator.hpp
  src/coreComponents/mesh/generators/WellGeneratorABC.hpp
  src/coreComponents/mesh/generators/WellGeneratorBase.cpp
  src/coreComponents/mesh/generators/WellGeneratorBase.hpp
  src/coreComponents/schema/docs/AcousticElasticSEM.rst
  src/coreComponents/schema/docs/AcousticElasticSEM_other.rst
  src/coreComponents/schema/docs/InternalMesh.rst
  src/coreComponents/schema/docs/InternalMesh_other.rst
  src/coreComponents/schema/docs/InternalWell.rst
  src/coreComponents/schema/docs/InternalWellbore.rst
  src/coreComponents/schema/docs/InternalWellbore_other.rst
  src/coreComponents/schema/docs/PorousDamageElasticIsotropic.rst
  src/coreComponents/schema/docs/PorousDamageElasticIsotropic_other.rst
  src/coreComponents/schema/docs/PorousDamageSpectralElasticIsotropic.rst
  src/coreComponents/schema/docs/PorousDamageSpectralElasticIsotropic_other.rst
  src/coreComponents/schema/docs/PorousDamageVolDevElasticIsotropic.rst
  src/coreComponents/schema/docs/PorousDamageVolDevElasticIsotropic_other.rst
  src/coreComponents/schema/docs/VTKMesh.rst
  src/coreComponents/schema/docs/VTKMesh_other.rst
  src/coreComponents/schema/docs/VTKWell.rst
  src/coreComponents/schema/docs/VTKWell_other.rst
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/meshTests/well1.vtk
  src/coreComponents/unitTests/meshTests/well2.vtk
  src/coreComponents/unitTests/wellsTests/testReservoirSinglePhaseMSWells.cpp
  src/docs/sphinx/CompleteXMLSchema.rst
Labels: ci: ready to be merged, flag: ready for review, ci: run integrated tests, flag: no rebaseline

#2946 Use output dir (option "-o") for printing out PVT tables
  src/coreComponents/functions/CMakeLists.txt
  src/coreComponents/functions/TableFunction.cpp
Labels: type: bug, ci: ready to be merged, ci: run integrated tests, flag: no rebaseline
