Repository GEOS-DEV/GEOS, pull requests merged in 2024-04, with the labels that each got.

#2995 Refactor wave solvers: move mass + damping matrix and PML inside dedicated files
  src/coreComponents/physicsSolvers/CMakeLists.txt
  src/coreComponents/physicsSolvers/wavePropagation/AcousticFirstOrderWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticFirstOrderWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticMatricesSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticPMLSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticFirstOrderWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticFirstOrderWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticMatricesSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEM.cpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEMKernel.hpp
Labels: type: cleanup / refactor, ci: ready to be merged, ci: run integrated tests, flag: no rebaseline

#3064 Minor include cleanup for flow solvers
  src/coreComponents/physicsSolvers/SolverBase.cpp
  src/coreComponents/physicsSolvers/SolverBase.hpp
  src/coreComponents/physicsSolvers/contact/SolidMechanicsLagrangeContact.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseHybridFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseHybridFVM.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseProppantBase.cpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/PoromechanicsSolver.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsStateReset.cpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsStatistics.cpp
  src/coreComponents/physicsSolvers/wavePropagation/AcousticElasticWaveEquationSEM.cpp
Labels: ci: ready to be merged, flag: no rebaseline

#3070 Fix broken compilation on Pangea3
  src/coreComponents/physicsSolvers/python/PySolver.cpp
Labels: type: bug, ci: ready to be merged

#3066 Update default hypre parameters
  src/coreComponents/linearAlgebra/interfaces/hypre/HypreMGR.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/HyprePreconditioner.cpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/CompositionalMultiphaseReservoirHybridFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/MultiphasePoromechanicsReservoirFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ReactiveCompositionalMultiphaseOBL.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalCompositionalMultiphaseFVM.hpp
  src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalMultiphasePoromechanics.hpp
  src/coreComponents/linearAlgebra/unitTests/testKrylovSolvers.cpp
  src/coreComponents/linearAlgebra/utilities/LinearSolverParameters.hpp
  src/coreComponents/schema/docs/elementRegionsGroup_other.rst
  src/coreComponents/schema/docs/particleRegionsGroup_other.rst
  src/coreComponents/schema/schema.xsd.other
Labels: type: bug, ci: ready to be merged, flag: ready for review, ci: run integrated tests, flag: no rebaseline

#2685 fix blas lapack links for tests
  src/coreComponents/mesh/unitTests/CMakeLists.txt
Labels: ci: ready to be merged, ci: run integrated tests

#3097 specify self hosted runner labels explicitly
  .github/workflows/ci_tests.yml
Labels: ci: ready to be merged, ci: run integrated tests

#3093 Small clean up for SinglePhasePoromechanicsEmbeddedFractures
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEmbeddedFractures.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEmbeddedFractures.hpp
Labels: ci: ready to be merged, ci: run integrated tests, flag: no rebaseline

#3092 Stabilized Fixed-Stress
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.hpp
Labels: type: feature, ci: ready to be merged, flag: ready for review, ci: run integrated tests, flag: no rebaseline

#3090 Enable CI testing on streak2
  .github/workflows/build_and_test.yml
  .github/workflows/ci_tests.yml
  scripts/ci_build_and_test_in_container.sh
Labels: ci: ready to be merged, ci: run integrated tests, flag: no rebaseline

#3099 Check that useStaticCondensation is not enabled when running SinglePhasePoromechanicsEmbeddedFractures
  src/coreComponents/physicsSolvers/contact/SolidMechanicsEmbeddedFractures.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEmbeddedFractures.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEmbeddedFractures.hpp
Labels: ci: ready to be merged, flag: no rebaseline

#3072 Neumann instead of Dirichlet boundary for 2nd order elastic wave free surface condition
  src/coreComponents/physicsSolvers/wavePropagation/ElasticTimeSchemeSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/ElasticWaveEquationSEM.cpp
Labels: type: bug, ci: ready to be merged, flag: requires rebaseline, ci: run integrated tests

#3102 Change `Unsupported` doc tag to `Best effort`
  src/docs/sphinx/developerGuide/Contributing/Dockerfile-remote-dev.example
  src/docs/sphinx/developerGuide/Contributing/InstallWin.rst
  src/docs/sphinx/developerGuide/Contributing/UsingDocker.rst
Labels: type: documentation, ci: ready to be merged, flag: no rebaseline
