Repository GEOS-DEV/GEOS, pull requests merged in 2025-04, with the labels that each got.

#3453 fix: delta volume fix plus some other stuff
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsEmbeddedFractures.cpp
  src/coreComponents/physicsSolvers/multiphysics/poromechanicsKernels/SinglePhasePoromechanicsEFEM.hpp
Labels: type: cleanup / refactor, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline

#3537 feat: Adding possibility to output all TableFunction in log/CSV + Solving a bug on PVT CSV export
  .integrated_tests.yaml
  BASELINE_NOTES.md
  src/coreComponents/common/CMakeLists.txt
  src/coreComponents/common/Path.cpp
  src/coreComponents/common/Path.hpp
  src/coreComponents/common/Units.hpp
  src/coreComponents/common/format/StringUtilities.cpp
  src/coreComponents/common/format/StringUtilities.hpp
  src/coreComponents/common/format/table/TableData.cpp
  src/coreComponents/common/format/table/TableData.hpp
  src/coreComponents/common/format/table/TableFormatter.cpp
  src/coreComponents/common/format/table/TableFormatter.hpp
  src/coreComponents/common/format/table/TableLayout.cpp
  src/coreComponents/common/format/table/TableLayout.hpp
  src/coreComponents/common/format/table/unitTests/testTable.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/CO2BrineFluid.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/BrineEnthalpy.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/BrineEnthalpy.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Enthalpy.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Enthalpy.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineDensity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineViscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/EzrokhiBrineViscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/FenghourCO2Viscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/FenghourCO2Viscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineDensity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineViscosity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/PhillipsBrineViscosity.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/SpanWagnerCO2Density.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/SpanWagnerCO2Density.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/WaterDensity.cpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/WaterDensity.hpp
  src/coreComponents/constitutive/fluid/multifluid/reactive/ReactiveBrineFluid.cpp
  src/coreComponents/dataRepository/Group.hpp
  src/coreComponents/fieldSpecification/TractionBoundaryCondition.hpp
  src/coreComponents/functions/CMakeLists.txt
  src/coreComponents/functions/FunctionBase.cpp
  src/coreComponents/functions/LogLevelsInfo.hpp
  src/coreComponents/functions/TableFunction.cpp
  src/coreComponents/functions/TableFunction.hpp
  src/coreComponents/linearAlgebra/DofManager.cpp
  src/coreComponents/mesh/DomainPartition.cpp
  src/coreComponents/mesh/generators/VTKUtilities.cpp
  src/coreComponents/physicsSolvers/FieldStatisticsBase.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/ReactiveCompositionalMultiphaseOBL.hpp
  src/coreComponents/physicsSolvers/fluidFlow/SourceFluxStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/SinglePhaseWell.cpp
  src/coreComponents/physicsSolvers/fluidFlow/wells/WellSolverBase.cpp
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/meshTests/CMakeLists.txt
Labels: ci: run CUDA builds, flag: ready for review, flag: requires rebaseline, ci: run integrated tests

#3617 fix: Fix runtime cuda error.
  src/coreComponents/fieldSpecification/TractionBoundaryCondition.cpp
Labels: ci: run CUDA builds, ci: run integrated tests

#3508 refactor: FieldSpecification context when targeting wrong fieldName
  src/coreComponents/fieldSpecification/FieldSpecificationManager.cpp
  src/coreComponents/mesh/ObjectManagerBase.hpp
Labels: type: feature, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3559 refactor: Refactoring raw logs to tables
  src/coreComponents/common/format/table/TableData.hpp
  src/coreComponents/constitutive/fluid/multifluid/CO2Brine/functions/CO2Solubility.cpp
  src/coreComponents/functions/TableFunction.cpp
  src/coreComponents/mesh/DomainPartition.cpp
  src/coreComponents/mesh/mpiCommunications/SpatialPartition.cpp
  src/coreComponents/mesh/mpiCommunications/SpatialPartition.hpp
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp
  src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseStatistics.cpp
Labels: type: bug, type: cleanup / refactor, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3595 fix: update TFrac tutorial example
  inputFiles/lagrangianContactMechanics/ContactMechanics_TFrac_benchmark.xml
  src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/intersectFrac/Example.rst
  src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/intersectFrac/intersectFracFigure.py
Labels: type: documentation, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, flag: no rebaseline, ci: run code coverage

#3615 fix: Log levels generation on documentation generation
  src/coreComponents/dataRepository/LogLevelsRegistry.cpp
  src/coreComponents/dataRepository/unitTests/CMakeLists.txt
  src/coreComponents/dataRepository/unitTests/testDocumentationGeneration.cpp
  src/coreComponents/schema/schema.xsd
Labels: type: bug, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, ci: run code coverage

#3624 fix: time step logic for sequential
  .integrated_tests.yaml
  BASELINE_NOTES.md
  src/coreComponents/physicsSolvers/NonlinearSolverParameters.cpp
  src/coreComponents/physicsSolvers/PhysicsSolverBase.cpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledSolver.hpp
  src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp
Labels: type: bug, ci: run CUDA builds, flag: requires rebaseline, ci: run integrated tests

#3625 fix: remove incorrect use of template keyword in function calls with no template argument list
  src/coreComponents/common/FieldSpecificationOps.hpp
  src/coreComponents/fileIO/vtk/VTKPolyDataWriterInterface.cpp
  src/coreComponents/finiteElement/kernelInterface/InterfaceKernelBase.hpp
  src/coreComponents/finiteElement/kernelInterface/KernelBase.hpp
  src/coreComponents/linearAlgebra/DofManager.cpp
  src/coreComponents/mesh/ElementRegionManager.hpp
  src/coreComponents/mesh/ParticleManager.hpp
  src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.hpp
  src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/PoromechanicsSolver.hpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp
  src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoirAndWells.cpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/acoustic/firstOrderEqn/isotropic/AcousticFirstOrderWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/acoustic/secondOrderEqn/anisotropic/AcousticVTIWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/acoustic/secondOrderEqn/isotropic/AcousticWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/acoustic/shared/AcousticMatricesSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/elastic/firstOrderEqn/isotropic/ElasticFirstOrderWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/elastic/secondOrderEqn/anisotropic/ElasticVTIWaveEquationSEMKernel.hpp
  src/coreComponents/physicsSolvers/wavePropagation/sem/elastic/secondOrderEqn/isotropic/ElasticWaveEquationSEMKernel.hpp
  src/coreComponents/schema/schema.xsd
  src/coreComponents/schema/schema.xsd.other
  src/coreComponents/unitTests/linearAlgebraTests/testDofManagerUtils.hpp
Labels: ci: run CUDA builds, ci: run integrated tests, ci: run code coverage

#3630 fix: remove sfinae in wrapperHelpers::resizeDefault function.
  scripts/setupPythonEnvironment.bash
  src/coreComponents/dataRepository/Wrapper.hpp
  src/coreComponents/dataRepository/wrapperHelpers.hpp
Labels: ci: run CUDA builds, ci: run integrated tests, ci: run code coverage

#3633 fix: compositional statistics output
  src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp
Labels: type: bug, ci: run CUDA builds, ci: run integrated tests, flag: no rebaseline

#3628 fix: Unsafe access to std::vector without bounds check
  src/coreComponents/common/format/table/TableFormatter.cpp
  src/coreComponents/mesh/generators/VTKUtilities.cpp
  src/coreComponents/mesh/mpiCommunications/CommunicationTools.cpp
Labels: type: bug, ci: run CUDA builds, flag: ready for review, ci: run integrated tests, ci: run code coverage
